### PR TITLE
Fix System.shell/2 command escaping on Unix

### PR DESCRIPTION
**Pull request by jonatanklosko**
Given

```elixir
System.shell("x=1; echo $x")
```

we would currently spawn port as

```elixir
Port.open({:spawn, ~s/sh -c "x=1; echo $x"/, ...)
```

and apparently the `$x` is interpolated as empty string, before actually running the shell script, as would happen in shell.

### CODE REVIEW

**Comment by eksperimental** [comment]
Hi @jonatanklosko
Just for the record, I discovered this bug. I was a partial solution to another bug that is still open in the issue tracker. https://github.com/elixir-lang/elixir/issues/11604#issuecomment-1027183635

**Comment by eksperimental** [comment]
> @eksperimental thanks, I totally missed that! I've just realised that escaping single quote within single quote string doesn't work, because escapes are disabled. In bash it's possible to do `$'a \' b'` (the dolar prefix), but that's not the case for sh. Escaping the dolar however works as expected as you said!

Awesome! @jonatanklosko

**Review by whatyouhide — APPROVED** [review]

**Comment by josevalim** [comment]
@jonatanklosko can you please compare our implementation with the one in Erlang and see if there are other improvements we should bring? I wrote a comment about this here: https://github.com/elixir-lang/elixir/issues/11604

**Comment by jonatanklosko** [comment]
@josevalim I improved it to halt when the command awaits stdin as Erlang does. Also, I switched to `:spawn_executable`, this way we don't need to escape the command altogether.

Two differences as compared with Erlang:

* they spawn the shell with `sh -s` which means the script is read from stdin, then they pass send script
* they serialize spawning the port by going through a single process as per [this comment](https://github.com/erlang/otp/blob/8deb96fb1d017307e22d2ab88968b9ef9f1b71d0/lib/kernel/src/os.erl#L222-L225), which I don't really get

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by fuelen** [comment]
Seems like the last file was included by mistake

**Comment by eksperimental** [comment]
> Seems like the last file was included by mistake

Oh.. yes. I will update the ignore rules. Thank you for noticing this @fuelen

**Comment by jonatanklosko** [comment]
Good catch, thanks for fixing @josevalim :)

**Pull request merged**
