### PR TITLE
Upgrade FreeBSD to 13.0 ALPHA in Cirrus CI

### PR DESCRIPTION
**Pull request by eksperimental**
I am upgrading even it is not a stable release yet, to see if test pass

### CODE REVIEW

**Comment by eksperimental** [comment]
The reason it is failing it is because the latest FreeBSD port of Erlang is OTP 21.
Any suggestion?

**Comment by josevalim** [comment]
@eksperimental can we use an alternate package manager for FreeBSD?

**Comment by nifoc** [comment]
FreeBSD has other Erlang versions under the erlang-runtimeX package, where X is 20 to 23.

**Comment by eksperimental** [comment]
> FreeBSD has other Erlang versions under the erlang-runtimeX package, where X is 20 to 23.

There we go.
Your suggestion saved the day @nifoc

**Comment by josevalim** [comment]
So we don’t need the alpha version anymore either, right?

**Comment by eksperimental** [comment]
The other question is, do we want to test it against Erlang/OTP 23?

**Comment by eksperimental** [comment]
> So we don’t need the alpha version anymore either, right?

We can leave it as is, and when 13 gets stable, it will automatically use that one. Or we can set it back to 12.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
