### PR TITLE
Add support for capitalized sharp s

### PR DESCRIPTION
**Pull request by leifg**
As of June 29th 2017, the German institute "Rat für deutsche Rechtschreibung" allows the usage of the capitalized "ß" character in German language ([source](http://www.rechtschreibrat.com/DOX/rfdr_PM_2017-06-29_Aktualisierung_Regelwerk.pdf)). The unicode character itself has been around for a while ([source](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E)).

This PR is a suggestion to change the current behaviour of String.upcase("ß"). It will change in the following way:

Old:
```elixir
String.upcase("ß")
--> "SS"
```

New:
```elixir
String.upcase("ß")
--> "ẞ"
```

Note, the behaviour of `String.downcase("ẞ")` is already correct:

```elixir
String.downcase("ẞ")
--> "ß"
```

Here is the list of pros and cons (that I could come up with):

Pro:
  - Makes up and downcasing consistent: `"straße" |> String.upcase |> String.downcase` will return the initial input

Cons:
  - No need because the "old" way of capitalization is still allowed
  - Breaking Change
  - Character looks hideous in most fonts

I personally am in favor of changing the behaviour. It should happen however in a version where breaking changes are expected anyway.

I'd like to get the input of other german speakers on this.

### CODE REVIEW

**Comment by ericmj** [comment]
It looks like we won't support this until we update to unicode v10, currently we are using v9. I don't think we should manually the unicode source files and instead stay on proper versions.

**Comment by leifg** [comment]
Genuine Question:

Is this change dependent on unicode v10 on a technical level or is switching to v10 just a good milestone to incorporate this change?

**Comment by ericmj** [comment]
Actually it seems it has not been changed in v10, I am afraid this change wont be incorporated until unicode decides to change it.

We need to use the unicode specification because the contract to our users specify that we use unicode, https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/string.ex#L9-L10. We can't say that we are using unicode AND this change in the casing rules for one character.

**Comment by michalmuskala** [comment]
I agree Elixir should follow whatever the Unicode standard does. Otherwise, it has a potential to become a huge mess with exceptions like this.

**Comment by josevalim** [comment]
Elixir doesn't handle locale specific behavior.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by leifg** [comment]
Oh interesting, wasn't aware the special casing file was provided by the unicode standard.

That makes a lot of sense. Let's see if they are going to change that.

**Comment by josevalim** [comment]
Sorry, premature send. So the change needs to be added to Unicode as
@ericmj said (as we dont do locale specific behavior)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Pull request closed without merging**
