### PR TITLE
Mix.Tasks.Format: Fix grammatical error

### PR DESCRIPTION
**Pull request by xtian**
as showed -> as shown

### CODE REVIEW

**Comment by eksperimental** [comment]
Your suggestion seems correct.

**Comment by xtian** [comment]
Yeah, "as shown" how I would write it, but as I wasn't sure after searching for the difference between "showed" and "shown". I'll reopen and let a maintainer decide :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
Great

**Pull request merged**
