### PR TITLE
Provide special case for Enum.random(range)

### PR DESCRIPTION
**Pull request by hauleth**
Now instead of doing slicing and dynamic dispatch it will handle it as
simple random call, multiplication, and addition.

### CODE REVIEW

**Comment by josevalim** [comment]
@hauleth can you please provide a benchmark? The Enumerable.slice implementation is pretty much Range.size + anonymous function. The anonymous function is a single-element list with said addition and multiplication. So the only additional cost is the protocol dispatch and a single-element list, which is probably not worth it.

**Comment by josevalim** [comment]
Closing this, feel free to ping and we will reopen if we see large differences in benchmarks. :)

**Comment by fuelen** [comment]
I made a benchmark :)
```elixir
Mix.install([:benchee])

defmodule NewImpl do
  def random(a..a//_), do: a

  def random(a..b//step = range) do
    case Range.size(range) do
      0 -> raise Enum.EmptyError
      size -> a + random_integer(0, size - 1) * step
    end
  end

  defp random_integer(limit, limit) when is_integer(limit) do
    limit
  end

  defp random_integer(lower_limit, upper_limit) when upper_limit < lower_limit do
    random_integer(upper_limit, lower_limit)
  end

  defp random_integer(lower_limit, upper_limit) do
    lower_limit + :rand.uniform(upper_limit - lower_limit + 1) - 1
  end
end

Benchee.run(
  %{
    "Enum.random" => fn to -> Enum.random(1..to) end,
    "NewImpl.random" => fn to -> NewImpl.random(1..to) end
  },
  inputs: %{
    "10" => 10,
    "100" => 100,
    "1000" => 1000,
    "10_000" => 10_000,
    "100_000" => 100_000
  },
  time: 10,
  memory_time: 2
)
```
<details>
  <summary>Output</summary>

```
Operating System: Linux
CPU Information: AMD Ryzen 7 PRO 6850U with Radeon Graphics
Number of Available Cores: 16
Available memory: 30.13 GB
Elixir 1.15.0-dev
Erlang 25.2

Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
reduction time: 0 ns
parallel: 1
inputs: 10, 100, 1000, 100_000, 10_000
Estimated total run time: 2.33 min

Benchmarking Enum.random with input 10 ...
Benchmarking Enum.random with input 100 ...
Benchmarking Enum.random with input 1000 ...
Benchmarking Enum.random with input 100_000 ...
Benchmarking Enum.random with input 10_000 ...
Benchmarking NewImpl.random with input 10 ...
Benchmarking NewImpl.random with input 100 ...
Benchmarking NewImpl.random with input 1000 ...
Benchmarking NewImpl.random with input 100_000 ...
Benchmarking NewImpl.random with input 10_000 ...

##### With input 10 #####
Name                     ips        average  deviation         median         99th %
NewImpl.random      712.78 K        1.40 μs  ±1746.05%        1.40 μs        1.96 μs
Enum.random         670.24 K        1.49 μs  ±1595.80%        1.40 μs        2.38 μs

Comparison: 
NewImpl.random      712.78 K
Enum.random         670.24 K - 1.06x slower +0.0891 μs

Memory usage statistics:

Name              Memory usage
NewImpl.random           480 B
Enum.random              584 B - 1.22x memory usage +104 B

**All measurements for memory usage were the same**

##### With input 100 #####
Name                     ips        average  deviation         median         99th %
NewImpl.random      719.31 K        1.39 μs  ±1076.71%        1.40 μs        1.96 μs
Enum.random         666.75 K        1.50 μs  ±1779.13%        1.40 μs        2.38 μs

Comparison: 
NewImpl.random      719.31 K
Enum.random         666.75 K - 1.08x slower +0.110 μs

Memory usage statistics:

Name              Memory usage
NewImpl.random           480 B
Enum.random              584 B - 1.22x memory usage +104 B

**All measurements for memory usage were the same**

##### With input 1000 #####
Name                     ips        average  deviation         median         99th %
NewImpl.random      717.47 K        1.39 μs  ±1665.02%        1.40 μs        1.96 μs
Enum.random         668.44 K        1.50 μs  ±2111.33%        1.40 μs        2.38 μs

Comparison: 
NewImpl.random      717.47 K
Enum.random         668.44 K - 1.07x slower +0.102 μs

Memory usage statistics:

Name              Memory usage
NewImpl.random           480 B
Enum.random              584 B - 1.22x memory usage +104 B

**All measurements for memory usage were the same**

##### With input 100_000 #####
Name                     ips        average  deviation         median         99th %
NewImpl.random      713.32 K        1.40 μs  ±1679.21%        1.40 μs        1.96 μs
Enum.random         665.92 K        1.50 μs  ±2141.56%        1.40 μs        2.38 μs

Comparison: 
NewImpl.random      713.32 K
Enum.random         665.92 K - 1.07x slower +0.0998 μs

Memory usage statistics:

Name              Memory usage
NewImpl.random           480 B
Enum.random              584 B - 1.22x memory usage +104 B

**All measurements for memory usage were the same**

##### With input 10_000 #####
Name                     ips        average  deviation         median         99th %
NewImpl.random      709.42 K        1.41 μs  ±1764.52%        1.40 μs        2.30 μs
Enum.random         661.78 K        1.51 μs  ±2191.15%        1.40 μs        2.38 μs

Comparison: 
NewImpl.random      709.42 K
Enum.random         661.78 K - 1.07x slower +0.101 μs

Memory usage statistics:

Name              Memory usage
NewImpl.random           480 B
Enum.random              584 B - 1.22x memory usage +104 B

**All measurements for memory usage were the same**


```
</details>

**Comment by josevalim** [comment]
Thanks. Yeah, I think the current version is fine. :)

**Pull request closed without merging**
