### PR TITLE
explain why receive after :infinity is the same as lack of after …

### PR DESCRIPTION
**Pull request by pavlos**
…clause

### CODE REVIEW

**Comment by pavlos** [comment]
@whatyouhide Yeah, we should probably mention it somewhere else, but I think we should also mention it here.  I put in this PR because it took me a bit of googling to figure out what the point of having :infinity was.

Where do you suggest we mention variable timeouts?

**Comment by whatyouhide** [comment]
@pavlos we can just mention it outside of the bullet list, e.g.:

```markdown
The `after` clause can be specified even if there are no match clauses. The timeout value given to `after` can be a variable; two special values can be used for it:

  * `:infinity` - the process should wait indefinitely for a matching
    message, this is the same as not using a timeout

  * `0` - if there is no matching message in the mailbox, the timeout
    will occur immediately
```

Wdyt?

**Comment by pavlos** [comment]
@whatyouhide I like it - I made the change and will squash it down

**Comment by pavlos** [comment]
@whatyouhide haha, yeah, I caught period that too.  It's getting late :-)

**Comment by whatyouhide** [comment]
Great work @pavlos!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
