### PR TITLE
update url to use https. standardize erlang.org/doc links to use www

### PR DESCRIPTION
**Pull request by eksperimental**
* update URL where the used http link redirects to https, and as well when a package is provided and the https link is available.
* remove period adjacent to URLs.
* standardize erlang.org/doc links to use www

* also update a wikipedia link that redirected to a different page ( https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Non-characters)

### CODE REVIEW

**Comment by lexmag** [comment]
Is there any practical reason to use `www` in erlang.org/doc links?

**Comment by eksperimental** [comment]
@lexmag I corrected the extra w. thanks for noticing that,
Well.. http://erlang.org redirects to http://www.erlang.org

**Comment by lexmag** [comment]
@eksperimental you’re welcome.
Hmm, as I see, http://erlang.org/doc/man/binary.html is a direct link.

**Comment by josevalim** [comment]
Yeah, let's stick with erlang.org because I think only the main site redirects (the docs do not).

**Comment by josevalim** [comment]
Actually, ignore me.

**Comment by eksperimental** [comment]
@josevalim @lexmag yes, I see what you guys mean (and i discourage the use of www, and even worse having two domains serving the same pages), but erlang.org directs to www, then people click on docs, and they end up in www.erlang.org/doc/
(that was my reasoning)

**Pull request merged**
