### PR TITLE
Display file:line in already defined type error message

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
The error message contins the full path to the file, what is the way to display it relative to the current project base dir?

**Comment by josevalim** [comment]
@eksperimental Path.relative_to_cwd

**Comment by eksperimental** [comment]
> @eksperimental Path.relative_to_cwd

I think we are ready to go.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
