### PR TITLE
Code.Fragment handles anonymous function

### LINKED ISSUE #12845: Code.Fragment.cursor_context and var calls
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

Those examples work
```
Code.Fragment.cursor_context("asd.a")
{:dot, {:var, ~c"asd"}, ~c"a"}
Code.Fragment.cursor_context("@asd.a(")
{:dot_call, {:module_attribute, ~c"asd"}, ~c"a"}
Code.Fragment.cursor_context("asd.a(") 
{:dot_call, {:var, ~c"asd"}, ~c"a"}
```
But those return `:none`
```
Code.Fragment.cursor_context("asd.(")                
:none
Code.Fragment.cursor_context("@asd.(")  
:none
```

### Expected behavior

```
Code.Fragment.cursor_context("asd.(")                
{:dot_call, {:var, ~c"asd"}, []}
Code.Fragment.cursor_context("@asd.(")  
{:dot_call, {:module_attribute, ~c"asd"}, []}
```

### PR DESCRIPTION
**Pull request by sabiwara**
Close #12845

This is a proposal and tentative fix, please let me know your thoughts.

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

**Comment by sabiwara** [comment]
Just to confirm: this would be good to support in `surround_context/3` too, right @josevalim ?

**Comment by lukaszsamson** [comment]
> Just to confirm: this would be good to support in `surround_context/3` too

Not sure if it would add value
```
Code.Fragment.surround_context("asd.()", {1, 1})
%{begin: {1, 1}, context: {:local_or_var, ~c"asd"}, end: {1, 4}}
```

**Comment by josevalim** [comment]
Right, if you are around the dot or on the paren, it would be a fun call. Before that it is just a var. :)

**Comment by josevalim** [comment]
But we can also wait until we have a use case. :)

**Comment by sabiwara** [comment]
Makes sense. Will put it on hold until/if there is an actual need, but agreed that the current one is probably good enough 👍

**Pull request merged**
