### PR TITLE
Exposes `Path.expand_dot/1` as a public function

### PR DESCRIPTION
**Pull request by fredwu**
Hi all,

I think `Path.expand_dot/1` is a very useful function for resolving paths, without needing to worry about the added path manipulation from `Path.expand/1-2`.

This PR merely makes the function public, with no change whatsoever to its implementation.

What do you think?

### CODE REVIEW

**Comment by josevalim** [comment]
The issue is that expanding only the dots without the full path can lead to incorrect results. Even after full expansion it can be an issue. Do you have an use case for this?

**Comment by fredwu** [comment]
@josevalim That's true, hence I've added in the doc that this function does not take into account the absolute or relative nature of the path itself.

The use case for me is to resolve a relative link (link B) in a given page path (Link A):

Link A: `foo/bar`
Link B: `../baz`

And I'm expecting `foo/baz` to be the correct output.

I intend to use it to resolve paths in my web crawler: https://github.com/fredwu/crawler/blob/e19de1500485c2808a42545be8f8d6ba1bbfbacd/lib/crawler/linker/path_builder.ex (it would replace the current use of `path |> Path.expand |> Path.relative_to(cwd)`.

**Comment by josevalim** [comment]
To be very honest, I don't think you should use the functions in Path to handle non-file system paths because we will always make assumptions based on those. I would say it is preferrable for you to go with something specific for URIs then.

**Comment by fredwu** [comment]
It's a tricky one as the use case for me isn't strictly URI-related either. A lot of the resolving are needed to translate URI into relative paths that are usable offline, the resolving bit therefore is related to the file-system in this case, but in a "controlled environment" where not expanding it to absolute path still gives correct result.

For now I've lifted the `expand_dot/1` function so I could use it in my lib. It would be nice for this helpful function to be available though. 😅

**Comment by fredwu** [comment]
Thanks @josevalim! I'll close this PR now. :)

**Pull request closed without merging**
