### PR TITLE
Support new gen:stop in GenEvent and GenServer

### PR DESCRIPTION
**Pull request by TattdCodeMonkey**
added stop/3 to GenServer and GenEvent using :gen.stop

### CODE REVIEW

**Comment by TattdCodeMonkey** [comment]
Should the usages of `GenServer.call(server, :stop)` in the tests be replaced with `GenServer.stop(server)` now ?

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by TattdCodeMonkey** [comment]
@lexmag I originally had 5000 matching the default timeout used for `call` but changed to `:infinity` to match the default that OTP uses. https://github.com/erlang/otp/blob/maint/lib/stdlib/src/gen.erl#L238

**Comment by josevalim** [comment]
I have changed it to 5000 in a later commit as we had an earlier discussion on IRC on the topic.

**Comment by TattdCodeMonkey** [comment]
:+1:

**Pull request merged**
