### PR TITLE
[WIP] Delete and regenerate mix.lock on conflict detection

### PR DESCRIPTION
**Pull request by joshprice**
First, rough attempt at solving #6554.

Feedback welcome, especially on the approach and how best to test it. 

/cc @jonrowe

### CODE REVIEW

**Comment by josevalim** [comment]
We cannot delete the lock file because then it means all versions will be recomputed, even the ones that did not conflict, which is most likely very undesired.

In case of conflicts, we need to literally parse the conflicting versions out the lock file, compare those conflicting versions against the allowed requirements in dependencies, merge them and write the new lock to disk.

The first step is probably to change the format of the lock file with one that is less conflict prone. Instead of this:

```elixir
%{"foo": ...,
  "bar": ...}
```

to this:

```elixir
%{
  "foo": ...,
  "bar": ...,
}
```

**Comment by joshprice** [comment]
Agree with the new `mix.lock` format. Had already assumed that the single dep per line will make this a lot easier. I'll give that a go, and also dig further into how yarn is doing it.

**Comment by josevalim** [comment]
Beautiful, we can even tackle those as separate pull requests, so everything becomes a bit easier to handle.

**Comment by josevalim** [comment]
Ping.

**Comment by kelvinst** [comment]
@joshprice are you working on it? Or can I implement the logic @josevalim mentioned?

> In case of conflicts, we need to literally parse the conflicting versions out the lock file, compare those conflicting versions against the allowed requirements in dependencies, merge them and write the new lock to disk.

**Comment by joshprice** [comment]
@kelvinst I haven't had much time to get very far with this, feel free to go ahead and implement. Happy to contribute where I can.

**Comment by josevalim** [comment]
Folks, I will close this PR, since deleting the lock file is not the direction we are going forward. @kelvinst, if you are working on this, please let us know in the main issue so we avoid duplicate work. :heart:

**Pull request closed without merging**
