### PR TITLE
Add hard links

### PR DESCRIPTION
**Pull request by hut8**
As proposed in https://groups.google.com/d/msg/elixir-lang-core/bSDn7lNlOv8/nnybSV27CAAJ

### CODE REVIEW

**Comment by josevalim** [comment]
Can you also please add `ln!` and `ln_s!`? Also please call `IO.chardata_to_string` on the inputs as we do for other functions to guarantee proper utf-8 conversion.

**Comment by hut8** [comment]
Sure thing 😄

**Comment by hut8** [comment]
How does this look? Thanks for getting back to me so quickly 👍 Elixir is amazing and thanks for all your hard work with it.

**Comment by fishcakez** [comment]
Thank you :heart:

**Pull request merged**
