### PR TITLE
Consistency: Use underscore after "my" adjective in underscore

### PR DESCRIPTION
**Pull request by eksperimental**
Additionally, the are still some other changes that could be done of the same kind, but they are all part of tests.
let me know if you want to have consistency in tests as well.

```elixir
$ ag -s "my[a-z0-9]"
...

lib/elixir/test/elixir/kernel/typespec_test.exs
43:    assert_raise CompileError, ~r"invalid type specification: mytype = 1", fn ->
45:        @type mytype = 1
53:        @type mytype :: "foobar"
74:      @type mytype :: term
77:    assert [type: {:mytype, {:type, _, :term, []}, []}] =
101:      @type mytype :: 10
103:    assert [type: {:mytype, {:integer, _, 10}, []}] =
109:      @type mytype :: -10
112:    assert [type: {:mytype, {:op, _, :-, {:integer, _, 10}}, []}] =
129:      @type mytype :: binary
132:    assert [type: {:mytype, {:type, _, :binary, []}, []}] =
138:      @type mytype :: <<>>
141:    assert [type: {:mytype, {:type, _, :binary, [{:integer, _, 0}, {:integer, _, 0}]}, []}] =
147:      @type mytype :: <<_::3>>
150:    assert [type: {:mytype, {:type, _, :binary, [{:integer, _, 3}, {:integer, _, 0}]}, []}] =
156:      @type mytype :: <<_ :: _ * 8>>
159:    assert [type: {:mytype, {:type, _, :binary, [{:integer, _, 0}, {:integer, _, 8}]}, []}] =
165:      @type mytype :: <<_::3, _::_*8>>
168:    assert [type: {:mytype, {:type, _, :binary, [{:integer, _, 3}, {:integer, _, 8}]}, []}] =
175:        @type mytype :: <<_::3*8>>
182:      @type mytype :: 1..10
185:    assert [type: {:mytype, {:type, _, :range, [{:integer, _, 1}, {:integer, _, 10}]}, []}] =
232:        @type mytype :: %ThisModuleDoesNotExist{}
238:        @type mytype :: %TestTypespec{}
247:        @type mytype :: %TestTypespec{no_field: :world}
299:        @type mytype :: record(:this_record_does_not_exist, [])
309:        @type mytype :: record(:timestamp, no_field: :foo)
324:      @type mytype :: []
325:      @type mytype1 :: [integer]
326:      @type mytype2 :: [integer, ...]
329:    assert [type: {:mytype, {:type, _, nil, []}, []},
330:            type: {:mytype1, {:type, _, :list, [{:type, _, :integer, []}]}, []},
331:            type: {:mytype2, {:type, _, :nonempty_list, [{:type, _, :integer, []}]}, []}] =
337:      @type mytype :: (... -> any)
340:    assert [type: {:mytype, {:type, _, :fun, []}, []}] =
346:      @type mytype :: (integer, integer -> integer)
349:    assert [type: {:mytype, {:type, _, :fun, [{:type, _, :product,
357:      @type mytype :: (() -> integer)
360:    assert [type: {:mytype, {:type, _, :fun, [{:type, _, :product, []},
367:      @type mytype :: (... -> integer)
370:    assert [type: {:mytype, {:type, _, :fun, [{:type, _, :any},
402:      @type mytype(x) :: x
403:      @type mytype1(x) :: list(x)
404:      @type mytype2(x, y) :: {x, y}
407:    assert [type: {:mytype, {:var, _, :x}, [{:var, _, :x}]},
408:            type: {:mytype1, {:type, _, :list, [{:var, _, :x}]}, [{:var, _, :x}]},
409:            type: {:mytype2, {:type, _, :tuple, [{:var, _, :x}, {:var, _, :y}]}, [{:var, _, :x}, {:var, _, :y}]}] =
415:      @type mytype :: (named :: integer)
416:      @type mytype1 :: (a :: integer -> integer)
419:    assert [type: {:mytype, {:ann_type, _, [{:var, _, :named}, {:type, _, :integer, []}]}, []},
420:            type: {:mytype1, {:type, _, :fun, [{:type, _, :product, [{:ann_type, _, [{:var, _, :a}, {:type, _, :integer, []}]}]}, {:type, _, :integer, []}]}, []}] =
426:      @opaque mytype(x) :: x
429:    assert [opaque: {:mytype, {:var, _, :x}, [{:var, _, :x}]}] =
435:      @type mytype :: tuple
436:      @opaque mytype1 :: {}
439:    assert [opaque: {:mytype1, _, []},
440:            type: {:mytype, _, []}, ] =
481:      @type mytype :: tuple
482:      @type mytype(a) :: [a]
483:      assert Kernel.Typespec.defines_type?(__MODULE__, :mytype, 0)
484:      assert Kernel.Typespec.defines_type?(__MODULE__, :mytype, 1)
485:      refute Kernel.Typespec.defines_type?(__MODULE__, :mytype, 2)

lib/elixir/test/elixir/exception_test.exs
76:      Code.eval_string("def foo do end", [], file: "myfile")
79:    assert Exception.format_stacktrace(System.stacktrace) =~ "myfile:1: (file)"
84:      Code.eval_string("defmodule FmtStack do raise ArgumentError, ~s(oops) end", [], file: "myfile")
87:    assert Exception.format_stacktrace(System.stacktrace) =~ "myfile:1: (module)"

lib/elixir/test/elixir/uri_test.exs
108:                path: "/mydirectory/myfile.txt", query: nil, fragment: nil,
110:           URI.parse("ftp://user001:secretpassword@private.ftp-servers.example.com/mydirectory/myfile.txt")
116:                path: "/mydirectory/myfile.txt", query: nil, fragment: nil, port: 22} ==
117:           URI.parse("sftp://user001:secretpassword@private.ftp-servers.example.com/mydirectory/myfile.txt")
123:                path: "/mydirectory/myfile.txt", query: nil, fragment: nil, port: 69} ==
124:           URI.parse("tftp://user001:secretpassword@private.ftp-servers.example.com/mydirectory/myfile.txt")
```

### CODE REVIEW

**Comment by lexmag** [comment]
Thank you @eksperimental. 💛

**Comment by lexmag** [comment]
I feel okay about doing so for tests, what does everyone else think?

**Comment by whatyouhide** [comment]
I agree on doing this for tests as well @lexmag.

**Comment by lexmag** [comment]
@eksperimental would you like to make same changes in the tests? Otherwise I can do this myself. :bowtie:

**Comment by eksperimental** [comment]
@lexmag sure. I can take care of that

**Pull request merged**
