### PR TITLE
Improve do_expand_dot private function of path module

### PR DESCRIPTION
**Pull request by MasashiYokota**
I've fixed the `do_expand_dot` private function of the `path` module.
I would be glad if you review this PR. Thank you.

### CODE REVIEW

**Comment by ryanwinchester** [comment]
When you say "fixed", does that mean it was broken?

Then I think if it _was_ broken and still passing tests, maybe you should add test(s) that would fail without your fix?

**Comment by MasashiYokota** [comment]
No. I'm sorry to confuse you. My expression was a bit wrong. This patch is for just only refactoring the `do_expand_dot` function based on [this guide](https://erlang.org/doc/efficiency_guide/functions.html#pattern-matching). 
There are no bugs as far as I know. 

Thank you.

**Comment by josevalim** [comment]
Hi @MasashiYokota, afaik the compiler cannot reorganize based on guards, so this effectively makes no difference. In any case, thanks!

**Comment by MasashiYokota** [comment]
@josevalim 
Thank you for your comment. As embarrassing as this is to say, I didn't know that.

I've re-refactored the function. How about the below code?
``` elixir
defp do_expand_dot(["." | t], [_, _] = acc), do: do_expand_dot(t, acc)
defp do_expand_dot(["." | t], []), do: do_expand_dot(t, [])
defp do_expand_dot([h | t], [_, _] = acc), do: do_expand_dot(t, ["/", h | acc])
defp do_expand_dot([h | t], []), do: do_expand_dot(t, ["/", h])
```

**Comment by josevalim** [comment]
I Iam not sure if it is equivalent. `[_, _]` will only match a list of two elements. But generally speaking, I don't think you should worry about these improvements in general. If they provide any gains, they will be very very very minor.

**Comment by MasashiYokota** [comment]
OK. I understood. Thank you so much.

**Pull request closed without merging**
