### PR TITLE
Use SPDX full name of Apache License 2.0

### PR DESCRIPTION
**Pull request by chulkilee**
https://spdx.org/licenses/Apache-2.0.html

- Full name: Apache License 2.0
- Short identifier: Apache-2.0

### CODE REVIEW

**Comment by eksperimental** [comment]
Whats the benefit of linking to spdx?

**Comment by josevalim** [comment]
@eksperimental it is not linking to SPDX, only standardizing on its names.

**Comment by eksperimental** [comment]
Yes, I realized after I posted the question. That's why I deleted.
thanks anyway

**Comment by fertapric** [comment]
Thanks @chulkilee! 💜

**Pull request merged**
