### PR TITLE
Add default value for List.first/1 and List.last/1

### PR DESCRIPTION
**Pull request by btkostner**
Adds a default field for `List.first/1` and `List.last/1`. Should be pretty simple

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by eksperimental** [comment]
what is the best way to deal with the `@doc since` value in this case?

**Comment by wojtekmach** [comment]
@eksperimental I believe the only way would be to break it up:

```diff
- @doc ...
- def first(list, default \\ nil)
- ...
+ @doc ...
+ def first(list) do
+   first(list, nil)
+ end
+
+ @doc ...
+ @doc since: "1.12.0"
+ def first(list, default) do
+ ...
```

not sure it's worth it though.

**Comment by Eiji7** [comment]
@wojtekmach At first sight I think exactly same … However I would like to mention that there is already a similar case:
https://github.com/elixir-lang/elixir/blob/1145dc01680aab7094f8a6dbd38b65185e14adb4/lib/elixir/lib/enum.ex#L404-L425

That's said in mentioned code `:discard` was never part of public `API` and function has changed its name. On the other hand we have old `chunk/2` and `chunk/3` (now deprecated) and new `chunk_every/2` and `chunk_every/3` with `since` added.

Whatever would be decided I'm really interested see opinions of other people.

**Comment by eksperimental** [comment]
It defeats the purpose to split it into two functions. I think we should add `@doc since: "1.12.0"` and override the missing doc since (probable v1.0.0).

**Comment by Eiji7** [comment]
@eksperimental Oh, I see. I would not be surprised if people (especially new in `Elixir`) would be confused asking: `"Why it's working on 1.10.4 when it's since is set to 1.12.0?"`. I'm a bit worried that some of them may open new issues thinking it's a bug/documentation fix report. What do you think?

**Comment by eksperimental** [comment]
> @eksperimental Oh, I see. I would not be surprised if people (especially new in `Elixir`) would be confused asking: `"Why it's working on 1.10.4 when it's since is set to 1.12.0?"`. I'm a bit worried that some of them may open new issues thinking it's a bug/documentation fix report. What do you think?

`List.last/2` won't be working on 1.10.4, it will be `List.last/1`, but the since attribute it for last/2

**Comment by Eiji7** [comment]
@eksperimental I know that `List.last/2` would not work … I mean that `List.last/1` would be working on `1.10.4` and new developer **may think** that it was **always** `List.last/2` (always with default argument). From such point `since` would be seen as invalid. Obviously we have a version switch in documentation - that's why I'm more than ok with your solution.

Just thinking if it would not be confusing for those new developers which does not need to check previous versions … Also switching to (one) previous version is not a big deal, but let's imagine that we have `>= 1.20.0` version and we need to take a look at multiple previous documentations to find that some function previously have less arguments and we still have no idea about its (old) `since`.

That's why if I would need to decide I would go with more clear way of having both `List.last/1` and `List.last/2`.

**Comment by eksperimental** [comment]
> @eksperimental I know that `List.last/2` would not work … I mean that `List.last/1` would be working on `1.10.4` and new developer **may think** that it was **always** `List.last/2` (always with default argument). From such point `since` would be seen as invalid. Obviously we have a version switch in documentation - that's why I'm more than ok with your solution.
> 
> Just thinking if it would not be confusing for those new developers which does not need to check previous versions … Also switching to (one) previous version is not a big deal, but let's imagine that we have `>= 1.20.0` version and we need to take a look at multiple previous documentations to find that some function previously have less arguments and we still have no idea about its (old) `since`.
> 
> That's why if I would need to decide I would go with more clear way of having both `List.last/1` and `List.last/2`.

@Eiji7 I have created a PR addressing this issue

**Pull request merged**
