### PR TITLE
Consider meta :file when fetching env location

### LINKED ISSUE #12659: Code.(compile/eval)_quoted drop file information in some cases
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:32:16] [ds:32:16:10] [async-threads:1] [jit:ns]

Elixir 1.16.0-dev (9041fca) (compiled with Erlang/OTP 25)

### Operating system

NixOS

### Current behavior

Given the following snippet:

```ex
# test.exs

src = """
defmodule Sample do
  @file "foo-bar.ex"
  @foo 1

  def bar do
    @foo
    :ok
  end
end
"""

ast = Code.string_to_quoted!(src)
Code.compile_quoted(ast)

src_nofile = """
defmodule Sample2 do
  @file "foo-bar.ex"

  defp a, do: 1
end
"""

ast = Code.string_to_quoted!(src_nofile)
Code.eval_quoted(ast)
```

Executing it with `elixir test.exs` gives the following output:
```
warning: module attribute @foo in code block has no effect as it is never returned (remove the attribute or assign it to _ to avoid warnings)
  foo-bar.ex:6: Sample.bar/0

warning: function a/0 is unused
  nofile:4: Sample2 (module)
```

Even though `Sample2` has a `@file` attribute, it seems to be dropped in evaluation, while in the `Sample` example not.

I've checked and this also happens in Elixir v1.14.2

### Expected behavior

Both cases should output the correct file

### PR DESCRIPTION
**Pull request by viniciusmuller**
This pull requests uses the message defined in `meta[:file]`, which was previously being ignored by `env_format`, resulting in "nofile" locations when evaluating code snippets, even with `@file` set.

I've also tried fix this by updating `store_definition` in `elixir_def.erl` but it ended up breaking kind changes errors, which apparently are always setting up `meta[:file]` with the file path they're contained in, even for snippets.

So I'm not sure if this is the best way to fix it, but I'm open to suggestions!

Closes #12659

### CODE REVIEW

**Comment by josevalim** [comment]
@viniciusmuller should we change `env_format` in `elixir_errors` instead to read from `meta[:file]` if there is no `meta[:keep]`?

**Comment by viniciusmuller** [comment]
That was my first approach, but it also ended up breaking the "kind change" errors, take a look at this:

The following test fails with this output:
```ex
  test "def defp clause change from another file" do
    assert_compile_error(["nofile:4\n", "def hello/0 already defined as defp"], ~c"""
    defmodule Kernel.ErrorsTest.DefDefmacroClauseChange do
      require Kernel.ErrorsTest
      defp hello, do: :world
      Kernel.ErrorsTest.hello()
    end
    """)
  end
```
```
  1) test def defp clause change from another file (Kernel.ErrorsTest)
     test/elixir/kernel/errors_test.exs:670
     Assertion with =~ failed
     code:  assert captured =~ message
     left:  "... def hello/0 already defined as defp in nofile:3\n  test/elixir/kernel/errors_test.exs:4\n\n"
     right: "nofile:4\n"
     stacktrace:
       (elixir 1.16.0-dev) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
       test/elixir/kernel/errors_test.exs:671: (test)
```

Iin this case, the filepath location is being assigned to `meta[:file]` even when it's a snippet and we don't use @file. So perhaps we need to fix this and then update this PR to fetch from meta[keep] in all cases.

**Comment by josevalim** [comment]
Actually, the more I look at about the code, I am not sure if it is a bug.

The @file annotation is meant to say from where the file contents come from - but not its definition. If you think about it, Phoenix templates have their contents in disk, but their definition still happens in a given place in a module.

**Comment by viniciusmuller** [comment]
> The @file annotation is meant to say from where the file contents come from - but not its definition. If you think about it, Phoenix templates have their contents in disk, but their definition still happens in a given place in a module.

But what do you think would be the correct output here, having the modules with `@file` that currently show it on the stacktrace also show `nofile`? I thought the main use case for the file attribute was to change this information, since it's what's on the `Module` docs

**Comment by josevalim** [comment]
Right, that's the point. `@file` changes the output for warnings inside the `def`. This warning comes from "outside". It has to point to where it is defined, and it is not defined inside `@file`.

Here is an example:

```elixir
src_nofile = """
defmodule Sample2 do
  @file "foo-bar.ex"

  defp a(b), do: :ok
end
"""

ast = Code.string_to_quoted!(src_nofile)
Code.eval_quoted(ast)
```

Notice how the unused variable warning is correct.

So perhaps the fix here is to improve the docs for `@file`?

**Comment by viniciusmuller** [comment]
I see, I think that for the end user this looks inconsistent, but makes sense logically, the moment I tried update the kind check code to display the defined module I've noticed that it was not really operating on the same "expression granularity" than the other cases.

I've currently bumped into this while writing tests for #12644, since a line-only snippet I was using was giving me the output and the compiler couldn't read the fixture file to print its line, but I guess since it's such a specific use case I'm better just evaluating an unused definition with `columns` disabled.

**Comment by josevalim** [comment]
Yeah, and we need to handle cases where we cannot read the line/file anyway. I will go ahead and close this one!

**Comment by viniciusmuller** [comment]
No problem! I'll open a PR updating the docs for `@file`

**Pull request closed without merging**
