### PR TITLE
Adding Code For Diagnostics To Windows Batch Files

### PR DESCRIPTION
**Pull request by OnorioCatenacci**
Adding a new test at the top of the Windows batch files to enable an end-user to easily see the output of the various Elixir batch files. This will make figuring out issues with the Win batch files a bit easier.

### CODE REVIEW

**Comment by OnorioCatenacci** [comment]
Sorry for all the noise Jose. :)

**Comment by Gazler** [comment]
@OnorioCatenacci for future reference, if you force push to a branch that has an open pull-request, the existing pull request is updated with the new commits.

Just referencing https://github.com/elixir-lang/elixir/pull/4028 and https://github.com/elixir-lang/elixir/pull/4027 for conversation purposes.

**Comment by OnorioCatenacci** [comment]
Thanks for that Gary.  I have to admit I thought I had a better handle on
using Git and Github than I actually seem to.  I didn't think squashing
commits would be all that difficult but apparently I was wrong.

On Tue, Dec 1, 2015 at 12:42 PM, Gary Rennie <notifications@github.com>
wrote:

> @OnorioCatenacci <https://github.com/OnorioCatenacci> for future
> reference, if you force push to a branch that has an open pull-request, the
> existing pull request is updated with the new commits.
>
> Just referencing #4028 <https://github.com/elixir-lang/elixir/pull/4028>
> and #4027 <https://github.com/elixir-lang/elixir/pull/4027> for
> conversation purposes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/pull/4029#issuecomment-161043995>.
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
