### PR TITLE
Test Suite Windows compatibility

### PR DESCRIPTION
**Pull request by xiamx**
Understandably development on Elixir language itself on Windows is less tested because of personal preferences and lack of support in Travis CI... I develop on Windows because I need to occasionally write some C#.

The current test suite does not pass in Windows. This pull request is aimed to address some issues in the test suite..

Please let me know if it's easier to put everything in one branch or separated for different fixes.

### CODE REVIEW

**Comment by josevalim** [comment]
Beautiful!

**Comment by josevalim** [comment]
Yes, we would love to have a green suite on Windows and others have done work towards it in the past but it is hard to keep it on a permanent green state exactly because we don't have a CI build. So contributions are really welcome!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by michalmuskala** [comment]
I saw several projects using https://www.appveyor.com/. Would it be an option to use it for elixir as well?

**Comment by robi-wan** [comment]
* They are free for open-source projects: https://www.appveyor.com/pricing/
* They support mingw, erlang (19.3) and git: https://www.appveyor.com/docs/build-environment/#pre-installed-software

**Comment by josevalim** [comment]
Can someone please send a pull request with the relevant files that need to be added to the repository so we get up running? The idea is that you can register your fork of Elixir and iron out the integration details and configuration files. Meanwhile I will setup the integration on this side until we get a PR. :)

**Comment by xiamx** [comment]
I have it started on my fork https://ci.appveyor.com/project/xiamx/elixir .. still trying to get it work. Will submit a PR when I'm ready

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
