### PR TITLE
Fix Git warning

### PR DESCRIPTION
**Pull request by eksperimental**
It was partially solved in 74855f052d6a0d8a015f1956426b0de27e3572c8

### CODE REVIEW

**Comment by eksperimental** [comment]
It is up to another PR whether we want to replace "master" with "main" or something else in the test files under `lib/mix/test`

```console
$ ag master lib/mix/test
lib/mix/test/test_helper.exs
228:System.cmd("git", ~w[config --global init.defaultBranch master])
247:    System.cmd("git", ~w[branch -d master])

lib/mix/test/mix/scm/git_test.exs
8:    assert Mix.SCM.Git.format_lock(lock(branch: "master")) == "abcdef0 (branch: master)"
17:    assert Mix.SCM.Git.equal?([git: "foo", branch: "master"], git: "foo", branch: "master")
18:    refute Mix.SCM.Git.equal?([git: "foo", branch: "master"], git: "foo", branch: "other")
49:      Mix.SCM.Git.accepts_options(nil, git: url, branch: "master", branch: "develop")
55:      Mix.SCM.Git.accepts_options(nil, git: "/repo", branch: "master", tag: "0.1.0")
59:      Mix.SCM.Git.accepts_options(nil, git: "/repo", branch: "master", branch: "develop")

lib/mix/test/mix/local/installer_test.exs
39:    args = ["git", "https://example.com/user/repo.git", "branch", "not_master"]
40:    opts = [branch: "not_master", git: "https://example.com/user/repo.git", submodules: nil]
46:    args = ["git", "https://example.com/user/repo.git", "ref", "not_master"]
47:    opts = [ref: "not_master", git: "https://example.com/user/repo.git", submodules: nil]
53:    args = ["git", "https://example.com/user/repo.git", "tag", "not_master"]
54:    opts = [tag: "not_master", git: "https://example.com/user/repo.git", submodules: nil]

lib/mix/test/mix/rebar_test.exs
104:      assert parse_dep({:git_rebar, '0.1..*', {:git, @git_rebar_charlist, :master}}) ==
105:               {:git_rebar, ~r"0.1..*", override: true, git: @git_rebar_string, ref: "master"}
107:      assert parse_dep({:git_rebar, {:git, @git_rebar_charlist, :master}}) ==
108:               {:git_rebar, ">= 0.0.0", override: true, git: @git_rebar_string, ref: "master"}
202:                 assert Enum.find(opts, &match?({:ref, "master"}, &1))

lib/mix/test/fixtures/rebar_dep/rebar.config.script
5:[{deps, [{git_rebar, "0.1..*", {git, filename:absname("../../test/fixtures/git_rebar"), master}}]}].
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by josevalim** [comment]
A PR that moved those to main would definitely be welcome!

**Comment by eksperimental** [comment]
> A PR that moved those to main would definitely be welcome!

I will work on it then

**Pull request merged**
