### PR TITLE
"mix --help" now is a shortcut for "mix help help"

### PR DESCRIPTION
**Pull request by eksperimental**
As discussed in https://github.com/elixir-lang/elixir/pull/5988#discussion_r111267224

### CODE REVIEW

**Comment by josevalim** [comment]
Sorry, my comment was not clear. What I said is that the result of `mix help help` is not useful as `mix --help` because it is not information about mix, it is information about how to customize the help task.

We could make `mix --help` show the same as `mix` right now but I am not convinced that should be the case.

Thank you!

**Comment by eksperimental** [comment]
Then my proposal is to have a standard `mix --help`  message as with the rest of the commands.

here's my initial draft:

```
$ mix --help
**Usage:**
  mix [task] [project_name]
      Invokes task.

  mix [options]
      Prints information about Mix such as this help message or version.

  elixir [elixir_options] -S mix [task] [project_name]
      Runs Mix via Elixir with Elixir options.

  iex -S mix [TASK]
      Starts IEx and runs the given task (or the default task "run" if none given).

**Options:**
  --help, -h                  Prints this message and exits
  --version, -v               Prints Mix version and exits

**Tasks:**
  For a list of available tasks run "mix help"

**Common commands:**
  mix                         Invokes the default task (current: "mix run")
  mix new PATH                Creates a new Elixir project at the given path
  mix help                    Lists all available tasks
  mix help TASK               Prints documentation for a given task
  iex -S mix                  Starts IEx and runs the default task
```

**Comment by josevalim** [comment]
We should not add yet another usage to maintain. Or it is either like `mix` or like `mix help`.

**Comment by eksperimental** [comment]
So I suggest to merge this suggestion in function that is called when you run `mix` in a dir with no mix.exs,
and make `mix --help`  call that
WDYT @josevalim?

**Pull request closed without merging**
