### PR TITLE
Add Port.stream!/2

### PR DESCRIPTION
**Pull request by lucidstack**
Hi there! 

This PR is to add `stream!/2` to the `Port` module, in order to create `Collectable` and `Enumerable` streams from Erlang ports. 🎉

A `Port.Server` GenServer is used internally, to have a single point of contact with the port. I initially tried opening and serving the stream from the calling process, but this made using ports' streams with `Experimental.Flow` impossible, as the consuming processes would be different from the one that initially opened the port. I couldn't come up with a better idea to avoid the additional GenServer, but obviously open to suggestions! 🙇 

As stated in the documentation, split lines are stitched together before going downstream (I found this particularly needed for things like CSV parsing), but this can be turned off by passing a third `raw` argument set to `true`, which makes the stream proxy all data messages from the port.

Hope this is something useful (and decently implemented!). 
Thank you very much in advance! 👋

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @lucidstack! I believe we don't need a separate server. Because all port messages have the port as first argument, you could write it using Stream.resource and select receives:

```elixir
receive do
  {^port, _, ...} ->
end
```

The trick is to make sure that you collect any left over message and close the port in the `after` callback of Stream.resource.

It is also important to note that `System.cmd` already provides a collectable implementation of system commands. Maybe we want to provide something like `into: :stream` there OR `stream_cmd`.

And lastly, keep in mind that you can't use an enumerable such as port stream as a source/producer in Flow because of conflicting mailbox messages. See GenStage.from_enumerable for more information. So if your goal is to use GenStage with ports, then it is better to create a Port specific stage.

Still this may make ports slightly more accessible so it is still worth discussing it.

**Comment by lucidstack** [comment]
Thank you for the thorough comment, @josevalim! I initially started the implementation without the server, by just having the `receive` blocks in the `Stream.resource/3` functions. 

After trying it out with `Flow`, I realised that the mailbox ownership was the problem, so I introduced the server. This is an example of how I'm using it at the moment:

```elixir
Port.stream!({:spawn_executable, @cmd}, [:binary, {:args, @args}, {:line, 65_536}])
|> CsvParser.parse_stream()
|> Flow.from_enumerable()
|> Flow.each(fn [id, iso] ->
  IO.puts("id #{id}")
  IO.puts("iso #{iso}")
end)
|> Flow.run()
```

This works fine because the server receives the messages from the port, and the various GenStage processes call the same server in `Stream.resource`'s `next_fun`. At the same time, I see how this adds complexity just to make the port streams work with `gen_stage`, and makes it somehow "special", which I'm not sure is a good thing. Thus, I'd be happy to strip it back to the `receive-in-stream-resource` solution, and get rid of the server.

I hadn't actually thought of adding the streaming functionality to `System.cmd/2`, but I suppose I went for `Port.stream!` to align the `Port` module to the `File` and `IO` ones. They both have stream-generating functions, and in the time of need, it felt kind of odd not to have one for ports.

At the same time, I noticed that `System.cmd` uses exactly a port with `:spawn_executable`, so we could very easily use `Port.stream!` itself, when `System.cmd` is invoked with the `into: :stream` option.

**Comment by josevalim** [comment]
> After trying it out with Flow, I realised that the mailbox ownership was the problem, so I introduced the server.

The problem now is that you are performing multiple copies and you no longer leverage back-pressure efficiently because it is hiding behind a pull interface! So I would really recommend implementing a stage that directly talks to the port. We can probably start by implementing it as a producer. What do you think?

> I suppose I went for Port.stream! to align the Port module to the File and IO ones.

That's a good point! Although it makes me realize that File and IO are pull implementations and I am not sure we want the same for Ports.

**Comment by lucidstack** [comment]
> So I would really recommend implementing a stage that directly talks to the port. We can probably start by implementing it as a producer.

That sounds great! You mean to add the stage directly into Elixir, or in user space? Sorry for the confusion, I couldn't find any other reference to gen_state in PR's or issues here, so I don't know what your stance is on this. 😀 

Meanwhile, shall we keep the simple `receive` implementation for the non-gen_stage-compatible stream? I see your concerns with the pull mechanism, that doesn't really match the pushy nature of ports. On the other hand, users follow the same path without stream anyway, by opening the port, listening to its messages, and closing it; `Port.stream!` would just make this process more straight-forward. Perhaps, a pull implementation is not perfect for ports, but it's the best we can afford, while still being useful to the user.

Saying that, port streams might not be valuable enough to compensate for their "pull" tradeoff… I'll leave this to you, and your immensely greater wisdom! 😄

**Comment by josevalim** [comment]
> That sounds great! You mean to add the stage directly into Elixir, or in user space?

I think right now you should implement it for your project and if you would like to share your implementation, I would love to discuss it. Then we can discuss about adding it as part of the GenStage project.

**Comment by josevalim** [comment]
About Port.stream, I need to think more about it, but I cannot do it right now. I will ping back. :)

**Comment by josevalim** [comment]
After further thought I have decided to close this PR exactly because using the Port as a stream may lead to the direction of inefficiencies or incompatibilities discussed above. Matching on the data coming from a port is relatively straight-forward, so we should promote that instead.

Thank you @lucidstack!

**Pull request closed without merging**
