### PR TITLE
add backticks to a massive amount of true, false and nil

### PR DESCRIPTION
**Pull request by eksperimental**
I have added backticks to `true`, `false` and `nil`, 
using the following regular expressions to detect them.

```bash
ag -i "\W(is|are|was|were|to|or|and|nor|when|returns?|defaults?|otherwise|\.)\s+(true|false|nil)" -l
```

if some more patterns can be added, please let me know.

### CODE REVIEW

**Comment by josevalim** [comment]
@eksperimental thank you! There is an issue though, you have added backticks to a bunch of comments and strings. Maybe you could check that everything until the word "true|false|nil" did not contain one of ", #, %?

**Comment by eksperimental** [comment]
Well, I haven't let a backtick open until the next line... If it's takes two lines, it's because I forgot to close it. Where is the file that this is happening?

CI build failed, but only one out of the 6 builds and i tested it locally with no issues,...

**Comment by eksperimental** [comment]
@josevalim well, the backticks inside the string, was on purpose, but it passes all the test, but I don't know if you prefer not to have them. I chose to use them because it denotes it's a special word/value, not just another word in the sentence.
just tell me whichever you think suits best.

**Comment by josevalim** [comment]
Yeah, I don't think we should add them to strings and code comments. They don't have markdown syntax in them.

**Comment by eksperimental** [comment]
all good, i have fixed that.
just for the record, the new command is:
```bash
ag '^(?-m)[^\"\%\#\n]*\W(?m)(is|are|was|were|to|or|and|nor|when|returns?|defaults?|otherwise|\.)\s+(?-i)(true|false|nil)\W(?-m)'
```

let me know if any other change is needed.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
