### PR TITLE
Use iex> prompt in IEx.Helpers examples

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
:+1: although we should remove `#=>` from the results then.

**Comment by eksperimental** [comment]
@josevalim you mean these ones?
https://github.com/elixir-lang/elixir/pull/5380/files#diff-c9f16866d68f0de207ec9d1fafbdabcbR264

i have done those so it doesn't break when we types change in Enum. but I guess we can deal with that (i remember having to deal with something like this previously but it was more difficult to solve, as it was listing the first function for a module)

or you mean others "#=>" ??

**Comment by josevalim** [comment]
I mean all of them. If we are adding `iex>` because we want to make it look like their shell, then we should also remove `#=>`.

**Comment by eksperimental** [comment]
@josevalim Sorry, i thought the `#=>` because it would break the doctest, but i realize doctests for this module are disabled.

Fixed. let me know what you think

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
