### PR TITLE
Change release default mode to interactive

### LINKED ISSUE #9337: Starting releases is slow
### Environment

- elixir 1.9.1-otp-21
- OS: Linux (ubuntu and archlinux)

### Current behavior

Starting an application build with the build in `mix release` from `elixir 1.9.1` is way slower than starting the same application build with `distillery`.

Unfortunately, I don't have a public test case, but I did create some measurements. Every time I measured the time to entry in `Application.start`:

```
## Distillery (elixir 1.8.2-otp-21)
- date && _build/prod/rel/app/bin/app foreground: < 3 seconds
- date && _build/prod/rel/app/bin/app console: < 3 seconds

## Distillery (elixir 1.9.1-otp-21)
- date && _build/prod/rel/app/bin/app foreground: < 3 seconds
- date && _build/prod/rel/app/bin/app console: < 3 seconds

## Elixir releases (elixir 1.9.1-otp-21)
- date && _build/prod/rel/app/bin/app start: 10 seconds
- date && _build/prod/rel/app/bin/app start_iex: 10 seconds

## env MIX_ENV=prod mix phx.server --preload-modules (elixir 1.9.1-otp-21)
- date && env MIX_ENV=prod mix phx.server --preload-modules: < 3 seconds

## Experiment: Elixir releases without runtime configuration (elixir 1.9.1-otp-21)
- date && _build/prod/rel/app/bin/app start: < 3 seconds
```

As you can see, using regular releases with runtime configuration are way slower than distillery. I have the feeling that even without runtime configuration they are still slower, but that's hard to measure. There is a post on elixirforum where others are reporting the same issue (https://elixirforum.com/t/elixir-1-9-release-slow-boot-time/) and pointing out that not including runtime configuration did not fix this for them (although it improved a bit)

Having about 10 seconds for a fairly simple application to before it starts is a huge overhead. It would be nice if we had similar startup performance as with `distillery`.

### PR DESCRIPTION
**Pull request by gordalina**
Closes #9337.
Helps #9603.

### CODE REVIEW

**Comment by gordalina** [comment]
Sounds good, I'll update the PR.

Is there a better way to check the OTP version other than calling ```elixir --eval "IO.puts(System.otp_release())"``` from the boot script?

**Comment by josevalim** [comment]
@gordalina oh, instead of checking the version on the boot script itself, check it when generating the boot file. Something like:

```eex
-mode <%= maybe_interactive(@release, "$RELEASE_MODE") %>
```

where

```elixir
defp maybe_interactice(release, other) do
  if ...otp >= 23 and Keyword.get(release.options, :reboot_system_after_config, true) do
    "interactive"
  else
    other
  end
end
```

**Comment by gordalina** [comment]
@josevalim Wouldn't that check the OTP version at release time rather than runtime? Or am I missing something here?

**Comment by josevalim** [comment]
It is at release time but the release includes the OTP version inside itself anyway. :)

**Comment by gordalina** [comment]
That makes sense! I'll update the PR.

**Comment by josevalim** [comment]
@gordalina absolutely beautiful. Just one test failure and we should be good to go!

**Comment by gordalina** [comment]
@josevalim this is ready for review. I've squashed the commits.

**Pull request merged**
