### PR TITLE
Loading umbrella project apps optional deps

### LINKED ISSUE #6333: Unexpected mix deps :optional behavior
### Current behavior

I have an application, A, that depends on an application that is configured in A's `config.exs`.

```elixir
  defp deps do
    [
      {:some_dependency, "~> 1.0.0", optional: true},
    ]
  end
```

I created a new application, B, that depends on application A. B does not need the dependency that's configured in A's `config.exs`. Therefore in A's `config.exs` it's marked as `optional: true`. This works great for application B.

The problem is that when I run application A, I get warnings logged that look like:

```
You have configured application :some_dependency in your configuration
file, but the application is not available.

This usually means one of:

1. You have not added the application as a dependency in a mix.exs file.

2. You are configuring an application that does not really exist.

Please ensure :some_dependency exists or remove the configuration.
```

I'm surprised by this behavior given my understanding of the `:optional` setting:

> In such cases, the current project will always include the optional dependency but any other project that depends on the current project won’t be forced to use the optional dependency

I would expect that since "...the current project will always include the optional dependency..." not to see the lines:

> You have not added the application as a dependency in a mix.exs file.

or

> You are configuring an application that does not really exist.

I'm trying to figure out what I don't understand about `:optional`'s behavior.

### Environment

* Elixir: 1.4.5
* Erlang/OTP: 20

### PR DESCRIPTION
**Pull request by kelvinst**
Fixes #6333

### CODE REVIEW

**Comment by kelvinst** [comment]
@josevalim in #6333 mentioned the error is because we end-up pruning the optional dependencies for umbrella apps. This is a try to fix the issue by not pruning it.

I've created [this app](https://github.com/kelvinst/umbrella_test) to test it, then ran on top of my own compiled `mix`:

```
git clone https://github.com/kelvinst/umbrella_test
cd umbrella_test/apps/test_a
~/Code/open-source/elixir/bin/mix compile
cd ../..
~/Code/open-source/elixir/bin/iex -S ~/Code/open-source/elixir/bin/mix
```

And still got the message "You have configured application :sentry in your configuration..."

I've checked the `_build` dir and the dependencies were **not** pruned at all, which means my code worked. So I guess the only option is to load the optional deps of all umbrella apps, is it right? Any other idea?

**Comment by ericmj** [comment]
I think this needs fix needs to be in the converger where we reject optional dependencies. The optional dependencies have already been removed when we reach the deps.loadpaths task.

**Comment by kelvinst** [comment]
@ericmj by removed you mean from the deps list to start the app right? Will do it!

My only doubt is: we leave this change or rollback it?

**Comment by ericmj** [comment]
They have been removed the deps list, correct. Or rather they are never loaded by mix because the converger filters the optionals away, we should skip this filtering if the optional dependency is a dependency of an umbrella child app.

I don't think we need the changes you have made so far, but please keep this PR open if do further changes.

**Comment by kelvinst** [comment]
@ericmj, now the converger is loading the deps list correctly. I've manually tested here and it's all good!

I've also checked if we really need to not prune the dependencies for umbrella-apps and we don't. What do you think? Let's remove the first commit? Any reason to leave it?

**Comment by kelvinst** [comment]
I'm now making a test scenario for umbrella apps optional deps.

**Comment by kelvinst** [comment]
Test added! I've ran it on master and it correctly fails there, so this PR is ready for reviewing! 😀

**Comment by ericmj** [comment]
@kelvinst Looks great! We should remove the first commit and only leave the converger changes.

**Comment by kelvinst** [comment]
Sure! Doing it now!

**Comment by kelvinst** [comment]
Done!

**Comment by josevalim** [comment]
@ericmj I am a bit on the fence about this one because when using path dependencies from sibling A to sibling B the optional dependencies won't be loaded as well. Although I assume this behaviour is expected because those are actual projects while the umbrella is a "meta" one which therefore should not impact optional deps?

**Comment by ericmj** [comment]
@kelvinst Me and @josevalim discussed this and we decided that this is the behaviour we want. I approved the PR but we will wait for one more approval before merging.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
