### PR TITLE
Standardize use of function captures by using parenthesis

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by whatyouhide** [comment]
This is another change I am very much in favour of in terms of increased code quality/readability, but not sure about because it touches a lot of stuff just for style. :/

**Comment by josevalim** [comment]
This is a change that I am not in favor because I personally love to use & without parenthesis. If we are going to normalize all styles then we might as well remove optional parentheses (which won't happen). :)

Thanks @eksperimental for the PR but merging this would be make me extremely sad.

**Comment by eksperimental** [comment]
Fair enough, but be aware that I had to use in IEx `quote do: ... |> Macro.to_string` to understand what was really going on where I have to put the parenthesis in this commit in a few instances, 
such as 
- https://github.com/elixir-lang/elixir/pull/4989/files#diff-59dfea30c24e10aaa6d3e55047e926d6L270
- https://github.com/elixir-lang/elixir/pull/4989/files#diff-0ed5c47cc55f463c3af34af96d1fef62L139
- https://github.com/elixir-lang/elixir/pull/4989/files#diff-90e7c8e0c527fa9baedd5cc343e197f9L91

You may want to change those in particular, if not replacing them all.

**Comment by josevalim** [comment]
Great, now you know that & has really low precedence. :) We should add
parentheses if they are used in the documentation. Other than that, it is
totally fine.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Pull request closed without merging**
