### PR TITLE
Maintain an order in Calendar elements

### PR DESCRIPTION
**Pull request by eksperimental**
Order is:
  calendar,
  year, month, day, hour, minute, second, microsecond,
  std_offset, utc_offset, time_zone, zone_abbr

### CODE REVIEW

**Comment by eksperimental** [comment]
the changes in the types order is debatable though. But if we are going to keep an order, it may make sense

**Comment by josevalim** [comment]
Yes, I don't think we need to keep an order and I would like to avoid changes to the source that are stylistics for reasons you are familiar with. :) Thank you! :heart:

**Comment by eksperimental** [comment]
I would not consider stylistic setting an order in structs with 12 different elements.
It's about making developers's life easier when you read this code and avoid missing elements that could lead to bugs.

**Comment by josevalim** [comment]
@eksperimental that's why Elixir introduced a `@enforce_keys` option on structs, so the compiler yells at you if you forget a required key. :)

**Comment by eksperimental** [comment]
that's true.
still a mess tough! hahah :-P

**Pull request closed without merging**
