### PR TITLE
Adding tee/2 function to Kernel

### PR DESCRIPTION
**Pull request by kelvinst**
This is a basic implementation of what @josevalim suggested on https://groups.google.com/d/msgid/elixir-lang-core/CAGnRm4Ji7kAjv5i4_04AVp-hae4ghj1DgZx1zr%2B4LyGBYpj5_A%40mail.gmail.com?utm_medium=email&utm_source=footer

PS: Didn't dog food it yet because I don't if this is going to be the final place for it (or even if it would be accepted). Once decided, we can think some places to use it on elixir core.

### CODE REVIEW

**Comment by devonestes** [comment]
This looks like a really useful function!

However, am I alone in having no idea why it has the name “tee”? Is there some computer science thing I’m missing that would make this name relevant?

**Comment by fxn** [comment]
What about removing “unchanged”? It returns “the subject” (or the first argument).

**Comment by fertapric** [comment]
> However, am I alone in having no idea why it has the name “tee”? Is there some computer science thing I’m missing that would make this name relevant?

@devonestes I think it's named after the ["T" piece used in plumbing](https://en.wikipedia.org/wiki/Piping_and_plumbing_fitting#Tee).

**Comment by josevalim** [comment]
The name comes from here: https://en.wikipedia.org/wiki/Tee_(command)

Since it is useful mostly inside pipelines, it probably makes sense to borrow the name from Unix pipes too.

**Comment by josevalim** [comment]
> PS: Didn't dog food it yet because I don't if this is going to be the final place for it (or even if it would be accepted). Once decided, we can think some places to use it on elixir core.

The truth is I am not sure we would find places to use it in Elixir. This function is useful only during debugging or during side-effects. But if you are doing side-effects there is nothing stopping you from having a private function that does the job. If we take your example:

    ["thing1", "thing2"]
    |> generate_more_things()
    |> tee(&File.write!("things", &1))
    |> do_something_with_things()

I would write it as:

    ["thing1", "thing2"]
    |> generate_more_things()
    |> write_it_to_disk()
    |> do_something_with_things()

And to me that is clearer than a `tee`. So my concern is that by having those functions, we are encouraging people to write "sloppy pipelines".

In fact, I planned not long ago to send a proposal to elixir-core about adding two functions to Kernel, `tee`, which we discuss here, and `pipe`, which simply pipes the first argument to an anonymous function. So you could do:

    ["thing1", "thing2"]
    |> pipe(&generate_more_things("foo", &1))
    |> tee(&File.write!("things", &1))
    |> do_something_with_things()

And you probably see my point here. To me none of those replace writing proper private functions. I eventually gave up on writing the proposal but I supposed @kelvinst could create a project called `:pipe_tee` or `:plumbing` with those additions.

**Comment by kelvinst** [comment]
Just realised my comparison is kind of unfair. Here is a fairer version with private functions:

```elixir
["thing1", "thing2"]
|> add_first_thing()
|> write_things_to_disk()
|> capitalize_things()
```

**Comment by mememori** [comment]
I agree with @kelvinst and with @josevalim.

Albeit it might be an incentive for "sloppy pipelines", `tee` is great for debugging, scripts and simple side-effectful pipelines. I could see a lot of uses for `tee` to make the project i am currently working on a bit more readable on some bits.

So, i'd say it would be a good addition. LGTM

**Comment by josevalim** [comment]
> I could see a lot of uses for tee to make the project i am currently working on a bit more readable on some bits.

That's a direction we can take. If users can post actual examples of pipelines before and after `tee`, it can really help the discussion move forward.

**Comment by OvermindDL1** [comment]
> That's a direction we can take. If users can post actual examples of pipelines before and after tee, it can really help the discussion move forward.

For documentative purposes, the original use-case was:

```elixir
blah
|> do_something0()
|> tee(&IO.inspect(&1.vwoop))
|> do_something1()
```

**Comment by yordis** [comment]
@josevalim I dont know if this would make sense but

I would use this with some async logger that I wouldn't care about the return value or any computation inside maybe?

```
data
|> do_something()
|> tee(&Logger.log(&1))
|> keep_going()
```

**Comment by josevalim** [comment]
I understand there is a benefit in theory, but it is unclear if it would
actually be relevant or make the code better in practice. That’s why we are
asking for actual code samples. I am sure it makes pseudo code look fine. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Folks, since we haven't had actual code samples posted here, I will go ahead and close this. My suggestion is to move this discussion to a medium with more visibility, probably Elixir Forum, and see the use cases that pop out. Thanks!

**Comment by josevalim** [comment]
Meanwhile, if someone wants to go ahead and create a project with the `tee/2` and `pipe/2` functions as I mentioned above, that's even better.

**Comment by kelvinst** [comment]
> Meanwhile, if someone wants to go ahead and create a project with the tee/2 and pipe/2 functions as I mentioned above, that's even better.

Did it! https://hexdocs.pm/plumbing/

**Comment by yordis** [comment]
@josevalim a couple of days after, I am in a position that I don't want to use @kelvinst package, not because it doesn't do what I need but because it will be another dependency to manage, so basically I will be copying this over to my package, so so far, the 3rd package on Hex that I know hat will include the exact same code.

To be honest,

I see the pattern of `|> tap( &log_error/1)` every where in my code because I combine it with other pipes so my code becomes cleaner.

The more piped style people use, the common the pattern of use `tap/tee` for logger is.


```elixir
some_value
|> My.business_do_something()
|> StrawHat.Response.tap_error(&log_error/1) # <-- this uses `tap/tee` under the hood
|> StrawHat.Response.tap(fn _ -> "my business did something" end) # <-- this uses `tap/tee` under the hood
```

I hope this actually gets into Elixir one day Jose, I really dont mind to copy over to the packages but so far has become part of my daily stack to use `tee` function.

**Pull request closed without merging**
