### PR TITLE
Add details about waiting modules in `--profile time` compiler output

### PR DESCRIPTION
**Pull request by GregMefford**
# Context
When running `mix compile --profile time`, we currently get output about how long each file took to compile, and how long it spent waiting for other compile-time dependencies to be available, but it doesn't say what those module are.

# Existing Solutions
We can, for example, use `mix xref trace` and `mix xref graph` to determine what those dependencies are, but it isn't easy to analyze which ones will actually have an impact in practice on the compile times of the dependent modules.

# New Feature
This PR adds more detail to the `--profile time` option of the Elixir compiler, so that it also lists how long each module spent waiting for each dependency to become available.

# Alternatives Considered
I also looked into leaving the output the same unless the user also passes the `--verbose` option, but the problem is that it then outputs the file name twice (once for the `--verbose` option and once for the `--profile` option) and I felt like that was messy. Let me know if you'd prefer to split this into a separate `--profile` option value like `time-details`, to preserve the existing behavior, instead.

# Future Work
I was also looking into how I can add this to the Compiler Tracing feature, but it was trivial to add to the existing profiling code this way, and I have not figured out the right place to inject the appropriate tracing events yet, but I will continue to work on that and open a separate PR.

# Example
As an example, I ran it against the Phoenix codebase:

## Before
```
...
[profile]    147ms compiling +      0ms waiting for lib/phoenix/router/scope.ex
[profile]     58ms compiling +      0ms waiting for lib/phoenix/socket/pool_supervisor.ex
[profile]    318ms compiling +      0ms waiting for lib/phoenix/router.ex
[profile]     47ms compiling +      0ms waiting for lib/phoenix/socket/serializer.ex
[profile]     68ms compiling +      0ms waiting for lib/phoenix/token.ex
[profile]    188ms compiling +      0ms waiting for lib/phoenix/socket/message.ex
[profile]    428ms compiling +      0ms waiting for lib/phoenix/param.ex
[profile]    114ms compiling +    526ms waiting for lib/phoenix/channel.ex
[profile]     83ms compiling +     81ms waiting for lib/phoenix/socket/serializers/v1_json_serializer.ex
[profile]    115ms compiling +      0ms waiting for lib/phoenix/transports/long_poll.ex
[profile]    157ms compiling +      0ms waiting for lib/phoenix/socket/transport.ex
[profile]    119ms compiling +     75ms waiting for lib/phoenix/socket/serializers/v2_json_serializer.ex
[profile]     42ms compiling +      0ms waiting for lib/phoenix/transports/websocket.ex
[profile]    198ms compiling +      0ms waiting for lib/phoenix/test/conn_test.ex
[profile]    286ms compiling +     42ms waiting for lib/phoenix/socket.ex
[profile]     96ms compiling +      0ms waiting for lib/phoenix/transports/long_poll_server.ex
[profile]    210ms compiling +    576ms waiting for lib/phoenix/channel/server.ex
[profile]    273ms compiling +      0ms waiting for lib/phoenix/test/channel_test.ex
[profile]    167ms compiling +      0ms waiting for lib/phoenix/verified_routes.ex
[profile] Finished compilation cycle of 87 modules in 1244ms
[profile] Finished group pass check of 87 modules in 106ms
Generated phoenix app
```

## After
```
...
[profile]    149ms compiling +      0ms total waiting for lib/phoenix/router/scope.ex
[profile]    332ms compiling +      0ms total waiting for lib/phoenix/router.ex
[profile]     50ms compiling +      0ms total waiting for lib/phoenix/socket/serializer.ex
[profile]    147ms compiling +      0ms total waiting for lib/phoenix/socket/message.ex
[profile]    391ms compiling +      0ms total waiting for lib/phoenix/param.ex
[profile]     77ms compiling +     11ms total waiting for lib/phoenix/socket/serializers/v1_json_serializer.ex
[profile]                    |     11ms waiting for Phoenix.Socket.Serializer
[profile]    132ms compiling +    490ms total waiting for lib/phoenix/channel.ex
[profile]                    |    490ms waiting for Phoenix.Socket
[profile]    119ms compiling +      0ms total waiting for lib/phoenix/socket/serializers/v2_json_serializer.ex
[profile]     70ms compiling +      0ms total waiting for lib/phoenix/token.ex
[profile]    151ms compiling +      0ms total waiting for lib/phoenix/socket/transport.ex
[profile]     90ms compiling +      0ms total waiting for lib/phoenix/transports/long_poll.ex
[profile]    287ms compiling +     12ms total waiting for lib/phoenix/socket.ex
[profile]                    |     12ms waiting for Phoenix.Socket.Broadcast
[profile]     42ms compiling +      0ms total waiting for lib/phoenix/transports/websocket.ex
[profile]    226ms compiling +    508ms total waiting for lib/phoenix/channel/server.ex
[profile]                    |    334ms waiting for Phoenix.Socket.Broadcast
[profile]                    |    174ms waiting for Phoenix.Endpoint
[profile]     94ms compiling +      0ms total waiting for lib/phoenix/transports/long_poll_server.ex
[profile]    197ms compiling +      0ms total waiting for lib/phoenix/test/channel_test.ex
[profile]    197ms compiling +      0ms total waiting for lib/phoenix/test/conn_test.ex
[profile]    152ms compiling +      0ms total waiting for lib/phoenix/verified_routes.ex
[profile] Finished compilation cycle of 87 modules in 1260ms
[profile] Finished group pass check of 87 modules in 104ms
Generated phoenix app
```

### CODE REVIEW

**Comment by josevalim** [comment]
HI @GregMefford! The feature looks good to me but I would like to bikeshed on the format. What do you think about:

```
[profile]    226ms compiling +    508ms total waiting for lib/phoenix/channel/server.ex (Phoenix.Socket.Broadcast, Phoenix.Endpoint)
```

I don't think the time waiting on each module itself is useful but rather only the modules themselves. WDYT?

**Comment by GregMefford** [comment]
One reason to have each module be listed on its own line is that, in a real-life codebase, the module names can get quite long (since they wouldn’t be aliased at all in this case), and there could also be a lot of modules in the list of modules causing the wait time. So I think it’s going to be a lot easier to visually scan or programmatically parse and count repeated occurrences if they’re each listed on their own line.

if they’re on their own line, I feel like there’s no reason not to also show the wait time per module, even if it’s probably not indicating a problem, because it does provide some accounting information, showing how the total breaks down by module. I think the per-module waiting time is probably as valuable as the overall waiting time (neither really indicates a problem, but is useful to understand the details of what’s going on).

If you don’t want to lose the single-line-per-file output option, we could think about whether another option makes sense.

**Comment by josevalim** [comment]
I see. The current output was designed so we can easily select a "column" and paste it on a spreadsheet. But now we are mixing the meaning. WDYT about this:

```
[profile]    226ms compiling +    334ms waiting for struct Phoenix.Socket.Broadcast (lib/phoenix/channel/server.ex)
[profile]                    |    174ms waiting for module Phoenix.Endpoint  (lib/phoenix/endpoint.ex)
```

**Comment by GregMefford** [comment]
I think this last proposal isn't as clear which thing is being compiled and which thing is being waited for. Maybe something like this is more clear? If you just wanted the compile times, you could pipe through `grep -v +` to remove all the ones with a `+` in them. Also, now each line has meaning by itself because it "reminds" you which file was being compiled for each awaited module.

```
[profile]      226ms compiling lib/phoenix/channel/server.ex
[profile] +    334ms waiting for struct Phoenix.Socket.Broadcast while compiling lib/phoenix/channel/server.ex
[profile] +    174ms waiting for module Phoenix.Endpoint while compiling lib/phoenix/channel/server.ex
```

**Comment by GregMefford** [comment]
Also I'm not sure it would ever say `module` or `struct`, would it? I think in the code, it is just the variable `on` that comes back in the message to notify when the module has been loaded after it was being waited for. It would probably be possible to keep track of whether it was a module or a struct that was being waited for, though.

**Comment by josevalim** [comment]
I want to keep the same times vertically aligned, instead of mixing them.

Regarding struct/module, when you wait on something, there is a kind, which is either module or struct so far.

**Comment by GregMefford** [comment]
Ok, thanks for clarifying!

I have pushed some new code with the following:
* Keep compiling time and waiting time in separate "columns"
* Removed the total waiting time per file so that it's not confused with the per-item waiting times that would be in the same column
* If there is only one thing being waited-for, keep it in the original line with the `compiling` time
* If there are more than one, break out to additional lines with a `|` instead of a `+`.

The actual output look like this while compiling Phoenix:

```
...
[profile]    351ms compiling +     51ms waiting for struct Phoenix.Socket.Broadcast while compiling lib/phoenix/socket.ex
[profile]     81ms compiling +      0ms waiting while compiling lib/phoenix/transports/websocket.ex
[profile]    119ms compiling +      0ms waiting while compiling lib/phoenix/transports/long_poll_server.ex
[profile]    295ms compiling +    556ms waiting for struct Phoenix.Socket.Broadcast while compiling lib/phoenix/channel/server.ex
[profile]                    |    202ms waiting for module Phoenix.Endpoint while compiling lib/phoenix/channel/server.ex
[profile]    335ms compiling +      0ms waiting while compiling lib/phoenix/test/channel_test.ex
[profile]    213ms compiling +      0ms waiting while compiling lib/phoenix/verified_routes.ex
```

I was going to add some more detailed regexes to test that the output is correct, but then realize that, since the `ParallelCompiler` is hard-coded to run in parallel based on the number of schedulers, it's difficult to ensure that things will be deterministically waited-on in the tests. If you have ideas about how to get around that, I'd be happy to add some more tests. For now, I figured that a little manual testing should be sufficient to make sure it's working, and a regression is unlikely unless someone changes this specific code on purpose.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
