### PR TITLE
coma is not an operator

### PR DESCRIPTION
**Pull request by dams**
Or is it ?

### CODE REVIEW

**Comment by AndrewDryga** [comment]
It's clear that comma is not an operator in there, along with other table rows not having a comma - looks like this is a typo 👍.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by dams** [comment]
Fun Fact: in Perl, the coma is an operator :P

**Comment by OvermindDL1** [comment]
> Fun Fact: in Perl, the coma is an operator :P

More fun facts:  The comma is an operator in OCaml too, `a,b` makes a 2-tuple, a `a,b,c` makes a 3-tuple, etc.... etc...  ^.^

**Pull request merged**
