### PR TITLE
Add report for "normal" exits in IEx

### PR DESCRIPTION
**Pull request by tywhisky**
Issue: #13745

I think rather than delete the `abnormal_reason?/1` directly, add the report with distinct color is better.

### CODE REVIEW

**Comment by josevalim** [comment]
@tywhisky please just remove the condition. I think we can treat all exists the same. Thank you!

**Comment by tywhisky** [comment]
> @tywhisky please just remove the condition. I think we can treat all exits the same. Thank you! Also, if you could add a test, it would be great!

I noticed that the behavior of :normal and :shutdown/{:shutdown, _} is inconsistent, do I need to make the :normal report as well?

> :normal returns the PID and then :ok

**Comment by josevalim** [comment]
Removing the conditional should be enough to make everything behave consistently. No more special cases for normal or shutdown. :)

**Comment by tywhisky** [comment]
Done. If there's still some problem please tell me.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
