### PR TITLE
Precompiled zip files to include man pages

### PR DESCRIPTION
**Pull request by eksperimental**
Original PR: https://github.com/elixir-lang/elixir/pull/3477/

I have removed the Makefiles and also added a gitignore rule to exclude the precompiled zip file.
the second commits cleans the `man` dir after it has been built, since there is no need to keep those files there. I think we should also remove `/man/elixir.1` and `/man/iex.1` from `.gitignore` but I don't know when we should do that.

### CODE REVIEW

**Comment by eksperimental** [comment]
One question, in `RELEASE.md` it states:
> Release new zip with `make release_zip`, push `Precompiled.zip` to GitHub Releases
But I cannot see the code that is pushing it to github
I knot there is an API for such a task, https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by eksperimental** [comment]
another question, is it worth to have a second make file with just 2 commands, in a separa makefile under `man/Makefile`
I think it could be easily moved to the `/Makefile`, unless there is a reason I'm ignoring.

**Comment by josevalim** [comment]
The push to github is manual. And yes, we could merge the makefiles.

**Comment by eksperimental** [comment]
makefiles merged,

/cc @eugulixes

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
