### PR TITLE
Introduce clean_erlang Make target

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
Is there any use case for this addition?
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D

**Comment by josevalim** [comment]
I will close this as deleting only the Erlang files does not have much purpose. We only have clean_elixir for core developers to test rebootstrapping the language. Make Erlang on the other hand is always fine without cleaning it before.

**Comment by eksperimental** [comment]
> I will close this as deleting only the Erlang files does not have much purpose. We only have clean_elixir for core developers to test rebootstrapping the language. Make Erlang on the other hand is always fine without cleaning it before.

I dind't know it was only for that purpose.
Why don't we just delete `Elixir.Kernel.beam` if that's the case then? (unless there are other cases)

**Comment by eksperimental** [comment]
> I will close this as deleting only the Erlang files does not have much purpose. We only have clean_elixir for core developers to test rebootstrapping the language. Make Erlang on the other hand is always fine without cleaning it before.

I thought eventually when working on the erlang files, you may need to clean everything to be recompiled, but I see what you mean.

**Pull request closed without merging**
