### PR TITLE
Raise on incomplete doctests that don't finish on a trailing new line

### PR DESCRIPTION
**Pull request by eksperimental**
As discussed in the mailing list.
this is a WIP, since I need to update the line numbers in the test, therefore the `@tag :skip`, but first need to be approved

### CODE REVIEW

**Comment by eksperimental** [comment]
I'm holding this until a second approval is given

**Comment by eksperimental** [comment]
Ready to merge

**Comment by eksperimental** [comment]
Ready to merge

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
@josevalim please give me a heads  up on the other PR I sent the mailing list

**Pull request merged**
