### PR TITLE
Dict.get_and_update/3 and Keyword.get_and_update/3

### PR DESCRIPTION
**Pull request by whatyouhide**
As discussed in #2973, I implemented `Dict.get_and_update/3` and `Keyword.get_and_update/3`. They both work like `Access.get_and_update/3`, but they'll replace the `Access` counterpart once the `Access` protocol will be deprecated.

I'm looking forward to a review!

### CODE REVIEW

**Comment by josevalim** [comment]
Excellent! We should probably add this custom implementation for keywords and maps:

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/access.ex#L60-L76
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/access.ex#L87-L96

I remember optimizing them all at the time. :)

**Comment by josevalim** [comment]
@msch this is my dilemma with your proposed update function. We are adding `get_and_update/3` to Dict because the Access protocol is being deprecated and this function is called even if there is no value. So, in my mind, it doesn't make sense to have an `update/3` function that is only called if it exists. Does it make sense?

**Comment by whatyouhide** [comment]
@josevalim pushed those implementations for `Map` and `Keyword` in 4029f3d.

**PS** Is there a reason beacause Erlang's `:maps` is used so frequently in `Keyword` and `Map`? Like, is it performance or they were just written in different times :smile:?

**Comment by josevalim** [comment]
> PS Is there a reason beacause Erlang's :maps is used so frequently in Keyword and Map? Like, is it performance or they were just written in different times :smile:?

Wait, `:maps` are used only in Map but we do use `:lists` in Keyword because those are the basic functions we build on top of. :D But we often prefer to provide an specific implementation instead of using the default ones from Dict exactly because of performance.

**Comment by josevalim** [comment]
This looks great. I will wait for some feedback and then merge this! Thank you!

**Comment by whatyouhide** [comment]
Ok, great. :smile: Thank you!

**Comment by MSch** [comment]
@josevalim I see where you are coming from, and I agree the naming is not optimal, but if the only problem is the name then I think having the functionality available under a different name still makes sense.

What about adding `fetch_and_update` that returns a tuple `{{:ok, value}, dict_with_updated_value}` or `{:error, original_dict}`, similar to how `fetch` returns `{:ok, value}` or `:error`?

In my code I've usually called the function `maybe_update(dict, key, fun)` but that name is clearly not optimal.

**Comment by josevalim** [comment]
>  I think having the functionality available under a different name still makes sense.

Definitely. My point is that the blocker has been the name!

`fetch_and_update` could help but I am not sure if it is an improvement, code wise, to what we have today. Today we do:

```elixir
case Map.fetch(dict, :key) do
  {:ok, val} -> Map.update!(dict, :key, fun)
  :error -> dict
end
```

With `fetch_and_update`:

```elixir
case Map.fetch_and_update(dict, :key, fun) do
  {:ok, key, dict} -> dict
  {:error, dict} -> dict
end
```

It is slightly better in terms of performance, but not enough to justify adding it imo. I thought about `update_existing` but it sounds confusing. How can you update something that does not exist? The current functions are actually upserts but now is too late to change them.

**Comment by MSch** [comment]
I was thinking `{_, map} = Map.fetch_and_update(map, :key, fun)` since I don't actually care about the previous value.

**Comment by MSch** [comment]
I actually think `update_existing` would be a good name. Should we continue this discussion on the ML instead of this PR?

**Comment by josevalim** [comment]
Maybe we could find a synonym for update to use here. Maybe `tap` (taps the value of an existing key) or something. `update_existing` is a no-go from my side because it reveals all other updates are poorly named. :P Yeah, let's continue in the ML.

**Pull request merged**
