### PR TITLE
 Run the formatter on lib/elixir/test/elixir/uri_test.exs

### PR DESCRIPTION
**Pull request by honsq90**

### CODE REVIEW

**Comment by josevalim** [comment]
@honsq90 your changes broke the build, can you please investigate?

**Comment by josevalim** [comment]
Note I have also pushed some changes to further clean up the code. :)

**Comment by honsq90** [comment]
thanks @josevalim! turns out that I added an extra `/` in the uri to parse when extracting the variable. build's good now :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
