### PR TITLE
add Map.atomize_keys function

### PR DESCRIPTION
**Pull request by StevenJL**

### CODE REVIEW

**Comment by alexrp** [comment]
I'm not sure we should be making it that easy to turn a bunch of strings into atoms.

**Comment by josevalim** [comment]
> I'm not sure we should be making it that easy to turn a bunch of strings into atoms.

Precisely.

Please remember that new features need to argued and justfied with code samples, use cases, etc. Otherwise they will likely be rejected. Thank you.

**Comment by SofaKing18** [comment]
@josevalim @StevenJL
Most popular case for me and my team is translate keys from string to atoms in Map.
We use it for access to value like `my_map.my_key`, instead of `my_map["my_key"]`. 
I guess first one is more readable. 
For this i have code below:
```
defmodule MapCommon do
....
  def atomize_keys(map) do
      map
      |> Enum.map((fn {k, v} -> {String.to_atom(k), v} end))
      |> Map.new
  end
end
```

Guess this feature would be nice for core Map module and will be very usefull in phoenix controller's params.

**Comment by mememori** [comment]
@SofaKing18 I think that it would be problematic to provide such function without making it clear that it can break your VM because `String.to_atom/1` converts the input String to an atom (creating it on the atom table if needed) and the atom table is not garbage collected and thus might break the VM

**Comment by SofaKing18** [comment]
@yordis nice solution, ty

@mememori There are many ways to break VM, but what should we do: make language more comfortable or do nothing?

There are 1M atoms by default, average application won't use that all, even if developer will atomize all keys of all maps;

And access to value by atom must be faster, isn't it?

**Comment by yordis** [comment]
@SofaKing18 this is where I understand you because `tee/2` was the similar situation https://github.com/elixir-lang/elixir/pull/7213#issuecomment-374532307

Decide when something gets push into the Core is not really clear right now and normally the minority of people that use it gets affected

**Comment by yordis** [comment]
> The solution provided by @yordis also has flaws, because it assumes all of the atoms have been loaded before hand, which may not be the case,

@josevalim well in case it doesn't an exception will be raise and in the worst scenario you send `500` in your server, but yeah definitely that is an observation.

> tee is not necessary for any of them and, as you said, it is a minority of people that uses it, so it definitely belongs in a package.

Well I understand that it is a minority that use it but you could say that from many functions of the language and they do not belongs to a package. 

Being said that, please ignore me on that sentence because it is my lack of understand on how to build a programming language (hopefully one day I will be able to give the answer by myself) so don't take it as an arguing something but my mind speaking out loud.

**Comment by josevalim** [comment]
> Well I understand that it is a minority that use it but you could say that from many functions of the language and they do not belongs to a package.

The problem is that `tee/2` was proposed to `Kernel`. The threshold for adding something to `Kernel` is very very very high. It is something that by definition affects all of Elixir files. Adding a function to an another module is much more accessible, because somebody would need to explicitly reach to it. The other functions are actually evaluated as a package with the modules they belong to.

**Comment by fertapric** [comment]
I don't know if it helps, but this is how I implemented a "map with indifferent access" for those interfaces that accept a map which could have either atoms or strings as keys. Here is the implementation https://gist.github.com/fertapric/427505e866a16c5073cee086683a13b3

This is an example of its usage:

```elixir
defmodule Blog do
  def create_post(%{} = attrs) do
    author_id = Params.get(attrs, :author_id)
    # Do something with the author_id
  end
end

# Example of using it in IEx
iex> create_post(%{title: "Hello world!", author_id: 1})

# Example in a Phoenix Controller
defmodule MyAppWeb.PostController
  def create(conn, params) do
    case Blog.create_post(params) do
      {:ok, post} -> # Render ok
      _ -> # Render error
    end
  end
end
```

Having the `Params` module eliminated the need to convert all the keys to atoms (or all the keys to strings) to "standarize" the usage of maps within the application.

It might not be performant for big maps (as it could loop twice to detect if all the keys are atoms and all the keys are strings), but I don't expect those in my use cases. If you do, you might implement something similar to [what Ecto does](https://github.com/elixir-ecto/ecto/blob/ce362f8f54f77c67d591d15417943e163256ae1f/lib/ecto/changeset.ex#L545-L566).

**Pull request closed without merging**
