### PR TITLE
Add parentheses. Fixes #3536

### LINKED ISSUE #3536: Makefile: exit with error if current directory contains whitespaces
I noticed Make cannot deal with whitespaces in the path, 

rightnow it's a wrong message the one `make` is giving

(currecnt dir is "/home/eksperimental/eli xir" notice the space in "eli xir")
 
```sh
$ make
/bin/sh: 1: /home/eksperimental/eli: not found
Makefile:67: recipe for target 'erlang' failed
make: *** [erlang] Error 127
```

I think the best we can do is check for space in the current directory `Makefile` is located,  and exit with  a message, as it's a real pain to deal with in `make` that from what I read.

### PR DESCRIPTION
**Pull request by c-rack**
Tested on Debian Linux.

### CODE REVIEW

**Comment by josevalim** [comment]
I think you mean "Add quotes" in the commit message? :)

**Comment by c-rack** [comment]
Yes, you are right, I meant quotes.

**Comment by josevalim** [comment]
Can you change the commit message? I will change the merge commit when merging. :)

**Comment by josevalim** [comment]
merged the quote one, thank you!

**Comment by c-rack** [comment]
Thanks

**Pull request closed without merging**
