### PR TITLE
Fix typo in Registry doc

### PR DESCRIPTION
**Pull request by yct21**

### CODE REVIEW

**Comment by josevalim** [comment]
Both are correct. :) Although there is probably a better placement for the word "though" in that sentence.

**Comment by yct21** [comment]
OK, I'm not a native English speaker and didn't know that was correct.

I'm closing it now :）

**Comment by eksperimental** [comment]
IMO This PR was correct. I cannot think of a proper use of "though" in that sentence

**Comment by josevalim** [comment]
The "though" is meant to be a contrast to the previous example, that uses start_link. It could also be written as:

> However, the registry is started as part of a supervision tree:

**Comment by eksperimental** [comment]
Then your last wording is way more clear @josevalim

**Pull request closed without merging**
