### PR TITLE
Indent some Markdown guides

### PR DESCRIPTION
**Pull request by whatyouhide**
This is what we generally use in Elixir, so I think we should do it in the anti-patterns guides too.

cc @lucasvegi

### CODE REVIEW

**Comment by josevalim** [comment]
@whatyouhide i would skip doing this here in particular because indentation with two spaces makes indentation with code blocks trickier to get right. It is mostly fine for Elixir, as we don't have such large chunks, but those are can get quite large, so I think it is fine as is.  :)

**Comment by josevalim** [comment]
@whatyouhide or maybe we remove the list altogether? The bolding already provides all style necessary.

**Comment by josevalim** [comment]
Yeah, we can remove the list:

image

**Comment by whatyouhide** [comment]
Yeah I like that. Done.

**Comment by lucasvegi** [comment]
> This is what we generally use in Elixir, so I think we should do it in the anti-patterns guides too.
> 
> cc @lucasvegi

Thanks for the suggestion! I will try to follow this template in future contributions.

**Pull request merged**
