### PR TITLE
fix type details in child spec `:shutdown` documentation

### PR DESCRIPTION
**Pull request by aweagel**
Minor documentation improvement

### CODE REVIEW

**Comment by whatyouhide** [comment]
Thank you @josevalim! 💟

**Comment by fertapric** [comment]
And thank you @aweagel! 💜 😂

**Comment by whatyouhide** [comment]
LOL, I was writing a message to José and my brain just wrote his username here. Thanks for the catch @fertapric and thank you @aweagel 😄

**Comment by aweagel** [comment]
More than honored to have been temporarily mistaken for @josevalim :joy:

**Pull request merged**
