### PR TITLE
Ignore _build directory of test fixture apps

### PR DESCRIPTION
**Pull request by maennchen**
When working in the repository, I get some non-ignored files that should probably be ignored so that they are not committed by accident:

```console
$ git status -s
?? lib/mix/test/fixtures/test_failed/_build/
?? lib/mix/test/fixtures/umbrella_test/apps/bar/_build/
?? lib/mix/test/fixtures/umbrella_test/apps/foo/_build/
```

### CODE REVIEW

**Comment by josevalim** [comment]
I don't have those files generated locally after a complete run. We also don't compile within the fixtures, so they should not have a _build. Maybe something unexpected cause those files to compile?

**Comment by maennchen** [comment]
@josevalim It's possible that the Elixir VSCode Extension has something to do with it.

**Comment by josevalim** [comment]
Yeah, it may be trying to compile files that it should not. But I don't think it is an issue with this repo. :)

**Comment by maennchen** [comment]
For anyone else having this issue:

* (if you haven't already) Setup global `.gitignore` - https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer
* Add the two lines from the diff into your global `.gitignore`

**Pull request closed without merging**
