### PR TITLE
Add Examples section to Kernel.is_struct/1

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
Why the change? in any case, I think `%URI{}` will be easier to grasp

**Comment by eksperimental** [comment]
`1..2` would work too

**Comment by josevalim** [comment]
@eksperimental we should not be telling users to create structs like %URI{} directly.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
