### PR TITLE
Add Kernel.ceil/1 and Kernel.floor/1 buildins

### PR DESCRIPTION
**Pull request by lukaszsamson**
Fixes https://github.com/elixir-lang/elixir/issues/7882

### CODE REVIEW

**Comment by josevalim** [comment]
Looks great! Two things remaining: simple tests (see kernel_test.exs) and
the spec for ceil is wrong.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fertapric** [comment]
There is also `Float.ceil/2` and `Float.floor/2`, should those functions be mentioned here? Or viceversa?

**Comment by josevalim** [comment]
Yeah, we should probably say that if they want floats back with a certain
amount of decimal places they should refer to the float ones.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by lukaszsamson** [comment]
I added tests and fixed the spec. I also added doc references to Float functions.

**Comment by michalmuskala** [comment]
Thank you! :heart:

**Pull request merged**
