### PR TITLE
Standardize links

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
well, but the DOCUMENTATION button at the top links to www.
Actually, if you visit: http://erlang.org it redirects you to http://www.erlang.org

They should stick to one,
Do you know where to report this? or could you report it.

**Comment by eksperimental** [comment]
oh.. i see and http://www.erlang.org/doc/ redirects to http://erlang.org/doc/
:-?

**Comment by josevalim** [comment]
I am unsure what to think about now since www.erlang.org/docs/... redirects to erlang.org/docs/... but "erlang.org" redirects to "www.erlang.org". I think we should keep whatever will cause the URLs we link to not redirect.

**Comment by josevalim** [comment]
@eksperimental yeah, haha.

**Comment by eksperimental** [comment]
ok. I propose the following, I drop the commit related to this. I try to report this and see what they want to do with it, and make the changes once the issue is addressed.
WDYT?

**Comment by josevalim** [comment]
@eksperimental sounds good to me!

**Comment by eksperimental** [comment]
great. commit dropped

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
