### PR TITLE
Allow heading separator in IO.ANSI.Docs to not to have spaces around "|"

### PR DESCRIPTION
**Pull request by eksperimental**
This is supported by GFM (GitHub Flavored Markdown).

### CODE REVIEW

**Comment by eksperimental** [comment]
This is built on top of this PR https://github.com/elixir-lang/elixir/pull/9615
Please merge once the other PR is merged

**Comment by josevalim** [comment]
@eksperimental can you please rebase?

**Comment by eksperimental** [comment]
> @eksperimental can you please rebase?

@josevalim done!

**Comment by fertapric** [comment]
Thanks @eksperimental! 💜

**Pull request merged**
