### PR TITLE
Enum to list

### PR DESCRIPTION
**Pull request by eksperimental**
- Enum.to_list/1: Optimize for ranges
- Add tests for Enum.reverse/1, Enum.reverse/2 and Enum.to_list/1

### CODE REVIEW

**Comment by josevalim** [comment]
thank you @eksperimental. I am more inclined to not accept this one because I think the cost of traversing it and calling reverse at the end like today is probably very low?

**Comment by eksperimental** [comment]
to my surprise I have these benchmarks,

```elixir
defmodule ToListRange.Original do
  def reverse(enumerable) do
    Enum.reverse(enumerable) |> :lists.reverse
  end
end

defmodule ToListRange.Optimized do
  def reverse(first..last) do
    Enum.reverse(last..first)
  end
end
```
```
## EnumToListRangeBench
1..1000000     -9.58%
1..10000000    -3.88%
1..100000      -2.49%
1..1000        +2.32%
1..10          +5.75%
1..100         +10.00%
1..10000       +12.21%
1..1           +37.88%
``` 

I'm not surprised to see a  performance of ranges over 100_000, but to see that the performance decreased for anything lower than 10_000.
aparently pattern matching on a range, is very expensive

so let's just merge my second commit then

can you do it from here, or should i update my PR to remove the first commit

**Comment by josevalim** [comment]
please remove the first commit because i cannot discard it from here. :)

**Comment by eksperimental** [comment]
done

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
