### PR TITLE
Add Date.beginning_of_month/1 and Date.end_of_month/1

### PR DESCRIPTION
**Pull request by wojtekmach**

### CODE REVIEW

**Comment by wojtekmach** [comment]
I figured I'll just send the PR, let me know what you think! cc @kipcole9, @Qqwy, @lau

**Comment by jalcine** [comment]
I’ve been doing this manually for some time; this would be a very happy edition for me.

(Originally published at: https://v2.jacky.wtf/post/acc5112c-8aed-4378-912b-05235c6b3b6e)

**Comment by kipcole9** [comment]
Similarly I have this as `first_day_of_month/1` and `last_day_of_month/1` in my `Cldr.Calendar` behaviour so this also makes sense for me.

**Comment by fertapric** [comment]
Awesome @wojtekmach! 🙌

**Pull request merged**
