### PR TITLE
Correct tense in Mix.Tasks.Test cmd line options

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
:+1:. Also, maybe we should stop aligning the `-` and sort those alphabetically? What does others think?

**Comment by eksperimental** [comment]
+1 for both

**Comment by lexmag** [comment]
> Also, maybe we should stop aligning the `-` and sort those alphabetically?

Yes please.

**Comment by josevalim** [comment]
Haha, let's do it then.

**Comment by eksperimental** [comment]
please guys have a look

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
