### PR TITLE
rename single-char variables and other variables with a more descriptive name

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks a lot for the effort but I am more inclined to not merge it. While some are definitely better, others I find too subjective, and I am more concerned with the effects on the codebase, likely merging some existing pull requests stale and what not. Thoughts?

**Comment by eksperimental** [comment]
@josevalim: Are you worried that these changed will mess up with PRs not merged yet?

Well, initially I started replacing "o" with "other", then I found that we still have in the definition of public functions variables named "f" instead of "fun", and the others are just to improve the readability of the code. Just to keep consistency, but feel free to tell me which ones you don' t want, I can happily update the PR, or if you feel it's more convenient not to have it, no worries at all.

**Comment by josevalim** [comment]
Well, none of those are public. :) Some may be `def` but the module is `@moduledoc false`. :)

**Comment by eksperimental** [comment]
that's explains why we still have those, becuase last time i fixed this i used the docs to search for the functions with single-char vars.

**Comment by josevalim** [comment]
:)

**Comment by eksperimental** [comment]
@josevalim since there are almost no open PRs.
I can volunteer to have a second go at this PR. wdty?

**Comment by ericmj** [comment]
While some of the changes are improvements, many are not, they just increase the number of characters in the identifier.

As an example, `defp nillify(other), do: other` is not more clear than `defp nillify(o), do: o`.

**Pull request closed without merging**
