### PR TITLE
Add step to Add/Update link to docs in Docs page in website

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
This won't help me because the `docs.html` step is only after the release is made official and the current lines are about branching on the git repo. I will have to add a note somewhere else. Thank you!

**Comment by eksperimental** [comment]
no worries

**Comment by eksperimental** [comment]
@josevalim I've been thinking about this.
And I realize two things:
for a Patch release, the changes are valid.

For a Minor release, I think the changes are still valid, because even though the official hasn't been released, the stable docs will link to the new release. So i don't think there's anything wrong with updating the docs page.

WDYT?

**Comment by josevalim** [comment]
We create a new minor branch in the repository when we release the first RC. We change stable on the website when the final version is out. Those happen at different moments. I am saying from experience that adding this note is not going to help me during the release process. :)

**Comment by eksperimental** [comment]
true. I overlooked the minor release initially being a RC.
so, whatever you think is gonna work out best for you, since you are the one doing the release
:-D

**Pull request closed without merging**
