### PR TITLE
Use ex_doc admonition blocks when possible

### PR DESCRIPTION
**Pull request by whatyouhide**

### CODE REVIEW

**Review by josevalim — COMMENTED** [review]
LGTM but we should change the casing. We don't use titlecase anywhere in Elixir, so "Avoiding the Application Environment" should be "Avoiding the application environment" and so on.

**Comment by whatyouhide** [comment]
Ah good to know, I thought we did for section titles. Will do and merge then 😌

**Review by josevalim — COMMENTED** [review]
Btw, also look for `> **`. But in another PR?

**Comment by whatyouhide** [comment]
@josevalim done in https://github.com/elixir-lang/elixir/commit/a20da2b92f4994b82bfe6c693aba86b7fa04cda8

**Pull request merged**
