### PR TITLE
Use :extra_applications instead of :applications in escript.build

### PR DESCRIPTION
**Pull request by whatyouhide**
I wonder, could this veeery simple change be a solution for #5529? 🤔 :)

### CODE REVIEW

**Comment by josevalim** [comment]
You need to get both and concatenate tchem together with ++. We can use
Keyword.get/3 with a default of an empty list.

**Comment by josevalim** [comment]
We should probably change an existing escritp test to use
extra_applications.

**Comment by whatyouhide** [comment]
@josevalim I implemented both suggestions. While changing the test related to [this](https://github.com/elixir-lang/elixir/blob/4024b937e2d61b2d31b8679e2e96198e048376a1/lib/mix/test/mix/tasks/escript_test.exs#L40-L52) in particular:

```elixir
  defmodule EscriptErlangWithDeps do
    def project do
      [app: :escripttesterlangwithdeps,
       version: "0.0.1",
       language: :erlang,
       escript: [main_module: :escripttest],
       deps: [{:ok, path: fixture_path("deps_status/deps/ok")}]]
    end

    def application do
      [applications: []]
    end
  end
```

I left `:applications` to `[]` since we don't want to bring the `:ok` application in the escript as that would require to embed Elixir. Out of curiosity, I tried using `applications: [:ok]` and `escript: [embed_elixir: true]` and it in fact worked, but then I tried `applications: [:ok], extra_applications: [:elixir]` (with `embed_elixir: false`) and it didn't work, failing to load the `:elixir` application; is this expected and I'm missing something? I know about the docs of `escript.build` that say

> you will have to add paths to Elixir’s ebin directories to ERL_LIBS environment variable when running the resulting escript, in order for the code loader to be able to find :elixir application and its children applications (if they are used).

but I expected that putting `:elixir` in the `:extra_applications` would do the trick anyways, but [here](https://github.com/elixir-lang/elixir/blob/4024b937e2d61b2d31b8679e2e96198e048376a1/lib/mix/lib/mix/tasks/escript.build.ex#L187-L193) we don't do anything about extra applications for Erlang escripts.

Sorry for the convoluted wall of text, hope my questions are clear enough 😄

**Comment by josevalim** [comment]
> but I expected that putting :elixir in the :extra_applications would do the trick anyways,

No because we change the escript generated based on the language configuration. Basically, you never add :elixir to `:extra_applications`, Mix takes care of it for you.

**Comment by josevalim** [comment]
I guess though you found a bug in that if someone depends on logger and not the parent project, `:logger` won't be included after all. I think we should open up a separete report for it though, it is not related to this bug per se, as it likely exists since the beginning of escript.build (and this one is a regression).

**Comment by whatyouhide** [comment]
@josevalim ok, got it. I will investigate and open another bug for that. Regarding this PR, do we need to change anything else?

**Comment by whatyouhide** [comment]
Awesome, backported to v1.4 as well.

**Pull request merged**
