### PR TITLE
Update formater inputs

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
You will have to format docs.exs too, can you please do so? Thank you!

**Comment by eksperimental** [comment]
yes. I know, it was formatted in the other PR. I will do it.

**Comment by eksperimental** [comment]
@josevalim please have a look. I have updated the rules are more files were not being formatted

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
