### PR TITLE
Allow Hex version to be configured by Mix.Project

### PR DESCRIPTION
**Pull request by xtian**
Since different Hex versions can result in different `mix.lock` output, I think it would be helpful to allow a project's desired Hex version to be configured via `Mix.Project`. This would help everyone working on the project to avoid git conflicts/churn in the lockfile.

I didn't see any existing tests around `Mix.CLI` or `Mix.Hex` but if this change is desirable I can look into adding some. (Any guidance around the best way to test this functionality would be greatly appreciated 😄  )

Also, is [this section in Mix.Project](https://github.com/elixir-lang/elixir/blob/867da6f876c48279823a41a33030c95ef37379b2/lib/mix/lib/mix/project.ex#L17)  the best place to add documentation?

### CODE REVIEW

**Comment by josevalim** [comment]
@xtian as far as I know, Hex does not allow you to rollback to a previous version and this would allow someone to set hex to a version nobody can fetch. Given you should be on latest, if the lock changes, then you have to update Hex. :)

Also the Hex team is working on solving those issues so it doesn't change the lock unless strictly necessary.

In any case, thanks for the PR!

**Comment by xtian** [comment]
Ok, thanks for the info!

**Comment by ericmj** [comment]
> as far as I know, Hex does not allow you to rollback to a previous version and this would allow someone to set hex to a version nobody can fetch. Given you should be on latest, if the lock changes, then you have to update Hex. :)

@josevalim is correct and the idea is that when Hex 1.0 is released you will be able to install a specific Hex version with `mix local.hex`.

**Comment by milmazz** [comment]
@xtian If you want to avoid unnecessary commits including the `mix.lock` file you can do the following as a workaround:

```console
$ git update-index --assume-unchanged mix.lock
```

When you or someone else in your team needs to commit changes in the `mix.lock`:

```console
$ git update-index --no-assume-unchanged mix.lock
$ git add mix.lock
...
```

HTH

**Pull request closed without merging**
