### PR TITLE
Fix charlist formatting issue on '\"'

### PR DESCRIPTION
**Pull request by sabiwara**
Close https://github.com/elixir-lang/elixir/issues/13363

### CODE REVIEW

**Comment by josevalim** [comment]
I am worried this may introduce other regressions. What if we check if the string has a “ and, if so, we use the sigil c with single quotes?

**Comment by sabiwara** [comment]
> I am worried this may introduce other regressions.

This is a fair point, I actually started working on a prop-based tests to catch some other cases and indeed it did.

> What if we check if the string has a “ and, if so, we use the sigil c with single quotes?

Could be a strategy, but it might be a bit more tedious to check for interpolation (not a big deal).
I was also evaluating replacing the whole `String.replace` pipe with a recursive function, will see how it goes and report back.

**Comment by josevalim** [comment]
I am honestly a bit worried because we are adding logic for handling `'' => ~c""`, which is a change of delimiters, into general delimiter logic.

So I would still prefer to emit `~c''` if there are `"`. It has an added benefit of not really changing the contents of the string.

**Comment by sabiwara** [comment]
> I am honestly a bit worried because we are adding logic for handling '' => ~c"", which is a change of delimiters, into general delimiter logic.

That's a great point. Will go with your approach!

**Comment by sabiwara** [comment]
@josevalim we should be good now, and the property-based tests still pass ✅

**Review by josevalim — APPROVED** [review]
Beautiful, please backport to v1.16 as well!

**Comment by sabiwara** [comment]
Backported 677ad618e9fd78c2c73497b67f9768cb87517cce
FYI had to fix a small test that had been removed on main a99a9cf47ae0bb49e8e2a44299ccef09c8472fac

**Pull request merged**
