### PR TITLE
Add links to Erlang modules

### PR DESCRIPTION
**Pull request by eksperimental**
command used to find these cases:

    $ ag '(?<!\[)`\:[^`]+`\s+module'

### CODE REVIEW

**Comment by josevalim** [comment]
Hrm. ExDoc can automatically link to those. Do we need the links?

**Comment by eksperimental** [comment]
they are not! I remember having this discussion, but I forgot what was the decision...

**Comment by eksperimental** [comment]
Is that a setting in ExDoc? or it is something that can be implemented? ....
If ExDoc can take care of this, we need to think of cases where we will still need a link when reading docs in IEx.

**Comment by josevalim** [comment]
@eksperimental I don't see any reason why we couldn't implement it on ExDoc but now that you mentioned it, it does look like we discussed it in the past. Was it because of possible false positives? Like linking the atom `:user` to Erlang's user module?

**Comment by josevalim** [comment]
Anyway, this change seems to be relevant today, so it is approved.

**Comment by eksperimental** [comment]
@josevalim from what I can see at the moment we are also not auto-linking in ExDoc to erlang functions either.
I have found some related discussions, shall I create an issue for this?

**Comment by josevalim** [comment]
@eksperimental do you have examples of where we are not linking? because that part in particular totally should: https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/formatter/html/autolink.ex#L324

**Comment by eksperimental** [comment]
check docs for `System.html#monotonic_time/0`

you'll see
> Inlined by the compiler into `:erlang.monotonic_time/0`.

not being linked

**Comment by josevalim** [comment]
> not being linked

Fixed in ExDoc master. Thank you!

**Comment by josevalim** [comment]
We need another approval and a merge on this one.

**Pull request merged**
