### PR TITLE
Fix gen_event docs typo

### PR DESCRIPTION
**Pull request by beedub**
~Can also just make the fix `provides a`~

### CODE REVIEW

**Comment by kennyballou** [comment]
Random drive by comment: I personally feel using `is a` limits the scope the description to "_only_ a tool". 
But again, opinion and the like...

**Comment by beedub** [comment]
reverted the verb change, and just fixed the typo. don't want to further any verb discussion :)

**Comment by kennyballou** [comment]
It's not like anyone is supposed to listen to me ...

👍

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
