### PR TITLE
Improve specs for List.improper?/1

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by michalmuskala** [comment]
Wouldn't dialyzer complain in here that it doesn't currently (so probably never will) support functions with overlapping domains?

**Comment by josevalim** [comment]
@michalmuskala you are correct. I always forget about this detail. I think we should keep things as is then.

**Comment by josevalim** [comment]
Ping.

**Comment by eksperimental** [comment]
so basically Dialyzer will treat `nonempty_improper_list2` as a `list` and it will overlap. Is that what you are saying @michalmuskala ?

**Comment by josevalim** [comment]
Yes. It will automatically become `list :: true | false` once it merges.

**Pull request closed without merging**
