### PR TITLE
Kernel.SpecialForms: use `quote do:` onliner when possible

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
I think we should rather use `quote do...end`  for consistency and avoid confusion. That's the same reason why we usually use parens and avoid one liners in the docs. :)

**Comment by lexmag** [comment]
:+1: for `quote do...end`.

**Comment by eksperimental** [comment]
So should i send a new PR replacing the onliners?

**Comment by josevalim** [comment]
@eksperimental I think so. Can you send some examples for us to be sure? I think it would be a good guideline unless the goal of the example is exactly to show the one liner itself. :)

**Comment by eksperimental** [comment]
@josevalim there're two modules: Macro and Kernel.SpecialForms

you can see the examples here (search for this string: "quote do: ")

http://elixir-lang.org/docs/master/elixir/Macro.html
http://elixir-lang.org/docs/master/elixir/Kernel.SpecialForms.html

the question, is whether we want to express:

```elixir
      iex> value = 13
      iex> quote do: sum(1, unquote(value), 3)
      {:sum, [], [1, 13, 3]}
```

as:

```elixir
      iex> value = 13
      iex> quote do sum(1, unquote(value), 3) end
      {:sum, [], [1, 13, 3]}
```

or as:

```elixir
      iex> value = 13
      iex> quote do
      ...>   sum(1, unquote(value), 3)
      ...> end
      {:sum, [], [1, 13, 3]}
```

**Comment by josevalim** [comment]
The last one IMO

**Comment by eksperimental** [comment]
great, I thought of the later one as well.
One last case is

```elixir
    iex> Macro.to_string(quote do: foo.bar(1, 2, 3))
    "foo.bar(1, 2, 3)"
```

Should we go with...
```elixir
    iex> Macro.to_string(quote do foo.bar(1, 2, 3) end)
    "foo.bar(1, 2, 3)"
```

or leave it as it is?

**Comment by josevalim** [comment]
I would add parens around `quote(do: ...)`.

**Comment by eksperimental** [comment]
thanks @josevalim , 
closing in favour of https://github.com/elixir-lang/elixir/pull/4376

**Pull request closed without merging**
