### PR TITLE
Improve heredoc error message

### PR DESCRIPTION
**Pull request by kw7oe**
Address issue #9047 

I am not sure if this PR resolve the issue mentioned. If not, feel free to point me to the right direction. Thanks.

### CODE REVIEW

**Comment by eksperimental** [comment]
It is kind of contradictory the "MUST be followed by OPTIONAL whitespace"
here's an improved version.

> heredoc start may be followed by whitespaces after ''' but must be followed by a new line

optional
> heredoc start may be followed by whitespaces after ''' **and** must be followed by a new line

**Comment by kw7oe** [comment]
> It is kind of contradictory the "MUST be followed by OPTIONAL whitespace"
> here's an improved version.
> 
> > heredoc start may be followed by whitespaces after ''' but must be immediately followed by a new line
> 
> optional
> 
> > heredoc start may be followed by whitespaces after ''' **and** must be immediately followed by a new line

Now that you mentioned it, I agree that it is kind of contradictory. Personally, I think the first improved version is better.

**Comment by josevalim** [comment]
Unfortunately the """ must always come at the end. So perhaps:

> heredoc start may be followed by whitespaces and then followed by a required a new line after """

?

**Comment by eksperimental** [comment]
I'm OK with that (therea a typo though, it should read "by a required new line").
Why does the message need to end with the markers?

**Comment by josevalim** [comment]
> Why does the message need to end with the markers?

Yes.

> I'm OK with that (therea a typo though, it should read "by a required new line").

I am not sure where the "by" goes. Can you please post the whole suggestion? :)

**Comment by kw7oe** [comment]
> I'm OK with that (there is a typo though, it should read "by a required new line").
> Why does the message need to end with the markers?

The message need to end with the markers because it will raise `TokenMissingError` instead of `SyntaxError` if the message does not end with markers _(probably due to the implementation of `parse_error` in `elixir_errors.erl`)_.

To place the marker in between in the message, I think it will require code changes in the mentioned module.

**Comment by eksperimental** [comment]
there was an extra "a" in the suggestion you posted before your edit.
> heredoc start may be followed by whitespaces and then followed by a required new line after """

I would go with something like this.

> heredoc start """ may be followed by optional whitespaces and a new line is required after it


It's kind of limiting having to write the sentence ending with the `"""`, 
here's the hack to achieve it

```diff
diff --git a/lib/elixir/src/elixir_tokenizer.erl b/lib/elixir/src/elixir_tokenizer.erl
index 3b25341a8..b460e0501 100644
--- a/lib/elixir/src/elixir_tokenizer.erl
+++ b/lib/elixir/src/elixir_tokenizer.erl
@@ -879,8 +879,8 @@ extract_heredoc(Line0, Column0, Rest0, Marker, Scope) ->
           {error, {ErrorLine, ErrorColumn, Message, Token}}
       end;
     error ->
-      Message = "heredoc start must be followed by a new line after ",
-      {error, {Line0, Column0, io_lib:format(Message, []), [Marker, Marker, Marker]}}
+      Message = "heredoc start ~ts may be followed by optional whitespaces and a new line is required after ",
+      {error, {Line0, Column0, io_lib:format(Message, [[Marker, Marker, Marker]]), ["it"]}}
   end.
 
 heredoc_error_message(eof, Line, Terminator) ->
diff --git a/lib/elixir/test/elixir/kernel/errors_test.exs b/lib/elixir/test/elixir/kernel/errors_test.exs
index aa5233ef1..5967c3489 100644
--- a/lib/elixir/test/elixir/kernel/errors_test.exs
+++ b/lib/elixir/test/elixir/kernel/errors_test.exs
@@ -159,7 +159,7 @@ defmodule Kernel.ErrorsTest do
 
   test "heredoc start" do
     assert_eval_raise SyntaxError,
-                      "nofile:1: heredoc start must be followed by a new line after \"\"\"",
+                      "nofile:1: heredoc start \"\"\" may be followed by optional whitespaces and a new line is required after it",
                       '"""bar\n"""'
   end
 
```

**Comment by josevalim** [comment]
The marker may be used by other parts of the tool chain, it is important
that it is actually the token and not some random word. Therefore the “””
has to come last.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
One last take:

> heredoc allows only zero or more whitespace characters followed by a new line after

**Comment by kw7oe** [comment]
I have make the changes using the following error message:

> heredoc allows only zero or more whitespace characters followed by a new line after

**Comment by fertapric** [comment]
What do you think about?

> heredoc's start must be followed by a new line (whitespaces are ignored) after

or:

> heredoc's start must be followed by a new line (ignoring whitespaces) after

**Comment by josevalim** [comment]
@fertapric I think the (ignoring whitespace) is not super clear. Is it before the """, after? before the newline, after?

**Comment by fertapric** [comment]
Thanks @kw7oe! 💜

**Pull request merged**
