### PR TITLE
Enum.chunk/2: improve function guard

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by whatyouhide** [comment]
👍 from my side.

**Comment by whatyouhide** [comment]
@ericmj it does but then you get

```
** (FunctionClauseError) no function clause matching in Enum.chunk/4
    (elixir) lib/enum.ex:367: Enum.chunk([1, 2, 3], 0, 0, nil)
```

, not sure this is a good "error". Wdyt?

**Comment by ericmj** [comment]
I think we usually are fine with FunctionClauseErrors from internal functions, the stacktrace will show where the user calls the function. It's usually not viable to catch all at the outer API layers.

WDYT @josevalim?

**Comment by michalmuskala** [comment]
In that case there won't be a stacktrace entry for `Enum.chunk/2` because of a tail call

**Comment by ericmj** [comment]
There should be a trace where the user calls the `chunk/2` function unless that's also a tail call. But that can of course happen for every function.

**Comment by josevalim** [comment]
chunk/4 will catch it, so we are good!

**Pull request closed without merging**
