### PR TITLE
make templates for mix.new configurable

### PR DESCRIPTION
**Pull request by pragdave**

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @pragdave. I would rather go the opposite direction. Instead of providing a module that we will call functions on, maybe we should expose the default templates for developers to call as they wish. Or maybe we should allow developers to mention which files should be skipped, which you then fill in after the parent generator runs.

My concern is that code in Elixir needs to be stable but the generated code is not necessarily stable, instead they aim to provide the best getting started experience. For example, in Elixir v1.5 we will likely get rid of the lib/my_app/application.ex file... and what if someone was depending on exactly this file being generated and customized?

Then I will be cornered into keeping backwards compatibility and I won't be able to improve the getting started experience. I also wouldn't like to add an API that we don't guarantee compatibility for, as that would defeat the point of exposing it in the first place.

So we can have discussions on alternative ways of handling this but I am confident it is not the direction in the current pull request.

**Comment by pragdave** [comment]
Actually, the PR allows you to  do that. The calls into the templates come
from new.ex—if you don't call a template, it won't be used. So removing a
file is not an issue. And you don't maintain compatibility anyway—those who
write templates do.

Here's the thing. I don't think we really need to make this configurable at
all. I also want to give people the best possible experience. But I don't
agree we currently do that. So rather than argue about it, I thought it
might be better simply to provide an alternative, and then let the
community comment on the relative merits of each. That way, we'd be able to
take the best of both to synthesize the new templates.

So is there a way to sneak this in just temporarily so we can perform the
experiment?

**Comment by josevalim** [comment]
> if you don't call a template, it won't be used

Precisely. Now imagine that someone requires template.lib_app to be generated and now we no longer invoke it because we no longer need it? Or imagine someone delegates almost all operations to the default templates assuming they are wired a certain way... but then we decide to change it.

This solution is very coupled to how the generators work today and I don't want to make a commitment to keep the `mix new` generator like that in the next couple years.

> Here's the thing. I don't think we really need to make this configurable at all. I also want to give people the best possible experience. But I don't agree we currently do that. 

Perfect!

You can create your own new generators and have them installed globally as an archive. Elixir v1.4 has features to make this workflow as straight-forward as possible:

    $ mix archive.install hex diet_new
    $ mix diet.new

The best part is that this is available today and you won't have to wait for Elixir v1.5 to be out (which will be in at least 4 months). Nerves has a good example: https://github.com/nerves-project/nerves/tree/master/bootstrap

> So is there a way to sneak this in just temporarily so we can perform the experiment?

I don't see how sneaking this in temporarily would help experimentation since this PR would require developers to use Elixir master, which very few do. If your goal is to experiment and try different approaches, I would say the archive way is the best way to do it today.

**Comment by pragdave** [comment]
On Thu, Mar 2, 2017 at 4:41 PM José Valim <notifications@github.com> wrote:

> if you don't call a template, it won't be used
>
> Precisely. Now imagine that someone requires template.lib_app to be
> generated and now we no longer invoke it because we no longer need it? Or
> imagine someone delegates almost all operations to the default templates
> assuming they are wired a certain way... but then we decide to change it.
>

​So it won't work with the current system, either. If you remove a file,
someone who relies on it will have to adapt...​



> You can create your own new generators and have them installed globally as
> an archive. Elixir v1.4 has features to make this workflow as
> straight-forward as possible:
>

​Just so I understand—are you suggesting I copy tasks/new.ex?
​

>

**Comment by josevalim** [comment]
> ​Just so I understand—are you suggesting I copy tasks/new.ex?

Yes, that's the best option that works right now. And if Elixir changes any file in `mix new`, your generators will continue working.

At some point we need to find a better balance between duplicating all files and coupling to the generator structure, but the proposed PR is a bit too much on the coupling side for my taste. :)

**Comment by whatyouhide** [comment]
What's the plan for this PR? :)

**Comment by josevalim** [comment]
I believe we can close this as we won't merge this particular implementation of generators customization. We are still interested on alternatives though.

Thanks @pragdave !

**Comment by pragdave** [comment]
> At some point we need to find a better balance between duplicating all
> files and coupling to the generator structure, but the proposed PR is a bit
> too much on the coupling side for my taste. :)
>
​I'm not sure I understand where the coupling is.

This isn't general purpose templating. It has to generate a fixed set of
files with a fixed set of data assigns.

If you add a new file, the way I implemented the templating it will
automatically fall back to using the standard one. If you remove a file,
you'll never call the template, and nothing will get generated.

Dave
​

**Comment by josevalim** [comment]
>  If you remove a file,
you'll never call the template, and nothing will get generated.

Exactly, and what if the template implementation relies strongly on that file being invoked? To provide a very concrete example: Phoenix v1.3 generates a `lib/my_app/application.ex` file with custom logic for starting the Phoenix endpoint and Ecto repo. However, in Elixir v1.5, we will no longer generate a `lib/my_app/_application.ex`, now it means that, if Phoenix were using templates, building Phoenix v1.3 applications on Elixir v1.5 will be broken because the `lib/my_app/application.ex` file, which is essential for Phoenix functioning, is no longer invoked.

**Comment by pragdave** [comment]
OK, but I'm not talking about application specific templating (although
that would be nice later). I'm talking very specifically about just `mix
new`.

**Comment by josevalim** [comment]
@pragdave but my comment above was about `mix new`, in a scenario that Phoenix removes its `mix phx.new` in favor of `mix new` with templates. If we merge this to Elixir, many will try to use those templates, and my point is exactly that I can't guarantee all of those uses will be correct.

**Comment by pragdave** [comment]
That's a little like saying that the current templates are broken because
if you use `mix new` it doesn't generate a Phoenix app.

I just don't see the issue. You have a bunch of template groups (standard,
Phoenix, umbrella, lean, etc) and each generates a different kind of
application. Sometimes two template groups generate the same kind of
application.

Right now, the PR assumes the ONLY use us to replace `mix new`. If you
wanted to build in some safety, we could extend it to declare the types of
application it can generate (normal, application, umbrella, phoenix,
nerves, ...) and then have mix xxx.new set the application type to xxx.

**Comment by josevalim** [comment]
I am not sure how else I can explain the issue.

If we provide this feature, developers will build templates with the
expectation certain functions will be called, and as soon as we stop
calling those functions, because we found better ways to structure your
app, those templates will be broken.

You cannot build on top of "mix new" because there is no guarantee "mix
new" will continue to behave as it does today.

This is exposing parts of the Elixir code that may change any time and, as
such, I don't feel comfortable exposing them. I want to reserve the right
of doing those changes.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by pragdave** [comment]
I can add a version number to the API. When you change the call sequence,
bump the version. I'll arrange for generators to contain the range of APIs
they support, and refuse to run outside that range.

But if that doesn't work, let's end this thread. It's totally your call.

**Comment by Eiji7** [comment]
@pragdave: I read your changes and I also think similarly to José.
Lets look at example change:
```elixir
- create_file "README.md",  readme_template(assigns)
+ create_file "README.md",  template.readme(assigns)
```
So you requires from custom templates that them will always share a **valid** `README.md` file (by valid I mean a version of file from current Elixir version - it's not good idea) Instead of this we should **join** them, so `README.md` could contain:
```
# Elixir README.md contents, maybe optionally changed by opts in future in case we removing something by option(s)
# separator like: "\n--------------\n"
Custom template (template_name) notes:
# custom template notes
```
> but my comment above was about mix new, in a scenario that Phoenix removes its mix phx.new in favor of mix new with templates. If we merge this to Elixir, many will try to use template customization, and my point is exactly that I can't guarantee all of those uses will maintain valid with time.

As José wrote we could have a conflict when custom template requires a file that is not supported in current Elixir version. We need to keep backwards compatibility **always** - no matter if we are generating a project from `standard template` or from `custom template` - first run should always work without **any** compilation errors. No matter if we are using custom templates from tomorrow or from next year(s).

To achieve this we need to have much more complex options. José choose a `Phoenix` templates as an example - I think it's really good point.
If we are calling: `mix new template=phoenix` then without any special care about backward compatibility it's easy to have a conflict in future.
If we are going to introduce custom templates then we need to add a support for something like `backward_compatibility_opts`, so template could require to add some files that are not supported in newer version of Elixir. In this case core developer when removing something that's obsolete need to add an option to keep deprecated file as an option.

Next thing is:
How `Phoenix 1.3` could know that in new `Elixir 1.5` will be an backward compatibility option that it will require? We could make all that options be enabled by default, but it's not a good idea too.

The main problem of Elixir (and not only) core developers is to implement solution that is good for all. They can't exclude anyone, because they want to add a solution good for others.

Feel free to send next PRs once you achieve all of what I and José explained.
Hope that my answer helped :smile:

**Comment by josevalim** [comment]
@pragdave I believe the versioning helps a lot but I still believe it is a subpar solution compared to you implementing your own `mix xxx.new` command. The way I see it, we have two options:

  1. Implement your own `mix xxx.new` that will work even in new Elixir versions
  2. Implement a template system that may be broken on any new Elixir version

Why would you choose the second option? Maybe there are some major pain points in the second option that I am not aware... if so, what are they? Should we rather try to fix them instead?

**Pull request closed without merging**
