### PR TITLE
Check for POSIX compliant shell scripts in CI

### PR DESCRIPTION
**Pull request by eksperimental**
WIP because I need to run it against the CI to see if it works

### CODE REVIEW

**Comment by eksperimental** [comment]
This works, the failing test is unrelated

**Comment by josevalim** [comment]
We should check for bin/iex too. :)

**Comment by eksperimental** [comment]
I was planning on convert the rest of the bin files once this is merged

**Comment by josevalim** [comment]
@eksperimental let's get them all ready upfront. :) I pushed bin/elixirc. It CI passes, we should be good to go!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
Sorry, I was away for a couple of days. I see that you have taken care of it. Awesome. We can state that we are POSIX compliant.

**Pull request merged**
