### PR TITLE
Use proper calendar types

### PR DESCRIPTION
**Pull request by fertapric**

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by michalmuskala** [comment]
BTW, shouldn't we have a warning for non-existent types? We probably could do something like that with xref, couldn't we?

**Comment by josevalim** [comment]
@michalmuskala I think it is the job of dialyzer or similar tools to catch things like that. :)

**Comment by michalmuskala** [comment]
If that's the case shouldn't we be running dialyzer on CI? Otherwise we can ship broken code.

**Comment by josevalim** [comment]
@michalmuskala I am ok with doing so to at least detect undefined types. :+1:

**Pull request merged**
