### PR TITLE
Fix table format in Base module

### PR DESCRIPTION
**Pull request by eksperimental**
The tables were shown as code, also it exposes two bugs in IEx when formatting tables, which are fixed in subsequent PRs

It also shows the need to create a better style for displaying tables in ExDoc. I will submit a feature request later.

### CODE REVIEW

**Comment by josevalim** [comment]
Good catch! I would like to fix both IEx and ExDoc first before going ahead with this change than. :)

**Comment by eksperimental** [comment]
I will submit two different PRs then fixing this issue (i just need to write the tests). And the feature request to ExDoc. We mostly need graphic designer or someone with good taste (not me!) to choose colors for the alternating rows

**Comment by eksperimental** [comment]
Last commit add clarity to the tables.

image

image

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
