### PR TITLE
Use proper case for Erlang error messages

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
Error messages start in lower case. Maybe the mistake here is that the error message is horribly succinct "erlang error" but the casing is definitely correct. :)

**Comment by eksperimental** [comment]
Well, I understand that, but in any case it is not proper to write a proper noun in lowercase.
What I thought of this rule was that the Exception is the beggining of the sentecen, therefore it should not be in uppercase whatever comes after, but since it's a proper noun it should be.

**Comment by josevalim** [comment]
Oh, I see what you mean. Yeah, this is good to go.

**Comment by whatyouhide** [comment]
👍

**Pull request merged**
