### PR TITLE
Remove trailing commas in templates

### PR DESCRIPTION
**Pull request by fertapric**
I think there are pros and cons about trailing commas, but this change is consistent with the formatter.

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
May I ask what are the pros.

**Comment by eksperimental** [comment]
Sorry, I meant what are the cons

**Comment by OvermindDL1** [comment]
> Sorry, I meant what are the cons

Inconsistency with the existing formatter style?  I honestly don't see cons with using trailing commas on element-by-line list/tuple/arg/map formatting personally, but do see lots of pros.

**Pull request merged**
