### PR TITLE
Use "operating system" instead of OS

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
My thought process was that operating system is vague so putting them in title case would make it clear we are talking about THE operating system. But I don't know if this is only me.

Another operation is "operating system (OS)".

Thoughts?

**Comment by eksperimental** [comment]
> Another option is "operating system (OS)".
I like this, but only for the documentation for functions with the "os" acronym

**Comment by josevalim** [comment]
Sounds good to me then! :D

**Comment by eksperimental** [comment]
pushed, also check the last commit

**Pull request merged**
