### PR TITLE
Print multiple clause erlang docs

### PR DESCRIPTION
**Pull request by sabiwara**
Just a draft for discussion, I'm not sure if we should actually support this.

According to [Lukas](https://github.com/erlang/otp/issues/7501#issuecomment-1637526249), multiple clauses of the same function might have a separate spec and doc.

Right now, due to the use of `Enum.find/2`, we're just showing the doc for the first clause:

Screenshot 2023-07-17 at 18 02 24

With this PR:

Screenshot 2023-07-17 at 18 02 34

Ideally, we'd probably want to intersperse specs and docs (`@spec halt(status,`, doc, `@spec halt(abort,`, doc...) like erlang shell does, but this is a bigger change due to the fact we're currently extracting specs separately. I'd be happy to keep looking into it, but I first wanted to confirm the desired behavior.

### CODE REVIEW

**Comment by sabiwara** [comment]
OK yeah that should work: https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/code/typespec.ex#L128

**Comment by garazdawi** [comment]
If you want to make life easier for yourself, you could just call [shell_docs:render/3](https://www.erlang.org/doc/man/shell_docs.html#render-2), but then you will not get the specs written with Elixir syntax.

**Comment by josevalim** [comment]
I am totally fine with rendering using Erlang syntax and APIs. It will be closer to what users will see on the website anyway.

**Comment by sabiwara** [comment]
Current (`:erlang.abs/1`):
Screenshot 2023-07-17 at 20 38 33

If we go with `:shell_docs`:

Screenshot 2023-07-17 at 20 38 44

I think it would look OK, just might be slightly harder for beginners without the familiar syntax.

```elixir
{:ok, d} = :code.get_docs(:erlang)
:shell_docs.render(:erlang, :abs,  d) |> IO.puts()
```

Will open a different branch, since I almost got it working with the Elixir formatted specs on this one.

**Comment by josevalim** [comment]
All Erlang examples are already in Erlang and we may not even support typespecs in a couple years time, so let’s move to Erlang rendering :)

**Comment by sabiwara** [comment]
Closing in favor of https://github.com/elixir-lang/elixir/pull/12803

**Comment by sabiwara** [comment]
> If you want to make life easier for yourself, you could just call [shell_docs:render/3](https://www.erlang.org/doc/man/shell_docs.html#render-2), but then you will not get the specs written with Elixir syntax.

Hi @garazdawi, sorry to ping you now, but would you have any thought on https://github.com/elixir-lang/elixir/pull/13352?

**Pull request closed without merging**
