### PR TITLE
Support SOURCE_DATE_EPOCH for reproducible builds

### PR DESCRIPTION
**Pull request by josevalim**
See #8689.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
Using `SOURCE_DATE_EPOCH` is one common approach, that will work fine.
Another is using the date of last git commit and falling back to ChangeLog file mtime if the git tree is unavailable:
https://github.com/ntop/nDPI/pull/662

**Comment by eksperimental** [comment]
Changelog will not work, because it gets updated in chunks

**Comment by josevalim** [comment]
Plus not all changes go to the CHANGELOG, such as documentation improvements. Also, if git is not available, we would need a fallback, so i think SOURCE_DATE_EPOCH is the way to go.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
