### PR TITLE
Function for comparing terms by order

### PR DESCRIPTION
**Pull request by lpil**
Hello!

After some chatter in the slack channel I thought it would be useful to have a compare function for general terns as well as for versions and logger levels.

I wasn't sure where a function such as this would live. My first two thoughts were:

- `Kernel.compare/2`
- `Order.compare/2`

The former doesn't work so well as it would conflict with any functions people have defined called `compare` in their own modules.

I wasn't sure about creating a new module just for this. This option seemed popular with those I spoke to in the channel.

What do you think of this function? And where ought I place it if it's something that would be wanted in Elixir?

Cheers,
Louis

### CODE REVIEW

**Comment by antipax** [comment]
What use case do you have in mind for this function?

**Comment by josevalim** [comment]
Please send feature proposals to the core mailing list. :)

On Thursday, June 30, 2016, Louis Pilfold <notifications@github.com> wrote:

> Hello!
>
> After some chatter in the slack channel I thought it would be useful to
> have a compare function for general terns as well as for versions and
> logger levels.
>
> I wasn't sure where a function such as this would live. My first two
> thoughts were:
>
>    - Kernel.compare/2
>    - Order.compare/2
>
> The former doesn't work so well as it would conflict with any functions
> people have defined called compare in their own modules.
>
> I wasn't sure about creating a new module just for this. This option
> seemed popular with those I spoke to in the channel.
>
> What do you think of this function? And where ought I place it if it's
> something that would be wanted in Elixir?
>
> Cheers,
> Louis
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/elixir-lang/elixir/pull/4912
> Commit Summary
>
>    - compare_order function
>
> File Changes
>
>    - *M* lib/elixir/lib/kernel.ex
>    <https://github.com/elixir-lang/elixir/pull/4912/files#diff-0> (26)
>
> Patch Links:
>
>    - https://github.com/elixir-lang/elixir/pull/4912.patch
>    - https://github.com/elixir-lang/elixir/pull/4912.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/pull/4912>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbrhpvrGJZQWErT5BoiZUj8CDLtwhks5qQ9GUgaJpZM4JCNq4>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by lpil** [comment]
This sort of thing:

```elixir
 case compare(x, y)
  :eq -> something()
  :lt -> another()
  :gt -> one_more()
end
```

Ah, I always forget the mailing list exists. I'll do that now.

**Comment by josevalim** [comment]
@lpil but you can also write it as `cond do foo > bar ->...; foo < bar -> ...; true -> end` and so on. My biggest concern is that we would have two ways of doing the same thing and I don't think this approach deserves a function in Kernel or a new model.

I am closing this until we get the mailing list feedback. :)

**Pull request closed without merging**
