### PR TITLE
Suppress warnings by adding `Keyword.*_lazy` functions

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by lexmag** [comment]
The implementation is really straightforward, but I'm still curious:

> let's implement manually because the implementation will certainly be faster than the one in Dict (since we can specialize it here)

@josevalim is that really so performance sensitive that we can't use `use Dict`?
Correct me if I'm wrong, but we still can have overrided default callbacks with it; `get`, `get_lazy`, `fetch!`, `pop`, `pop_lazy` functions are almost the same as `Dict` defaults (it's additional `case` to the `:lists.keyfind/3`).

And as it's been said on IRC: "you shouldn't have a big keyword list anyway". :smile: 

I can run benchmarks if there is a need for it.

**Comment by josevalim** [comment]
The dict implementation traverses twice. Which is necessary when we don't have underlying access to the dict representation but that is not the case here.

Functions in the standard library needs to be as fast as they can. Imagine how many times keyword list functions are invoked in applications? We need to worry about performance so everyone else need to worry less.

**Comment by lexmag** [comment]
Let me clarify my point.
For instance, `Keyword.get/2`
```elixir
case :lists.keyfind(key, 1, keywords) do
  {^key, value} -> value
  false -> default
end
```
and `Dict.get/2`
```elixir
case fetch(dict, key) do
  {:ok, value} -> value
  :error -> default
end
```
are almost the same since `Keyword.fetch/2` is
```elixir
case :lists.keyfind(key, 1, keywords) do
  {^key, value} -> {:ok, value}
  false -> :error
end
```
It is true for `get`, `get_lazy`, `fetch!`, `pop`, `pop_lazy` and probably more functions in `Keyword`.

**Comment by josevalim** [comment]
@lexmag for get, get_lazy, fetch! it makes sense. It doesn't make sense for pop or pop_lazy though. They can (and should) be written in faster ways.

**Comment by lexmag** [comment]
Agree, it's not the case for `pop`, `pop_lazy`, but it is for `put_new` and `put_new_lazy`. I would like to make a new PR with that change and move discussion there if you agree.
Anyway, that PR is ready for merge, the only question is shall we have lazy version of the `Keyword.pop_first/3`?

**Comment by josevalim** [comment]
> Agree, it's not the case for pop, pop_lazy, but it is for put_new and put_new_lazy.

The current put_new implementation in Keyword is also faster than the one in Dict. That's because Keyword.put deletes all matching keys so calling .get and .put for the case there is no key ends-up traverse the listing twice in the Dict implementation applied to Keyword.

> I would like to make a new PR with that change and move discussion there if you agree.

Yes, the PR is welcome, but I think we will be able to use it only in the fetch/get related functions. :)

**Comment by josevalim** [comment]
Btw, no tests for pop_lazy? :)

**Comment by lexmag** [comment]
> no tests for pop_lazy? :)

Following the tradition with `pop` tests. :)
Actually, `Keyword` has a decent test coverage via doctests, but, of course, no harm to bring even more.

**Comment by josevalim** [comment]
Forgot about the doctests. :)

**Comment by lexmag** [comment]
> the only question is shall we have lazy version of the `Keyword.pop_first/3`?

**Comment by josevalim** [comment]
I wouldn't worry about it until someone needs it.

**Comment by lexmag** [comment]
Good. :smile:

**Pull request merged**
