### PR TITLE
IEx helpers: port and reference should be in lowercase

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
Why should they be in lowercase? Not that I disagree, just trying to understand the rationale. :)

**Comment by josevalim** [comment]
So we keep it as "PID" above because it is an abbreviation?

**Comment by eksperimental** [comment]
> So we keep it as "PID" above because it is an abbreviation?
yes, plus it is the standard across the code base. `pid` is only used for arguments.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
