### PR TITLE
Add Version.parse_requirement!/1

### PR DESCRIPTION
**Pull request by wojtekmach**
Similar to #4426.

### CODE REVIEW

**Comment by josevalim** [comment]
@wojtekmach should we change places like [this](https://github.com/elixir-lang/elixir/blob/87b056e79d510498bd61578f771bf78ae002c47e/lib/elixir/lib/version.ex#L168) to use the raising variant now?

**Comment by wojtekmach** [comment]
Good call, I’ll do it.

**Comment by wojtekmach** [comment]
We have a doctest :)

**Comment by ericmj** [comment]
Good point :)

**Pull request merged**
