### PR TITLE
Throw syntax error for `:foo.Bar`

### LINKED ISSUE #2986: Raise syntax error on :foo.Bar

### PR DESCRIPTION
**Pull request by oneeman**
Closes #2986 (I think)

I wasn't too sure if this was the right place for the test, and whether to include both tests or just one (or more than two).

### CODE REVIEW

**Comment by eksperimental** [comment]
could this be useful?

```diff
diff --git a/lib/elixir/test/erlang/atom_test.erl b/lib/elixir/test/erlang/atom_test.erl
index ea78e7c..7853a38 100644
--- a/lib/elixir/test/erlang/atom_test.erl
+++ b/lib/elixir/test/erlang/atom_test.erl
@@ -28,7 +28,8 @@ kv_with_interpolation_test() ->
 
 quoted_atom_test() ->
   {foo,[]} = eval(":\"foo\""),
-  {foo,[]} = eval(":'foo'").
+  {foo,[]} = eval(":'foo'"),
+  {'foo.Bar',[]} = eval(":\"foo.Bar\"").
 
 atom_with_interpolation_test() ->
   {foo,[]} = eval(":\"f#{\"o\"}o\""),
```

**Comment by oneeman** [comment]
Sorry, I realized I wasn't following the precedent in the parser of having the errors grouped together at the end.  Will see if I can bring it closer in line, marking the PR as WIP for now.

**Comment by josevalim** [comment]
@oneeman Yes, we just need to add throw_bad_atom or something. Also, can we start the error message with lowercase and move the test case to atom_test.erl? Thanks a lot! :heart:

**Comment by josevalim** [comment]
@eksperimental please send those assertions as another pull request if they don't exist there today!

**Comment by oneeman** [comment]
@josevalim Terrific, I did those and amended it.   I was thinking it might be nice to detect the error from the grammatical rules like the other cases there which throw errors, but my yacc/yecc skills are practically nil.

**Comment by oneeman** [comment]
@josevalim Could the test for this error be more at home in `lib/elixir/test/elixir/kernel/errors_test.exs`?  I ran across it while browsing and saw that's where other syntax error tests seem to be.

**Comment by josevalim** [comment]
Good call, certainly! Can you please send a pull request migrating it?

**Comment by oneeman** [comment]
Will do :-)

**Pull request merged**
