### PR TITLE
Fix escript on windows

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by josevalim** [comment]
@xiamx ok, I have more news. The issue happens exclusively with `test_mix`. Probably because we are starting processes in Mix test suite and those are not terminating, causing the whole thing to hang. Can you reproduce this in your machine?

**Comment by josevalim** [comment]
Here is tasklist on CI: https://ci.appveyor.com/project/josevalim/elixir/build/1-master+55

Notice that are two hanging erl.exe in there.

**Comment by josevalim** [comment]
I have added a taskkill and it works! While it would be best to find what is causing the leakage, it should be enough as an intermediate fix so the build is green.

**Comment by xiamx** [comment]
wow nice!

**Comment by josevalim** [comment]
Thank you, this wouldn't have been possible without yours and @robi-wan's help!

**Pull request merged**
