### PR TITLE
Update Unicode to version 13.0.0

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you so much! Btw, you can submit a similar PR to Erlang/OTP: https://github.com/erlang/otp/commit/6e20fe67e6e4e86a681fdb9fc1f24589f0e07252

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by eksperimental** [comment]
> Thank you so much! Btw, you can submit a similar PR to Erlang/OTP: [erlang/otp@6e20fe6](https://github.com/erlang/otp/commit/6e20fe67e6e4e86a681fdb9fc1f24589f0e07252)

You are welcome!
Yes, I will give it a go

**Comment by eksperimental** [comment]
@josevalim do you think it can also make it to v1.12?

**Comment by josevalim** [comment]
I would rather not given OTP will likely stay within 12.1.

**Comment by eksperimental** [comment]
> I would rather not given OTP will likely stay within 12.1.

Sorry, just out of curiosity, and probably for future updates in the Unicode module, what is the rationale here to be on a par with the latest OTP release and not past?

**Comment by josevalim** [comment]
It is not a strong reason to not update but there is no reason to rush. :)

**Comment by eksperimental** [comment]
> Thank you so much! Btw, you can submit a similar PR to Erlang/OTP: [erlang/otp@6e20fe6](https://github.com/erlang/otp/commit/6e20fe67e6e4e86a681fdb9fc1f24589f0e07252)

I am done, but i want to run the tests before submitting the PR.
based on https://github.com/erlang/otp/blob/master/HOWTO/TESTING.md#short-version
Could you please tell me how to run the tests only for Unicode?

**Comment by josevalim** [comment]
From OTP root:

```
$ export ERL_TOP=$PWD
$ export PATH=$ERL_TOP/bin:$PATH
$  ./otp_build all -a && ./otp_build tests
$ cd release/test/test_server
$ erl
erl> ts:install().
erl> ts:run(stdlib, unicode_SUITE, [batch]).
```

**Comment by eksperimental** [comment]
> From OTP root:
> 
> ```
> $ export ERL_TOP=$PWD
> $ export PATH=$ERL_TOP/bin:$PATH
> $  ./otp_build all -a && ./otp_build tests
> $ cd release/test/test_server
> $ erl
> erl> ts:install().
> erl> ts:run(stdlib, unicode_SUITE, [batch]).
> ```

Awesome, All tests passed. I am submitting it.
There is a type in one line, it should read.
`$ cd release/tests/test_server`

**Comment by eksperimental** [comment]
> Thank you so much! Btw, you can submit a similar PR to Erlang/OTP: [erlang/otp@6e20fe6](https://github.com/erlang/otp/commit/6e20fe67e6e4e86a681fdb9fc1f24589f0e07252)

PR submitted https://github.com/erlang/otp/pull/4707

**Pull request merged**
