### PR TITLE
Force System.build_info()[:revision] to be 7 char long max

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by ericmj** [comment]
Should we remove the `--short` flag if we want to force 7 char commit hashes? I think gitconfig can change it to shorter as well.

**Comment by fertapric** [comment]
Could `--short=7` be a good compromise? In most cases, the revision will be 7 characters long, exceeding that number just in case of collisions.

**Comment by eksperimental** [comment]
> Could `--short=7` be a good compromise? In most cases, the revision will be 7 characters long, exceeding that number just in case of collisions.

I think this is the way to go

**Comment by whatyouhide** [comment]
I'm ok with the change, but what's the rationale behind it? I would also love to have this added to the commit message.

**Comment by ericmj** [comment]
> I'm ok with the change, but what's the rationale behind it?

Git is not always consistent in the length of their short hashes, repos with large histories will have longer hashes and users can override the size of short hashes. This change attempts to make it more consistent.

**Comment by whatyouhide** [comment]
Thanks @eksperimental! 💟

**Pull request merged**
