### PR TITLE
Select certain command-line arguments from a restricted set of values

### PR DESCRIPTION
**Pull request by milmazz**
Sometimes you want to select certain command-line arguments from a restricted set of values, assume for a moment that we want to play Rock–paper–scissors. So, there is a restricted set of values for the argument `--move`.

The current behavior from `OptionParser` does not allow to filter some values:

```elixir
iex(1)> OptionParser.parse(["--move", "rock"], switches: [move: :string])
{[move: "rock"], [], []}
iex(2)> OptionParser.parse(["--move", "scissors"], switches: [move: :string])
{[move: "scissors"], [], []}
iex(3)> OptionParser.parse(["--move", "bacon"], switches: [move: :string])
{[move: "bacon"], [], []}
```

This proposal includes the `choices` option, which allow us to select the command-line arguments based on a restricted set of values:

```elixir
iex(4)> OptionParser.parse(["--move", "rock"], switches: [move: :choices], choices: [move: ["rock", "paper", "scissors"]])
{[move: "rock"], [], []}
iex(5)> OptionParser.parse(["--move", "bacon"], switches: [move: :choices], choices: [move: ["rock", "paper", "scissors"]])
{[], [], [{"--move", "bacon"}]}
```

This also work with ranges or list of integers:

```elixir
iex(6)> OptionParser.parse(["--door", 1], switches: [move: :choices], choices: [door: 1..4])
{[door: 1], [], []}
```

If we use `OptionParser.parse!/2` we should get an exception in case of an invalid value:

```elixir
iex(7)> OptionParser.parse!(["--move", "bacon"], switches: [move: :choices], choices: [move: ["rock", "paper", "scissors"]])
** (OptionParser.ParseError) 1 error found!
--move : Invalid choice bacon, choose from: rock, paper, scissors
    (elixir) lib/option_parser.ex:244: OptionParser.parse!/2
```

This commit also includes some minor refactoring in `OptionParser` to reduce the number of parameters in some functions.

### CODE REVIEW

**Comment by whatyouhide** [comment]
Is this really a concern of `OptionParser` though? For example, say I want to accept a path to an existing file. Should we provide also `:existing_file` as a type then? When do we stop? 🤔

**Comment by lexmag** [comment]
I share @whatyouhide's concern on that patch.
Also it actually won't work with integers since `["--door", 1]` is not a valid input.

**Comment by milmazz** [comment]
> Is this really a concern of OptionParser though? 

@whatyouhide I believe so, I have seen this behavior in other programming languages, for example with `argparse` in Python or `Getopt::Declare` (I don't recall if you can do the same with `Getopt::Long`) in Perl. I haven't check yet, but maybe you can do the same with `optparse-applicative` in Haskell. To sum up, you can reject a command-line argument value base on a set of values in those modules.

Also, with this option, we normalize the message error when a value for a command-line argument is invalid given a restricted set of values.

**Comment by whatyouhide** [comment]
I am still 👎 on adding this.

```elixir
if options[:some_option] not in ["foo", "bar", "baz"] do
  Mix.raise "--some-option must be one of \"foo\", \"bar\", \"baz\""
end
```

seems very straightforward to implement correctly and gives all the flexibility you need in how you handle which values for the option are allowed for example. I believe this would complicate an already not-so-simple API (`OptionParser`) with concerns that can easily be pushed to application level.

**Comment by josevalim** [comment]
There would be one reason for supporting this: if we automatically generated help based on the arguments description. It is something we planned to do but never happened. Given the current situation of the option parser, I am also :-1: on this feature.

Thank you @milmazz!

**Comment by milmazz** [comment]
@josevalim @whatyouhide No worries about the `choices` option, that's normal in the OSS. But, are you interested in the refactoring that I made (reduce the number of parameters in some functions in `OptionParser`)? I can create another PR with that if you want.

@josevalim BTW, I was also thinking on the *generated help` feature in `OptionParser`, do you have any advice on how the API should be?

**Comment by josevalim** [comment]
No idea on the API, that's part of the work that needs to be done. :)

**Pull request closed without merging**
