### PR TITLE
Run formatter on Logger.Translator

### PR DESCRIPTION
**Pull request by devonestes**

### CODE REVIEW

**Comment by whatyouhide** [comment]
Can you please check if the error in the build was caused by this PR?

**Comment by devonestes** [comment]
All fixed!

**Comment by josevalim** [comment]
This is a tricky one. I wonder if those would look better if we use `++`. Instead of:

```elixir
msg = [
  "Child ",
  inspect(name),
  " of Supervisor ",
  sup_name(sup),
  ?\s,
  sup_context(context),
  "\n** (exit) ",
  offender_reason(reason, context)
  | child_info(min_level, offender)
]
```

we would do:

```elixir
msg =
  ["Child ", inspect(name), " of Supervisor ", sup_name(sup), ?\s] ++
    [sup_context(context), "\n** (exit) ", offender_reason(reason, context)] ++
    child_info(min_level, offender)
```

It takes less space and I find it much easier to read.

Thoughts?

**Comment by devonestes** [comment]
I don't have strong feelings either way. If you find it much easier to read, then that's enough for me to think that's a good change. I'll give it a whirl.

**Comment by josevalim** [comment]
@devonestes I am also on the fence so, if you haven't started yet, let's wait for @whatyouhide's feedback too.

**Comment by whatyouhide** [comment]
I like @josevalim's suggestion, I hadn't thought about it but it's a great idea.

**Comment by devonestes** [comment]
Cool - well this is ready for another review then!

**Pull request merged**
