### PR TITLE
Make string split with an empty string consistent with replace

### PR DESCRIPTION
**Pull request by josevalim**
To go with #6559. /cc @lexmag

### CODE REVIEW

**Comment by michalmuskala** [comment]
How does empty regex compare to empty string after the changes?

**Comment by josevalim** [comment]
@michalmuskala you are correct it is inconsistent with regexes. 😩

**Comment by whatyouhide** [comment]
What are some good properties we can come up with for `String.split`?

**Comment by josevalim** [comment]
@whatyouhide I think at this point the inconsistency with regex split, which is pretty much unsolvable, leaves our hands tied, regardless of properties.

**Pull request closed without merging**
