### PR TITLE
Use implicit try where possible.

### PR DESCRIPTION
**Pull request by michalmuskala**
Also, use a standard order in try with else clauses after catch/rescue

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you @michalmuskala! Although I would agree this makes things consistent, we are generally :-1: on this kind of pull requests because we lose the history on those lines. So while someone could refactor the code if changing the same lines, we should avoid doing so on its own.

**Comment by lpil** [comment]
Oh wow- I'd no idea you could do that. Thanks :)

**Comment by eksperimental** [comment]
I had no idea either, 
this should definitely be documented!

**Comment by michalmuskala** [comment]
I can totally understand that @josevalim, and I was aware of this rule.

One of the reasons I went for it anyway was exactly the fact that not many people know about this, and in many contexts the elixir source code is recommended as a great material to learn elixir.

**Comment by lexmag** [comment]
I feel 👎 on this change since it affects history, and explicitness is not a bad thing after all. :bowtie:

**Pull request closed without merging**
