### PR TITLE
Update Unicode to 16.0.0

### PR DESCRIPTION
**Pull request by maintenance-beam-app**
This is an automated commit generated by the Maintenance project.
https://github.com/eksperimental/maintenance

If you find any issue in this PR, please kindly report it to
https://github.com/eksperimental/maintenance/issues

### CODE REVIEW

**Comment by eksperimental** [comment]
> New Data Files for Unicode 16.0
> 
> DoNotEmit.txt. This is a new file that collects information about characters or character sequences that should not be emitted or generated in newly authored text and for which a suitable alternative sequence exists. This data could be used by applications such as input methods or autocorrect.
> Unikemet.txt. This data file provides property and other character information in support of Egyptian hieroglyphs.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by eksperimental** [comment]
@kipcole9  you might be interested

**Comment by kipcole9** [comment]
Thanks @eksperimental, much appreciated. I track this repo so I saw the automated message - very cool. I updated my Unicode libs in September when Unicode 16 was released so everything there is also up-to-date.

**Comment by eksperimental** [comment]
@josevalim just stopping to tell you to look at this comment, https://github.com/erlang/otp/pull/9141#issuecomment-2694069023
and see if `IndicSyllabicCategory.txt` and the changes in https://github.com/erlang/otp/pull/9518 are required in Elixir.

**Comment by josevalim** [comment]
Thank you! We delegate that functionality to Erlang, so we are good :)

**Pull request merged**
