### PR TITLE
Enum.chunk/2: improve function guard

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by ericmj** [comment]
I think we discussed this already? `chunk/4` has the function guard.

**Comment by ericmj** [comment]
Reference: https://github.com/elixir-lang/elixir/pull/4990

**Comment by eksperimental** [comment]
oh.. shoot, i was cleaning out my local git repos. and i see this one was not merged.
totally overlooked it. my short-term memory is failing.
too many repos i guess. :-P

**Comment by ericmj** [comment]
No worries :)

**Pull request closed without merging**
