### PR TITLE
Implement Inspect for DateTime

### PR DESCRIPTION
**Pull request by wojtekmach**

### CODE REVIEW

**Comment by lau** [comment]
This hides the fields in the struct. For UTC ones it isn't as bad.

For the other time zones: You can't see what `std_offset` and `utc_offset` is. What's wrong with having it just show the map as today?

Maybe it should be documented that to "inspect" a struct you can pipe it to delete :__struct__ : `|> Map.delete(:__struct__)` Is there a function for doing this? If someone is looking at a log and want to know what the data looks like, sometimes they might want to know all of the details.

**Comment by josevalim** [comment]
@lau you can do `inspect(data, structs: false)`.

If you think the proposed implementation is correct though, then I think we should merge this, as today's representation is quite verbose. Imagine for example when you load a bunch of Ecto structs, the verbose DateTime representation really gets in the way.

**Comment by wojtekmach** [comment]
FWIW we do see the offset in the proposed implementation, but yeah we don't distinguish between `std_offset` and `utc_offset`, but the same is true for `to_string` implementation.

btw, another shortcut is `|> Map.from_struct`

**Comment by lau** [comment]
Cool. Yeah it looks good to me in being correct. Nice work. :shipit: 

I agree the trade off (lack of verbosity vs detailed information) makes sense in many cases.

Perhaps `inspect(data, structs: false)` is a good thing for people to also try if they are debugging non-UTC DateTimes. And the use of `inspect(a_date_time, structs: false) in combination with DateTime could be added to the docs somewhere.

**Comment by lau** [comment]
If there are two `DateTime`s with different calendars how can you tell the difference? For `NaiveDateTime` the inspect implementation is limited to`https://github.com/elixir-lang/elixir/blob/6aeea8a0ea12f28f904ab5870d8b8970fd49ffc2/lib/elixir/lib/calendar/naive_datetime.ex#L655`. https://github.com/elixir-lang/elixir/blob/6aeea8a0ea12f28f904ab5870d8b8970fd49ffc2/lib/elixir/lib/calendar/naive_datetime.ex#L655

Should this also be limited to `Calendar.ISO`?

**Comment by wojtekmach** [comment]
> Should this also be limited to Calendar.ISO?

Good catch, I agree this is how it should be, will fix.

An idea for future improvements is to maybe have:
- `#DateTime<2016-05-24 13:26:08Z>` for ISO
- `#DateTime<2016-05-24 13:26:08Z (Calendar.Julian)>` for non-ISO
- `~D[2017-01-01]` for ISO
- `#Date<2017-01-01 (Calendar.Julian)>` for non-ISO
etc

**Comment by josevalim** [comment]
Great catch @lau. Let's go with only the iso calendar for now.

**Pull request merged**
