### PR TITLE
Implement Map.take_in/2

### PR DESCRIPTION
**Pull request by samuelmanzanera**
Support of Map.take_in/2 to extract values using nested keys (recursively).

I think it may be useful when you only want a part of the map -- mostly when its deep nested map (i.e KV stores, DB engines, etc..) to reduce memory footprint with copy and message passing.

### CODE REVIEW

**Comment by whatyouhide** [comment]
Hey @samuelmanzanera, has this been proposed through the elixir-lang-core mailing list first? As we explain [on the website](https://elixir-lang.org/development.html), we reserve the issue tracker for bugs and we tend to not accept features that haven't been thoroughly discussed first. An immediate problem I see with this is that it would need to be a generic mechanism based on `Access` like `get_in` or `update_in` and not specific to maps. Thanks!

**Comment by josevalim** [comment]
I initially like this proposal, so please send it through the mailing list. We also need to discuss details such as what happens if you ask to take from something that is not a map. The current implementation ignores them but it may be better to raise. We would also have to implement the same functionality for keywords.

My only concern is that this functionality can be quite inefficient compared to pattern matching. For example, instead of:

    iex> Map.take_in(%{a: 1, b: %{c: 10, d: %{e: 5, f: 3}}}, [b: [:c, d: [:f]]])
    %{b: %{c: 10, d: %{f: 3}}}

I could do:

    iex> %{b: %{c: c, d: %{f: f}}} = %{a: 1, b: %{c: 10, d: %{e: 5, f: 3}}}
    iex> %{b: %{c: c, d: %{f: f}}}
    
But I am not sure at the moment about how to avoid the duplication - but it is something worth keeping in mind.

**Comment by josevalim** [comment]
Closing pending the ML discussion. :)

**Comment by samuelmanzanera** [comment]
Thanks for you replies.

One thing the pattern matching cannot achieve (as far as I know) it's for an example like this one
```elixir
iex> %{a: a, b: %{d: d}} = %{a: "hello", b: %{c: "hi", d: "hola"}}
%{a: "hello", b: %{c: "hi", d: "hola"}}
```

Instead with Map.take_in
```elixir
iex> Map.take_in(%{a: "hello", b: %{c: "hi", d: "hola"}}, [:a, b: [:d]])
%{a: "hello", b: %{d: "hola"}}
```

The `c`is well excluded as the expected filtered keys.

Pattern matching of course can be more efficient but include some data not expected/desired.

> The current implementation ignores them but it may be better to raise
Actually the implementation raise if it's not a map but the Keyword implemention can be nice also

Integrate it inside Access may be prefered than duplicate Map and Keyword implementation. (Didn't think about it @whatyouhide)

I will include the proposition in the mailing list as asked. Thanks

**Comment by josevalim** [comment]
> One thing the pattern matching cannot achieve (as far as I know) it's for an example like this one

You have to repeat the pattern after matching it:

    iex> %{a: a, b: %{d: d}} = %{a: "hello", b: %{c: "hi", d: "hola"}}
    iex> %{a: a, b: %{d: d}}
    %{a: "hello", b: %{d: "hola"}}

Which is an annoyance but something that we could try to tackle.

**Comment by samuelmanzanera** [comment]
> > One thing the pattern matching cannot achieve (as far as I know) it's for an example like this one
> 
> You have to repeat the pattern after matching it:
> 
> ```
> iex> %{a: a, b: %{d: d}} = %{a: "hello", b: %{c: "hi", d: "hola"}}
> iex> %{a: a, b: %{d: d}}
> %{a: "hello", b: %{d: "hola"}}
> ```
> 
> Which is an annoyance but something that we could try to tackle.

Thanks sorry my bad!

**Pull request closed without merging**
