### PR TITLE
Enhance difference highlighting for lists

### PR DESCRIPTION
**Pull request by lexmag**
Make it recursive and element-aware, it also should be faster than difference for their `inspect`ed representation (especially when difference is big).

### CODE REVIEW

**Comment by josevalim** [comment]
Btw, unrelated to this issue but related to the feature, should we inspect strings before calculating the diff on them? Otherwise we get differences like below. Also the differences may be on the use of \t instead of \s and those would be hard to catch without inspecting.

screen shot 2016-04-09 at 14 32 31

**Comment by michalmuskala** [comment]
I just looked at the diff @josevalim pasted and started wondering:
Wouldn't be better to use a different color for deletions? The red blends in with headers from the error itself, and using something different would make it stand out more. I needed to search the diff for a while before realizing where the issue was. Alternatively we could use different color for the headers and keep the red for deletions.

**Comment by josevalim** [comment]
We could make all of them blue in the same color as stacktraces?

**Comment by whatyouhide** [comment]
I'm :+1: on making them the same color as `stacktrace: `.

**Comment by lexmag** [comment]
Agree the `stacktrace` color could look better:

screen shot 2016-04-10 at 12 06 21

**Comment by whatyouhide** [comment]
Looks marvelous this way :heart_decoration:

**Comment by michalmuskala** [comment]
This is much better!

**Comment by josevalim** [comment]
:shipit:

**Pull request merged**
