### PR TITLE
Build info

### PR DESCRIPTION
**Pull request by eksperimental**
* System.build_info/0: add :build and improve tests
* Use System.build_info[:build] consistently in Mix and Elixir

It depends on changes introduces by https://github.com/elixir-lang/elixir/pull/4313 and https://github.com/elixir-lang/elixir/pull/4314

### CODE REVIEW

**Comment by eksperimental** [comment]
T

**Comment by eksperimental** [comment]
There I go with three different PRs, I had to include the commits from the other PRs since it relies on those changes, so I didn't know what was the best way to deal with this.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
This is perfect @eksperimental! Thank you so much! I have merged all three of them in order and this helped a lot in the review process. :heart_eyes:

**Pull request merged**
