### PR TITLE
Update CI to test on Erlang/OTP 27.0

### PR DESCRIPTION
**Pull request by michallepicki**

### CODE REVIEW

**Comment by josevalim** [comment]
It seems it is not yet available on setup-beam, I am not sure if explicit action is needed from them. :)

**Comment by michallepicki** [comment]
Whoops, sorry about that! I saw 27.0 on [one of hexpm/bob 's lists ](https://builds.hex.pm/builds/otp/arm64/ubuntu-24.04/builds.txt) but didn't think it's not on all of them yet.

**Comment by michallepicki** [comment]
Actually it is already on [the 20.04 list](https://builds.hex.pm/builds/otp/arm64/ubuntu-20.04/builds.txt) so you may be right that maybe setup-beam needs to support this version as well.

**Comment by michallepicki** [comment]
Apparently I had linked the arm64 list. TIL bob builds on ARM as well now. Here is the [amd64 20.04 list](https://builds.hex.pm/builds/otp/amd64/ubuntu-20.04/builds.txt), 27.0 is not there yet

**Comment by ericmj** [comment]
@michallepicki Can you reopen the PR? It's available now.

**Comment by ericmj** [comment]
Thank you!

**Pull request merged**
