### PR TITLE
Enhance difference highlighting for tuples

### PR DESCRIPTION
**Pull request by lexmag**
Make it recursive and element-aware, it also should be faster than difference for their inspected representation (especially when difference is big).

### CODE REVIEW

**Comment by lexmag** [comment]
@ericmj, your Tuesday example should have much better diff with this patch.

__From:__
screen shot 2016-04-11 at 01 16 58
__To:__
screen shot 2016-04-11 at 01 16 02

**Comment by josevalim** [comment]
Beautiful. Btw, I think we should probably move the code to `ExUnit.Diff.format/3`, and break the current test into smaller tests, since we have been expanding it bit by bit!

**Comment by lexmag** [comment]
Agree, at its current state it deserves its own place.

**Comment by lexmag** [comment]
The moving `ExUnit.Diff` is coming.

**Pull request merged**
