### PR TITLE
Replace Keyword.t/0-1 types with built-in keyword/0-1

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
There is one issue,

https://github.com/elixir-lang/elixir/blob/5319756/lib/elixir/lib/kernel.ex#L3809
if I change that line
`@spec exception(Keyword.t) :: Exception.t`

for 
`@spec exception(keyword) :: Exception.t`

I will get an error,
```
  1) test no warnings on raise (Kernel.DialyzerTest)
     test/elixir/kernel/dialyzer_test.exs:67
     raise.ex:2: Overloaded contract for 'Elixir.Dialyzer.Raise':exception/1 has overlapping domains; such contracts are currently unsupported and are simply ignored

     stacktrace:
       test/elixir/kernel/dialyzer_test.exs:69: (test)
```

it looks like that spec is overlapping with this one
https://github.com/elixir-lang/elixir/blob/5319756/lib/elixir/lib/kernel.ex#L3803
`@spec exception(String.t) :: Exception`

but I cannot figure out why it should.

**Comment by josevalim** [comment]
@eksperimental is `Dialyzer.Raise` defining its own specs by any chance?

**Comment by eksperimental** [comment]
the only specs are defined by calling `defexception`
https://github.com/elixir-lang/elixir/blob/5319756/lib/elixir/test/elixir/fixtures/dialyzer/raise.ex

**Comment by fishcakez** [comment]
The reason for the overlapping domains is that `keyword/0` is rewritten to the `:elixir` exported type and `:elixir` is not in the PLT and so `dialyzer` does not know the type causing it to use `any()`. `binary()` is a subset of `any()` so there are overlapping domains.

From OTP 18 / dialyzer 2.8+ unknown function/type warnings are not enabled by default. It can be turned on with `[warnings: [:unknown]]` to `:dialyzer.run/1`. It might be that we can remove `Keyword` from the PLT also.

**Comment by eksperimental** [comment]
@fishcakez Thank you so much for the explanation!

**Comment by eksperimental** [comment]
I'm also wondering, should we soft-deprecate Keyword.t/0-1 type eventually?
I don't see much point in having it.

**Comment by josevalim** [comment]
Aliases are common, so I don't see an issue with keeping both. So the fix
is to simply add elixir to the PLT?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
I think replace Keyword with :elixir, I did not run anything.

We may want to look at using the unknown warning to help explain future
issues but unsure if that'll result in other warnings.

**Comment by josevalim** [comment]
Ping. We would like to include this on v1.5.0-rc.0 which should be out next week.

**Comment by eksperimental** [comment]
@josevalim sorry, but what is the solution proposed here.

**Comment by josevalim** [comment]
@eksperimental the fix is to remove `Keyword` from [here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/kernel/dialyzer_test.exs#L25) and add `:elixir` instead.

**Comment by eksperimental** [comment]
Suggestion implemented, rebase and all CI tests pass. So this is ready to be merged

**Comment by fishcakez** [comment]
Thank you :heart:

**Comment by eksperimental** [comment]
Same to you

**Pull request merged**
