### PR TITLE
Remove previous archive after download success

### LINKED ISSUE #3345: Only remove current hex.ez if download is successful of new one
https://github.com/hexpm/hex/issues/97

Currently I have the bug where I cannot download a new hex.ez via mix. Sometimes I hit "Y" when it asks to download, in hopes it might be fixed. But it's not and it deletes my current hex. 

So next time I `mix deps.get` it cannot find hex and I have to go download it manually.

### PR DESCRIPTION
**Pull request by doomspork**
RFC @ericmj — This should close #3345.  Thanks in advance for your feedback :tada:

### CODE REVIEW

**Comment by ericmj** [comment]
Perfect! Thanks.

**Comment by doomspork** [comment]
Hooray :tada: Thanks again for your help.

**Comment by jeregrine** [comment]
🎉

**Comment by ericmj** [comment]
@doomspork I have reverted this commit because it was removing the just installed version if it already existed. Please make sure we do not remove the just installed version and add a test for it.

**Comment by doomspork** [comment]
Thanks for the heads up @ericmj, I'll take a look at this today.

**Comment by doomspork** [comment]
Alright @ericmj, I do believe I've got this sorted out now.  I'll open a new PR today.  Thanks for your patience.

**Pull request merged**
