### PR TITLE
MIX_BUILD_PATH specifies the build_path (and has the env added on to it)

### LINKED ISSUE #9188: Using mix clean with MIX_BUILD_PATH can erase your source code files
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 22)
```
* Operating system: 
Arch linux / docker

### Current behavior

In Docker I usually set MIX_BUILD_PATH to avoid permission conflicts with the host. So in my docker container I have `MIX_BUILD_PATH=/_build` and my app in `/api`.

However, `mix clean` is expecting the build path to be two directories deep, ie `/_build/dev`. So it runs `Path.dirname()`, resulting in `"/"`. Then it adds to that path, eventually resulting in the following pattern: `/*/lib/your_app_name`, and it erases everything matching that. My application is in `/api/`, so this matches.

The result: my source code gets deleted.

### Expected behavior

I would expect `mix clean` to only delete build files.

### Possible solutions

1. add the env to `MIX_ENV_PATH` in `Mix.Project.build_path/1`
2. have `mix clean` match only build files (`.beam` etc)
3. document MIX_BUILD_PATH better so that users understand that it should be eg, `/_build/dev` (https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix.ex#L237)
4. modify `mix clean` to recognize when it is dealing with `MIX_BUILD_PATH` so that it doesn't remove the last directory from the path.
5. filter files to be deleted to make sure they aren't actually in your application directory
6. something else?

### PR DESCRIPTION
**Pull request by derekkraan**
Fixes #9188.

(@josevalim I think this is what you meant?)

### CODE REVIEW

**Comment by josevalim** [comment]
@derekkraan precisely. Also please add a test to `mix/project_test.exs`.

**Comment by derekkraan** [comment]
:ok_hand: will do

**Comment by derekkraan** [comment]
Done! the try/after ensures that this test doesn't break other tests if it breaks (which it does on `master`).

**Comment by derekkraan** [comment]
I see you pushed a change. I was going to put the call to `System.delete_env/1` in an `on_exit` block. Or would you prefer I leave it as it is now?

**Comment by derekkraan** [comment]
Like so:
```elixir
test "considers MIX_BUILD_PATH" do                                       
  System.put_env("MIX_BUILD_PATH", "_build")                             
                                                                         
  on_exit(fn ->                                                          
    System.delete_env("MIX_BUILD_PATH")                                  
  end)                                                                   
                                                                         
  assert Mix.Project.build_path() == Path.join(File.cwd!(), "_build/dev")
end                                                                      
```

**Comment by josevalim** [comment]
@derekkraan both are fine. the current one is good enough, so i would keep it as is. :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
