### PR TITLE
Only store test timings in CLIFormatter when --slowest is used

### PR DESCRIPTION
**Pull request by vorce**
Hey all, thanks a lot for Elixir! ❤️ 

Our monolith's test suite is growing fast, and at 12k cases the memory usage goes up a lot (GBs) when running tests. This can cause build failures if the oom killer kicks in.

After looking at what the `CLIFormatter` is doing it seems it is saving each test case struct, even if it's not strictly needed. This PR changes so timings are only saved if `--slowest` is used.

Not very happy with the tests, but not sure if starting the genserver and sending message + inspecting state is much better. What do you think?

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @vorce!

Thank you for the pull request but unfortunately I doubt this will make any difference on the amount of memory used. The amount of memory used by the timings or even the structs is minimal compared to the amount of memory the actual code in the tests use.

What could potentially help is for us to have a flag that removes modules from memory after you run the tests. This could be done in ExUnit.Runner. You can give it a try by adding:

```
:code.delete(module)
:code.purge(module)
```

around here:

https://github.com/elixir-lang/elixir/blob/94bab4476406b732dc82100e150de2de2faacc26/lib/ex_unit/lib/ex_unit/runner.ex#L228

Then measure if it actually reduces the memory usage in your case. It may also increase the test suite time, so please measure that too and let us know.

**Comment by vorce** [comment]
Thanks for the quick reply @josevalim!

I'll do some proper measurements. And thanks for the tip about `:code.delete` and `:code.purge` - I'll play around with that as well.

**Comment by josevalim** [comment]
Oh, great find! I was definitely wrong and the logs are definitely the root cause.

I think you can provide a 1LOC change here:

https://github.com/elixir-lang/elixir/blob/main/lib/ex_unit/lib/ex_unit/cli_formatter.ex#L287

to this:

    # Do not store logs, as they are not used for timings and consume memory.
    [%{test | logs: ""} | timings]

And that's it! No tests necessary. Can you please update the PR?

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by josevalim** [comment]
Btw, can you also please try the code purge/delete change too? I would also love to know if it also yields improvements.

**Comment by vorce** [comment]
Cool - thanks José! I'll try out the :code.purge/delete change and report back 👍

**Comment by vorce** [comment]
@josevalim I added some initial results for using `:code.purge` and delete in the runner: https://docs.google.com/spreadsheets/d/1vuxsO8gQhYsq7HRikB6hOC-xtht67gYVDmkaVqHXDBk/edit?usp=sharing (elixir_modified tab is master, elixir_purge is with using code:purge and delete). 
I've only ran it on elixir's own test suite so far. Looks very promising, memory curve is downward! I will run it some more to better see how much the run time is affected.

**Pull request merged**
