### PR TITLE
Run travis tests against Erlang 19

### PR DESCRIPTION
**Pull request by PragTob**
With some of the incompatibilities expected from a major version
thought this might be a good idea, and the builds are fast enough
so I think travis won't mind :)

(not sure if this is wanted, I just noted that they were only running against 18, so I thought adding the new major might be a good idea :) )

Tobi

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
what about other Erlang versions such as 18.3?

**Comment by antipax** [comment]
Yeah, seems like it should be running on the latest minor version of each major release?

**Comment by fishcakez** [comment]
I think it is more useful to use the first minor than last because that is the most likely time where we have an issue we need to handle because of new features. I am not sure there is a reason not to have the first and last though, or a troublesome version.

**Comment by eksperimental** [comment]
well, i think it makes sense to be running **at the very least** the lastest minor version as well as the lowest supported version.
In the past we were supporting, 17.0, 17.3, 17.4, 17.5 at the same time

I propose to add support for 
18.0, 18.1, 18.2.1, 18.3, 19.0

**Pull request merged**
