### PR TITLE
Review Version module specifications

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
Feedback is welcome

**Comment by eksperimental** [comment]
@ericmj That I was waiting for some feedback, as I wasn't 100% sure about the types

**Comment by eksperimental** [comment]
WIP removed from commmit log and PR title. it can be merged now

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
