### PR TITLE
Log error on unhandled GenServer message by default

### PR DESCRIPTION
**Pull request by fishcakez**

### CODE REVIEW

**Comment by josevalim** [comment]
What if we log for all handle_* callbacks



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Oops, premature send. All handle callbacks for all behaviors so they are
consistent and we don't need the dialyzer hack.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fishcakez** [comment]
`handle_call/3` causes a problem because either we reply and risk
mishandling that in the caller or if we noreply and risk the caller
blocking for infinity (or the timeout).

**Comment by josevalim** [comment]
Excellent point. Suggestions? I am thinking that if we log and use no
reply, it is still fine because it is not a silent fail?

Also, regardless of handle_call, which log level should we use?


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by fishcakez** [comment]
I think this is now too intertwined with Alexei's proposal on mailing list
so should move discussion there.

**Comment by fishcakez** [comment]
We can't log for GenEvent because the message might be for a different handler.
This change will also log for Agent because `handle_info/2` isn't overridden in `Agent.Server`.

**Pull request merged**
