### PR TITLE
Fix inconsistencies in sigils syntax.

### PR DESCRIPTION
**Pull request by tuvistavie**
As briefly discussed with @lexmag, I fixed some inconsistent sigils definitions.
https://github.com/elixir-lang/elixir/pull/4108/files#r48375380

### CODE REVIEW

**Comment by josevalim** [comment]
I usually avoid such commits because they pollute the history. It is annoying when you do a git blame and it points to a style-related commit. I will leave it up to @lexmag though. :)

**Comment by josevalim** [comment]
Thank you!

**Comment by tuvistavie** [comment]
@josevalim Sure, I understand! `git blame -w` is cool for whitespaces, but I do not know how to avoid this issue for general style-related commits :sweat:

**Comment by lexmag** [comment]
Sorry I wasn't clear enough in the that comment. :cry:
I was saying that keeping everything as it is today would be better.
Style-related commits is good when they correct every single appearance of bad style, what is very uneasy thing considering different sigils (`w`, `s`, etc.) and possible "markers" (`[`, `|`, `"`, etc.), and honestly, I don't think we have stated definitive "marker" for sigils __yet__.
Thank you anyway! :yellow_heart:

**Comment by tuvistavie** [comment]
@lexmag No problem, thanks for the explanation!

**Pull request closed without merging**
