### PR TITLE
Makefile: remove use of `cd` when running tests (2nd try)

### PR DESCRIPTION
**Pull request by eksperimental**
Original PR and discussion: https://github.com/elixir-lang/elixir/pull/3534

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @eksperimental but, as said in the other pull request, it is not worth changing this and adding the complexity of dynamically checking paths and so on. Running inside the project is the best approach.

**Comment by eksperimental** [comment]
no problem,

Would you be interested in having a new PR with the changes to `lib/ex_unit/test/ex_unit/doc_test_test.exs`
commit: https://github.com/eksperimental/elixir/commit/a7b7dd70047a5e531751a0f14b09b7965bd59c64

I can leave only the changes made to the line numbers, (not the file path),
I think it's worth since whenever that file is edited in the future, it won't need updating the hardcoded line numbers.

**Comment by josevalim** [comment]
Not really because I *want* to see the printed reports entirely even if it is cumbersome to change from time to time. If we didn't care about the layout, we only match on parts instead of the whole thing.

**Comment by lexmag** [comment]
As for me, eksperimental@a7b7dd7 brings more magic than simplicity.

**Comment by eksperimental** [comment]
@josevalim that makes total sense.

**Pull request closed without merging**
