### PR TITLE
Keyword.bool/3 and Keyword.bool!/2

### PR DESCRIPTION
**Pull request by guilleiguaran**
Implementation of idea suggested in #2497

### CODE REVIEW

**Comment by jcspencer** [comment]
Any news on this?
/cc @josevalim

**Comment by guilleiguaran** [comment]
Should I rebase this?

**Comment by josevalim** [comment]
Not yet, we still haven't decided on this, sorry!

**Comment by MrMormon** [comment]
I don't see discussion happening on any related issues. Is it happening behind the scenes in IRC or something?

**Comment by josevalim** [comment]
This issue has been sitting here for our while and we were not able to reach an agreement on merging it, so it is probably time to let it go. Thanks @guilleiguaran!

**Pull request closed without merging**
