### PR TITLE
Explain race condition in assert_receive to user when it happens

### LINKED ISSUE #5199: assert_receive output can be confusing on failure due to race to read process mailbox
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: 

### Current behavior

If a message is received after the `assert_receive` timeout, but before [`ExUnit.Assertions.__mailbox__(self())`](https://github.com/elixir-lang/elixir/blob/0f206e533569cf9b2ac50986e676322c5fa1ed08/lib/ex_unit/lib/ex_unit/assertions.ex#L408) is called, the failure message is confusing, because the message will appear in `Process mailbox` section, but the error will say `No message matching`.

```
No message matching {:DOWN, ^client_reference, :process, ^client_pid, {:timeout, _}} after 100ms.
The following variables were pinned:
  client_reference = #Reference<0.0.6.1817>
  client_pid = #PID<0.935.0>
Process mailbox:
  {:DOWN, #Reference<0.0.6.1817>, :process, #PID<0.935.0>, {:timeout, {GenServer, :call, [#PID<0.935.0>, {:index, %{}}, 1]}}}
```

### Expected behavior

Check the message again inside `ExUnit.Assertions.__mailbox__(self())` before flunking, then do one of the following:
A) Say "Message appeared in mailbox after `<timeout>`.  Increase timeout.", then have the user retest after increasing the timeout option to `assert_receive`
B) Don't `flunk` and allow the test to pass even though it was a little past the timeout (since the timeouts aren't precise anyway).

I like (A) because it makes the test more reliable and allows users that are checking soft-realtime issues to know that they are on the edge of their timeout window.

I'd be happy to open a PR for either option.

### PR DESCRIPTION
**Pull request by KronicDeth**
Fixes #5199

When using assert_receive, it is possible for the following sequence of
events:
1. `after` timeout triggers, indicating messages was not received
2. Process receive messages
3. `Process.info(self(), :messages)` is called and gets message
`assert_receive` was waiting for.

Previously, `assert_receive` would not check the output `Process.info(self, :messages)` for the expected pattern, so it would print a confusing error message that said "No message matching <pattern> after <timeout>ms", but then show a matching message in the "Process mailbox" section.  Now, for this special race-condition, a long-form explanation that the message is being delivered at or near the timeout is being printed, along with how this could impact production and how to fix it if it only impacts tests.

## Design Review

So, there are multiple points where I'd like feedback on the design:

1. Should the failure message be so long and wordy.  (I would gladly taking editing/technical writing changes.)
2. Should the corrective actions list use `Macro` to try to give the exact new code to use, since option (1) doesn't say explicitly how to increase the timeout to one `assert_receive`.
3. Should I still use the overridden `failure_message` when the race condition occurs (and then append the part starting from ", but a matching [...]" OR is the way I did it okay, because it's such an exceptional case that the new explanation should always be used.
4. I can consistently trigger the bug by having the timeout for `Process.send_after` and the `assert_receive` timeout be the same, but is that a fluke of my setup?  I don't want this to become a flaky test that sometimes fails the build and requires manual rebuilds.  Should I be simulating the race condition instead of activating it directly?

### CODE REVIEW

**Comment by KronicDeth** [comment]
The build failed on only for 18.1 (https://travis-ci.org/elixir-lang/elixir/jobs/159066166), but it's not related to my change, but also the last build on master https://travis-ci.org/elixir-lang/elixir/builds/159034942_ passed, so I'm not sure what's going on with the failing test.  Is it know to be flaky?

```
04:09:48.796 [error] Task #PID<0.5488.0> started from #PID<0.5469.0> terminating
** (UndefinedFunctionError) function Inspect.inspect/2 is undefined (module Inspect is not available)
    (elixir) Inspect.inspect(IEx.Info, %Inspect.Opts{base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: false, safe: true, structs: true, width: 80})
    (elixir) lib/kernel.ex:1597: Kernel.inspect/2
    (mix) lib/mix/tasks/compile.protocols.ex:130: Mix.Tasks.Compile.Protocols.consolidate/4
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<8.127116546/0 in Mix.Tasks.Compile.Protocols.consolidate/6>
    Args: []
  1) test recompiles project if scm changed (Mix.Tasks.Compile.ElixirTest)
     /home/travis/build/elixir-lang/elixir/lib/mix/test/mix/tasks/compile.elixir_test.exs:61
     ** (EXIT from #PID<0.5469.0>) an exception was raised:
         ** (UndefinedFunctionError) function Inspect.inspect/2 is undefined or private. Did you mean one of:
     
           * inspect/2
     
             (elixir) Inspect.inspect(IEx.Info, %Inspect.Opts{base: :decimal, binaries: :infer, char_lists: :infer, charlists: :infer, limit: 50, pretty: false, safe: true, structs: true, width: 80})
             (elixir) lib/kernel.ex:1597: Kernel.inspect/2
             (mix) lib/mix/tasks/compile.protocols.ex:130: Mix.Tasks.Compile.Protocols.consolidate/4
             (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by josevalim** [comment]
This failure happens from time to time. I believe it is a race condition in the mix suite where we change directories as we consolidate some protocol. Unfortunately I was not able to pin point it yet.

This patch looks great btw, I will merge it and change the error message locally.  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by fishcakez** [comment]
This is going to produced a failures in the test suite because it is a race condition (it is noted but this is awkward) https://travis-ci.org/elixir-lang/elixir/jobs/162424629#L309

**Comment by KronicDeth** [comment]
@fishcake I can change the test to not trigger the race, but instead mechanistically check the implementation if the race condition is too flaky.

**Comment by josevalim** [comment]
Fixed in aef130c0ebaab148390ca87f93bb0c56ddf0eb2e.

**Pull request merged**
