### PR TITLE
Fixed typo/grammar in Supervisor @doc

### PR DESCRIPTION
**Pull request by uDude**
The first three commits are just me reverting and resyncing to upstream master.  The fourth is the single letter change to the Supervisor doc.

### CODE REVIEW

**Comment by alxndr** [comment]
Might be nice to [squash all these commits into just one](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by uDude** [comment]
I suck with git.  I will rtfm

**Comment by josevalim** [comment]
Yes, please squash and we are good to go! :D

**Comment by uDude** [comment]
squashed.

**Comment by alxndr** [comment]
Nicely squashed @uDude!

One more slightly odd thing (which may not matter at all, but I figured I'd mention it): the commit doesn't link to your GitHub account. I think you may need to add your GitHub account's email address to the git settings on your local computer.

**Comment by uDude** [comment]
graci, will do.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
