### PR TITLE
Fix parsing of fractional durations

### PR DESCRIPTION
**Pull request by urmastalimaa**
The parsing of fractional durations checked for non-negativity by testing `second > 0`, which reports `false` for not only negative integers but also for 0.

The JavaScript libraries that I tested disagree whether "-PT-0,6S" represents a positive or negative duration, "moment" and "tinyduration" reported positive, "luxon" (the successor to moment) reported negative. My reading of the specification gives me no reason to doubt that a double negative should result in anything but a positive total result.

It is worth mentioning that as the scale units are represented as integers, there is no clean way to implement fractional parsing of non-second units. Currently, fractional non-second durations simply fail to parse. [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Durations) gives "0.5Y" as an example.

### CODE REVIEW

**Comment by urmastalimaa** [comment]
I'll clarify that I didn't change the possibility and interpretation of double negatives, outside of "-PT-0,NS".

**Comment by tfiedlerdejanze** [comment]
FWIW i'd also find it counter-intuitive for `"-PT-0,6S"` to result in a negative duration.

As the change doesn't affect the actual behaviour i am fine with it, however, while it makes sense to me in theory i fail to see the practical benefit of it. @urmastalimaa does this actually fix a case that's currently wrongly parsed?

> Currently, fractional non-second durations simply fail to parse. [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Durations) gives "0.5Y" as an example.

this is correct, it was intended for us to support fractional units for the smallest time unit only for now.

**Comment by urmastalimaa** [comment]
Thanks for the context.
Me getting on tangents without stressing what is being fixed caused a bit of confusion, my apologies.
I split the change into three commits to be clearer
1. Added tests for existing behaviour about rejecting fractions for non-second components
2. Added tests for existing behaviour about fractional durations with 0 in the integer component, including a case for the existing bug
3. Fix for parsing fractionals with 0 in the integer component

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
