### PR TITLE
Use parens consistently in some function calls in the IO module

### PR DESCRIPTION
**Pull request by pavlos**
Just tacked on some parens to make it consistent with the other defaults that use group_leader()

### CODE REVIEW

**Comment by whatyouhide** [comment]
What if we title the commit with something like

> Use parens consistently in some function calls in the IO module

?

**Comment by pavlos** [comment]
@whatyouhide :+1:

**Comment by whatyouhide** [comment]
@pavlos :clap:

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
