### PR TITLE
Don't deprecate {:ok, keywords | map} results in ExUnit callbacks anymore

### PR DESCRIPTION
**Pull request by whatyouhide**

### CODE REVIEW

**Comment by josevalim** [comment]
Maybe we should hold this one for one extra release. I am afraid we are enabling too many warnings (which have been accumulated).

**Comment by whatyouhide** [comment]
@josevalim I enjoy warnings a lot as I believe they're the true way™ of ensuring 1.x -> 2.0 will be a smoothish transition, but maybe you have a good point. Should we deprecate in 1.6 then? If that's ok, I would still like to commit the test updates so that when we deprecate we will not see any warnings already :)

**Comment by michalmuskala** [comment]
Isn't this violating the deprecation policy? It's a very surprising change, I've never actually heard about it, and it affects a lot of code - actually all of it.

When was it introduced that the tuple can be skipped? I couldn't find it in the changelogs.

**Comment by whatyouhide** [comment]
@michalmuskala as far as I found, in https://github.com/elixir-lang/elixir/commit/58377cde, which was on 1.3 as well, so we soft-deprecated for 1.3 and 1.4 and that's why I was hard-deprecating on 1.5. But a good point is that the documentation wasn't updated in all its parts, so this may be a slightly surprising change indeed.

**Comment by josevalim** [comment]
@whatyouhide let's update the comments to say to change this on 1.6 and meanwhile make sure we update the docs.

**Comment by josevalim** [comment]
@whatyouhide alternatively we can just keep it as is and accept any of `:ok`, `{:ok, map}` or `map`.

**Comment by whatyouhide** [comment]
I think a good path could be to:

  * update the docs to only mention `:ok | keyword | map`, without mentioning `{:ok, keyword | map}` (or saying it's deprecated)
  * update the TODO to say to hard-deprecate this on 1.6
  * update all tests in the Elixir source that return `{:ok, keyword | map}` to return `keyword | map` (which I already did in this PR)

I'm not a fan of allowing `:ok | keyword | map | {:ok, keyword | map}` even in the future, as it feels superfluous to me and confusing as to why we would have all of them. Actually, I prefer `:ok | {:ok, keyword | map}` myself just because I prefer the explicitness of tagging the tuple, even if I know it's superfluous information, but it's ok as `:ok | keyword | map` as well :)

Sounds like a good plan to all of you, or do you have suggestions?

**Comment by josevalim** [comment]
Just to add some background. We introduced this changed when we added the named setups to the language, because the named setups receive the context and return the context. So we wanted those to work more like function composition.

However, for some reason, I do prefer `{:ok, map | keyword}` for setup blocks. I am not sure if this is habit or an actual preference.

**Comment by whatyouhide** [comment]
I definitely prefer `{:ok, map | keyword} | :ok` as well, and while I get the idea behind just `:ok | map | keyword`, we're not really piping setup functions, right? So it may still be ok to require `{:ok, map | keyword} | :ok`? (but I guess it would be backwards incompat?)

Anyhow, what should I do now then? 😄

**Comment by josevalim** [comment]
> Anyhow, what should I do now then? 😄

I would remove the TODO and support all three formats (which is what we do today). It is clear we have preferences based on the usage and the discussion shows we are not ready to deprecate any of them.

**Comment by whatyouhide** [comment]
Ok, updated!

**Pull request merged**
