### PR TITLE
Run the code formatter on lib/elixir/test/elixir/kernel/expansion_test.exs

### PR DESCRIPTION
**Pull request by alistairstead**

### CODE REVIEW

**Comment by ericmj** [comment]
Thanks for submitting the PR, but please limit to one file per PR and one PR per day so we don't get overloaded.

**Comment by alistairstead** [comment]
Okay. Sorry had a few in flight but will not send anymore today

On Mon, Oct 9, 2017 at 15:53, Eric Meadows-Jönsson <notifications@github.com> wrote:
Thanks for submitting the PR, but please limit to one file per PR and one PR per day so we don't get overloaded.

**Comment by ericmj** [comment]
No worries. Thanks for you contributions!

**Comment by josevalim** [comment]
Merged manually, thank you!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request closed without merging**
