### PR TITLE
Use XDG directories by default

### PR DESCRIPTION
**Pull request by hauleth**
This will use XDG-like directories by default, not only if the proper env variables exists. It will still fallback to old `~/.mix` if this directory exists.

### CODE REVIEW

**Comment by josevalim** [comment]
This will unfortunately be a breaking change. The behaviour is there for those who want to opt-in though. Thanks!

**Comment by hauleth** [comment]
It would be quasi-breaking for new installations only, as it would use `~/.mix` if it is present. So if user would do `mkdir ~/.mix` it would work as earlier. It is for example how Git managed migration (mostly) as it will read both `~/.config/git/config` and `~/.gitconfig` and will override all configuration options from the previous one.

This has serious implication as user explicitly need to set `XDG_*` variables which is [against the specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

Other alternative I see is that Mix would check if the `~/.config/mix` exists and if so, then it would use the XDG specs.

Ideally it would be to use `filename:basedir/2` there, but it would be probably a little bit more confusing for some users, especially on macOS.

**Comment by hauleth** [comment]
@josevalim I have just checked, and usage of `~/.mix` directory is not documented almost anywhere. It is only briefly mentioned in `mix help` docs. Other than that this behaviour is completely undocumented and from my viewpoint the [environment variable docs](https://hexdocs.pm/mix/Mix.html#module-environment-variables) suggest that Mix will follow XDG specs.

**Comment by ericmj** [comment]
If it's not documented it is only because it's missing in the docs. The vast majority of the Elixir community will use that `~/.mix` is used by default and I can only assume that are many scripts that make this assumption, CI or otherwise.

I have made a PR to document the defaults properly: https://github.com/elixir-lang/elixir/pull/9938.

**Comment by ericmj** [comment]
I don't believe any scripts are pre-creating the `~/.mix` directory, instead they rely on mix to create it. Because of this it would still be a breaking change to only use `~/.mix` if it already exists.

**Pull request closed without merging**
