### PR TITLE
don't inline `Integer.to_char_list/2' and `Integer.to_string/2'

### PR DESCRIPTION
**Pull request by talentdeficit**
replacing them with erlang native functions eliminated the guard checks on the function arguments

### CODE REVIEW

**Comment by josevalim** [comment]
@talentdeficit you are right. We need to either stop inlining them or remove the guards. @ericmj what are your thoughts here?

**Comment by talentdeficit** [comment]
i found a few other places where function specs indicate there should probably be a guard (`List.to_integer/2') for example that isn't present. i left them inlined (and unguarded) but for consistency whatever decision is made should probably be applied to those also

**Comment by ericmj** [comment]
Is a FunctionClauseError more useful than an ArgumentError?

**Comment by josevalim** [comment]
I think none of them are good. The argument error also shows the arguments in the underlying bad call. I am more inclined to remove the guards.

**Comment by c-rack** [comment]
I don't think there is a benefit due to the guards, so I would vote for removing the guards and inline the functions.

**Comment by ericmj** [comment]
If they are equally bad we should just inline.

On Mon, Apr 6, 2015 at 1:54 PM, José Valim <notifications@github.com> wrote:

> I think none of them are good. The argument error also shows the arguments
> in the underlying bad call. I am more inclined to remove the guards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/pull/3248#issuecomment-90196881>.
>



-- 
Eric Meadows-Jönsson

**Comment by lexmag** [comment]
:+1: for inline and ArgumentError.

**Comment by c-rack** [comment]
I'll prepare a PR

**Pull request closed without merging**
