### PR TITLE
Piping assertions

### PR DESCRIPTION
**Pull request by jfrolich**
Hello all,

I know we can do great assertions with native operators. However often I'm using the pipe operator to chain functions together to come to certain result. Then usually I save the result, and test it.

I think in this use case a better developer experience is to be able to pipe that result directly to an assertion.

That's why in the following pull request I created two new macros:

`assert_equal` you can pipe the result directly into this function and assert if the it is the expected value.

`assert_match` you can pipe the result into this and see if it matches a pattern.

Hope this makes my case, when more explanation is needed I'm happy to respond!

### CODE REVIEW

**Comment by josevalim** [comment]
Please send feature requests to the mailing list so we can collect everyone's feedback. At the end though, it is very very very unlikely this will be accepted. There is a lot of simplicity in having mostly one assertion macro and I believe people attempt to rely to much on piping.

**Comment by jfrolich** [comment]
Thanks Jose, 

it was a small implementation, so I thought it was better to see it implemented than as a proposal.
About keeping simplicity I can see the argument. 

My issue with using operators in assertions, is that while improving readability, they are not very functional constructs, and thus do not compose well. Having a functional equivalent for the assertions, makes sense in a functional language in my opinion. 

If you have slightly more complex tests than testing the output of a single function, you need assignment and then assert that assignment with an operator. Using functional assertions is a win for readability in my opinion. Consider this controller test in phoenix:

```elixir
conn =
  build_conn()
  |> post("/upload_content_cover", params)

assert %{"success" => true} = json_response(conn, 200)
```

with `assert_match` this translates to the following:
```
build_conn()
|> post("/upload_content_cover", params)
|> json_response(conn, 200)
|> assert_match(%{"success" => true})
```

I prefer the latter, because it is more declarative. 

With regards to too much use of the pipe operator; My argument is mostly that these functional assertions are composable, whether you use the pipe operator, or manual composition (`foo(bar())`), I personally think the pipe operator makes the flow much more readable. Using the pipe operator a lot I would say is a good sign, because then you are writing easily composable functions, often meaning clean code, so I do not really get the point of that they are over-used.

However I can also see why this should be a library :) Just would like to give you a bit more background in my thinking. I'm also interested in your feedback to this.

**Comment by jfrolich** [comment]
Will send this to the mailing list as well.

**Comment by josevalim** [comment]
The problem is that it doesn't scale API wise. Soon you will see yourself adding assert_in, assert_different, assert_more_than, etc, which are solved by today's API. It feels like a step backward only for the benefit of piping.

**Pull request closed without merging**
