### PR TITLE
Add `b` IEx helper to display behaviour docs

### PR DESCRIPTION
**Pull request by lexmag**
It introduces `b` helper to output behaviour docs as shown below:
```elixir
iex(1)> b Mix.SCM.fetchable?/0

                                def fetchable?/0                                

Returns a boolean if the dependency can be fetched or it is meant to be
previously available in the filesystem.

Local dependencies (i.e. non fetchable ones) are automatically recompiled every
time the parent project is compiled.

:ok
```
In contrast with regular docs currently we have no `args` stored in the behaviour docs.
I think it might be solved by some ways:
* adding it to the behaviour docs (breaking change)
* extracting it from the specs
* probably keep it as is

Another question is, shall we display it as `def fetchable?/0` like it has to be implemented or as it is defined `defcallback fetchable?/0`?

### CODE REVIEW

**Comment by josevalim** [comment]
Nice! I would show it as `defcallback` (or `defmacrocallback`).

Regarding the args, we should consider extracting the whole signature from the specs or showing the spec before or after the documentation.

**Comment by josevalim** [comment]
Ping me when this is ready for merge please. :)

**Comment by lexmag** [comment]
Sure, almost done. :smile:

**Comment by lexmag** [comment]
@josevalim ping, it is ready for merge. Here is a showcase:
```elixir
iex(1)> b Mix.SCM.fetchable?/0

                     defcallback fetchable?() :: boolean()                      

Returns a boolean if the dependency can be fetched or it is meant to be
previously available in the filesystem.

Local dependencies (i.e. non fetchable ones) are automatically recompiled every
time the parent project is compiled.
```
```elixir
iex(2)> b Mix.SCM.fetchable   
No documentation for Mix.SCM.fetchable was found
```
```elixir
iex(3)> b DoNotExist.run   
Could not load module DoNotExist, got: nofile
```
Please note, I haven't added `b` for a one module only, not sure if it's needed, the output for behaviour with many callbacks  looks clumsy.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by alco** [comment]
Could `b Module` simply list the callbacks? There is no way to get it otherwise in IEx, need to go for the source.

**Comment by josevalim** [comment]
:+1: for listing the callbacks.

**Comment by lexmag** [comment]
Agree, it'll look natural.

**Pull request merged**
