### PR TITLE
Rename Calendar module files according to the convention

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
Date.Range breaks the rule big time since it is placed in a different directory,
The other two are just missing the underscore.

**Comment by josevalim** [comment]
It is fine as is. :) If we were going to follow the convention, they wouldn't even be inside the `calendar` folder. I also think we agreed that we would write `DateTime` as `datetime`. Or did we settle on `date_time`? I can't remember.

**Comment by wojtekmach** [comment]
I'd keep it as `datetime` even if it's arbitrary; GItHub is `github`, not `git_hub`!

**Comment by eksperimental** [comment]
> I also think we agreed that we would write `DateTime` as `datetime`. Or did we settle on `date_time`? I can't remember.

I missed that discussion.

**Pull request closed without merging**
