### PR TITLE
made change

### PR DESCRIPTION
**Pull request by pankajobjects**

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks although according to this page the current version is correct:
https://english.stackexchange.com/questions/8382/when-etc-is-at-the-end-of-a-phrase-do-you-place-a-period-after-it
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ryharris** [comment]
The comma is extraneous because "under the `doc` directory" is a dependent clause that follows the main clause. 

>However, don't put a comma after the main clause when a dependent (subordinate) clause follows it (except for cases of extreme contrast).

From https://owl.english.purdue.edu/owl/owlprint/607/

**Comment by josevalim** [comment]
Oh, that makes sense. Thanks!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
