### PR TITLE
Augment the Stream.t type to include functions

### PR DESCRIPTION
**Pull request by whatyouhide**
@josevalim something like this?

### CODE REVIEW

**Comment by josevalim** [comment]
Sorry, I was wrong. You should use Enumerable.t there. Stream.t is likely
useless, I can't see why anyone would use it. :)

On Saturday, May 28, 2016, Andrea Leopardi <notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> something like this?
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/elixir-lang/elixir/pull/4712
> Commit Summary
>
>    - Augment the Stream.t type to include functions
>
> File Changes
>
>    - *M* lib/elixir/lib/stream.ex
>    <https://github.com/elixir-lang/elixir/pull/4712/files#diff-0> (5)
>
> Patch Links:
>
>    - https://github.com/elixir-lang/elixir/pull/4712.patch
>    - https://github.com/elixir-lang/elixir/pull/4712.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/pull/4712>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbhbS_vuXorYnAEZwjqLJXvl_BybEks5qGKBkgaJpZM4IpJi1>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
@josevalim sorry, so should I fix `Stream.t` to be `%__MODULE__{} | Enumerable.t`, or should I fix `URI.query_decoder/1` to return `:: Enumerable.t` (and maybe mention that it returns an enumerable instead of a stream in the documentation for it?)?

**Comment by josevalim** [comment]
It should be Enumerable.t in query decoder. You can still say it returns a
stream because a streak is any lazy Enumerable.

On Saturday, May 28, 2016, Andrea Leopardi <notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> sorry, so should I fix Stream.t
> to be %__MODULE__{} | Enumerable.t, or should I fix URI.query_decoder/1
> to return :: Enumerable.t (and maybe mention that it returns an
> enumerable instead of a stream in the documentation for it?)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/pull/4712#issuecomment-222327550>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbk7Hh_2uc34fieM-7ZITyr5qVIiTks5qGKGPgaJpZM4IpJi1>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
@josevalim alright, that's what I thought :)

**Pull request closed without merging**
