### PR TITLE
Request for feedback: formatted elixir's erlang code using erlfmt

### PR DESCRIPTION
**Pull request by awalterschulze**
This code is formatted using `erlfmt` version 0.9.0

We would like to hear what you think about this new code formatter for erlang and whether you think it is usable?

It seems that most erlang code in elixir already conform to the erlfmt style, which is pretty impressive on the part of the elixir developers for having such a consistent discipline.  It almost seems as if you have some tool, I am unaware of.

The biggest difference between the current and formatted code, seems to be the use of 2 spaces in the current code, vs erlfmt's use of 4 spaces. For context this decision is explained [here](https://github.com/WhatsApp/erlfmt/blob/master/doc/FormattingDecisionSpaces.md).

There are still other small differences, that would be valuable to get some feedback on.
Thank you for your time.

### CODE REVIEW

**Comment by josevalim** [comment]
The changes look good to us! The only question that showed up is how we are going to integrate this into CI if we eventually migrate but I think we can use an escript, so it is not a problem.

**Comment by awalterschulze** [comment]
During github actions, it is possible to download erlfmt, build it, cache it and run it.
So you shouldn't need to commit a compiled escript to your repo.

As an example, for my repos, I like to have a step in my Makefile, that just says `make deps` and it downloads and installs all dependencies.  During CI, I can then just call the exact same step. So it is easy for developers on the repo to setup an environment that is somewhat consistent with CI.

But maybe there is something we can do to make this easier on your end?

**Comment by josevalim** [comment]
I would still embed it in the repo so contributors can also run it locally without any additional install? Or big is the escript? :D

**Comment by michalmuskala** [comment]
Latest release is 123K. I think we should be fine checking it into the repo

**Comment by ericmj** [comment]
How stable is the formatter output? Since erlfmt is pre-release, maybe we should hold off on using it until 1.0 is released to avoid unnecessary change churn of the .erl files?

Are there any discussions about an official erlang formatter? Since erlfmt is unofficial afaik we should probably evaluate the other existing formatters first.

**Comment by awalterschulze** [comment]
Here is a comparison we did with other erlang formatters
https://github.com/WhatsApp/erlfmt/blob/master/doc/ErlangFormatterComparison.md

**Comment by michalmuskala** [comment]
Those are fair questions.

We have a document comparing erlfmt with other formatters in https://github.com/WhatsApp/erlfmt/blob/master/doc/ErlangFormatterComparison.md.

As to the stability, we're approaching it quickly. There's only a handful of open discussions and applying proposals in most of them wouldn't change already-formatted code. For somewhat settled decisions we maintain a list of documents describing the reasoning behind them at https://github.com/WhatsApp/erlfmt/tree/master/doc#formatting-decisions.

As to settling on one official formatter for Erlang, this would be my preferred outcome, but if it happens, it will take a long time. We've engaged with the OTP team looking for feedback on the current style and got a solid review. We've addressed all of the remarks either through changes or enhancing the decision documents with relevant explanations.

Also, I think it's fine to wait a bit more. At this point, what we wanted was to primarily check whether there aren't any show-stoppers for Elixir adopting erlfmt for its Erlang code.

**Comment by josevalim** [comment]
Alright, I think this discussion has filled its purpose then and we will be glad to discuss effectively moving to the formatter once it becomes stable.

**Comment by awalterschulze** [comment]
Thank you so much for your time.  This was very valuable to us <3

**Pull request closed without merging**
