### PR TITLE
Handle case when report_cb need 2 arguments

### PR DESCRIPTION
**Pull request by hauleth**

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks @hauleth! Can we add a test case for this? Please look at `translator_test.exs` for examples.

**Comment by hauleth** [comment]
Done

**Comment by josevalim** [comment]
Thanks. Btw, for reference, can you add a link to some OTP code that uses
report_cb/2?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by hauleth** [comment]
[`proc_lib`](https://github.com/erlang/otp/blob/f489df9deb37878552c7573ac4b05d392265d1fa/lib/stdlib/src/proc_lib.erl#L512) is using `proc_lib:report_cb/2` function

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
