### PR TITLE
add CONTRIBUTING.md to Precompiled.zip release

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
What is the rationale here? We don't even ship tests with Elixir, so even things like running tests would not be possible. They should really go to version control. :)

**Comment by eksperimental** [comment]
I was thinking about feature requests, bug reports and the guidelines,
that the first half of the article,
but for the second half, you are right, I will be a bit odd to include a file that talks about stuff that are missing

so what about the  "man" folder.
are you alright with that one?

**Comment by josevalim** [comment]
@eksperimental we could include the compiled man pages, yes. We will need to change the make rule requiremets a bit though, right?

**Comment by josevalim** [comment]
Closing this then. Please send a PR for the man pages if it makes sense.

**Pull request closed without merging**
