### PR TITLE
Allow (un)registering other processes via Registry

### PR DESCRIPTION
**Pull request by bitwalker**
`Registry` currently only allows you to perform registrations in the context of the current process; but I believe it is important to also provide a way to perform registrations for other processes.

### Background

While ideally you would register processes from the process itself (in `init/1` or elsewhere, which we also do), I'm of the opinion that it is not uncommon to have situations where you are adding and removing registrations dynamically and using some centralized process to manage that.

As an example - I'm currently working on an application for which I backported `Registry` to Elixir 1.3 - we ended up needing the ability to handle registrations externally (for reasons which I'll explain in a moment), so I patched it in. We're now upgrading to 1.4.5 (and soon 1.5) and would like to remove our forked version of `Registry` and use the standard library, but without this capability we can't.

As for why we ended up implementing this capability: We have a process which is handling service discovery and management in a cluster, where each node in the cluster runs this process and communicates with one another to replicate service registration events. Services notify this process when they become available, and depending on the role of the node (which can change), they may be exposed to other nodes or not - so the authority to register as a given service does not lie with the service process itself, and we needed to be able to perform registrations on behalf of that process. Additionally, we broadcast registrations, so we're performing registrations against a remote pid on the local Registry (this allows us to do very fast lookups for services on each node, but we don't have to reinvent a global registry from scratch). Since Registry monitors the pids, if the nodes become disconnected or the pid goes down, all copies of the registration will be removed automatically, which works well enough for our needs.

This setup works well for our application, though it's not suited for every problem, but I believe that this kind of thing (registering on behalf of another process) is common enough to warrant adding this to the API.

### CODE REVIEW

**Comment by josevalim** [comment]
This introduces race conditions into the Registry. The registry needs to write on two ETS tables and the only mechanism to do so without race conditions is to make sure processes can only write to keys that belongs to them. This is a design decision taken early on so we didn't have to serialize writes through one or more processes, there is no way around it. :)

**Comment by bitwalker** [comment]
Sure, makes sense from a "could be used in any way" point of view - guess it'll have to remain a forked implementation in our app. Thanks anyway!

**Comment by josevalim** [comment]
@bitwalker just because I want to make this super clear: the proposed implementation has race conditions and there are no guarantees it will behave as expected (or at all). Really truly use at your own risk.

**Comment by bitwalker** [comment]
@josevalim The race condition you're talking about is a non-issue with the way we are using Registry, registrations are already serialized through a single process, and no other process is modifying that particular registry (only reads are concurrent). I understand the issue though, which is why I'm not pressing the point on this PR ;)

**Comment by fishcakez** [comment]
> Since Registry monitors the pids, if the nodes become disconnected or the pid goes down, all copies of the registration will be removed automatically,

With the implementation in this PR `Registry` won't cleanup any pids that aren't `self()`.

**Comment by bitwalker** [comment]
@fishcakez Good point, I just double checked the implementation we have, and the difference is that our intermediary process is handling the monitoring, for some reason I thought Registry was doing it, but it appears not - in any case, it's clear that this PR isn't worth much without the other work we've put in around it.

**Comment by fishcakez** [comment]
For anyone finding this issue later, and considering this feature:

One aspect of `ETS` versus `Registry` is that `Registry` is specifically about storing values bound to the lifetime of the process. Primarily the association of a name to the pid but also about associating a value to that pid, that can be looked up by the associated name.

While the standard approach is to lookup the pid to communicate with a name, one can also store a pid as the value of the registration. Therefore a process registering on the behalf of another may wish to registry itself as the name associated with the other process and set the `value` to the other process' pid. This has the great value that the when the proxy registry dies everything is cleaned up by `Registry` - similarly the other process will likely be linked to this proxy. The other process doesn't need to be local.

Obviously I don't know enough about this situation but it may be a helpful tip to anyone finding this issue in future.

**Pull request closed without merging**
