### PR TITLE
Add Map.filter

### PR DESCRIPTION
**Pull request by Erol**
Added `Map.filter`

```
iex> Map.filter(%{a: 1, b: nil}, fn({_k, v} -> !is_nil(v) end)
%{a: 1}
```

### CODE REVIEW

**Comment by Erol** [comment]
I'm not sure though if I should implement `Keyword.filter`. Thoughts?

**Comment by tuvistavie** [comment]
What would be the difference between `Enum.filter` and `Keyword.filter`?

**Comment by Erol** [comment]
`Keyword.filter` would be the same to `Enum.filter`, since they would both return a keyword list.

**Comment by josevalim** [comment]
We have no plans to support Map.filter for now. The best option for now is to use for-comprehensions or Enum.into or such. Thank you.

**Comment by whatyouhide** [comment]
(or `:maps.filter/2` for that matter 😛)

**Comment by Erol** [comment]
Thanks for the feedback! I'm going to try and submit this to Crutches for now.

**Pull request closed without merging**
