### PR TITLE
Clarify use of Enum.member?/2 in in/2 operator

### PR DESCRIPTION
**Pull request by eksperimental**
Introduced in: 9a9b1f48bc5a63f364e3c5329ceccea7b67fd3b7 (#9903)
/cc @glv

### CODE REVIEW

**Comment by glv** [comment]
Thanks for copying me on this! If the technicalities are different when used in a guard, I'm happy for that to be clarified.

However, my PR that's referenced here was actually prompted by a long struggle — as an Elixir newbie — to find clear documentation of the precise semantics of `in` and `not in` (what types they work with, etc). So I updated `operators.md` so that each operator clearly links to some other part of the documentation that provides more details about the semantics.

To that end, please don't remove the reference to `Enum.member?` in `operators.md` without replacing it with some other link to the details.

**Comment by glv** [comment]
Oh, sorry … I see now that the link to `in/2` at the start of the line has all the info required. Carry on!

**Comment by eksperimental** [comment]
> To that end, please don't remove the reference to `Enum.member?` in `operators.md` without replacing it with some other link to the details.

The reason why I deleted and didn't update it it is because it would be too much information for a list that aims to enumerate the operators.

**Comment by eksperimental** [comment]
> Oh, sorry … I see now that the link to `in/2` at the start of the line has all the info required. Carry on!

yes. I was going to say that.

**Comment by eksperimental** [comment]
@glv I have updated the descriptions. Please have a look

**Comment by glv** [comment]
Love it, maintains consistency with the other elements of the list by having a short description. Thank for the change!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
