### PR TITLE
IEx Autocomplete assumes module at each level, issue 3361

### PR DESCRIPTION
**Pull request by jfis**
Possible fix for
https://github.com/elixir-lang/elixir/issues/3361

### CODE REVIEW

**Comment by josevalim** [comment]
@jfis sounds like a good fix... we just need tests. :)

**Comment by jfis** [comment]
Right so I wasn't sure how to do that. Current tests make assumptions about the modules that will be returned. I'm not so sure that the situation to be tested is one that exists naturally in the elixir code base, but I'll check.

**Comment by jfis** [comment]
Would it be ok to define a module outside the test module? (see latest)

**Comment by ericmj** [comment]
Yes, but you can move it inside the module as well, just rename it to `SublevelTest.LevelA.LevelB` because it will take the namespace of the containing module.

**Comment by josevalim** [comment]
This looks great to me. Can you please move the module definition before the test (totally cosmetic change, just because we use it in the test, it would be nice to have it before) and squash all commits? Thank you! :heart:

**Comment by jfis** [comment]
Ok. By the way, why can't the module definition be inside the test?

**Comment by josevalim** [comment]
It can!

**Comment by jfis** [comment]
I thought I tried the following before and it didn't work, but I just tried again and it worked. Should I change?

    test :elixir_completion_sublevel do
      defmodule SublevelTest.LevelA.LevelB do
      end
      assert expand('IEx.AutocompleteTest.SublevelTest.') == {:yes, 'LevelA.', []}
    end

**Comment by jfis** [comment]
Oh I know why it didn't work before. It's bc I had the full name like:

    test :elixir_completion_sublevel do
      defmodule IEx.AutocompleteTest.SublevelTest.LevelA.LevelB do
      end
      assert expand('IEx.AutocompleteTest.SublevelTest.') == {:yes, 'LevelA.', []}
    end

**Comment by lexmag** [comment]
@jfis you can use `Module.create(__MODULE__.MyMod, nil, __ENV__)` as well. :bowtie:

**Comment by jfis** [comment]
@lexmag ah, cool. thanks for the tip!

**Pull request merged**
