### PR TITLE
Add Access.find/2 and Access.find!/1

### PR DESCRIPTION
**Pull request by mruoss**
I was about to create my own library with this helper function but I think it actually fills a hole in the Access module.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @mruoss!

Access.filter should be enough for those use cases. The only difference is to extract the value from the list on “get”.

**Comment by mruoss** [comment]
Hi @josevalim 

Wow, you really are a fast replier! :) Let me pitch this just very quickly before we dismiss it. Indeed, the two are very similar. What I like about Access.find() is the ability to pass a default value. This is especially nice if I don't know whether an item exists in the list or not when using put_in() or update_in(). If the item does not exist, I can pass a default and continue the traversal just like with Access.key/2:

```elixir
iex> list = [%{name: "john", salary: 10}, %{name: "francine", salary: 30}]
iex> put_in(list, [Access.find(&(&1.name == "adam"), %{name: "adam"}), :salary], 50)
[%{name: "adam", salary: 50}, %{name: "john", salary: 10}, %{name: "francine", salary: 30}]
```

**Comment by mruoss** [comment]
Or another way of arguing: The two are similar just like Enum.filter() and Enum.find() are similar. You could use Enum.filter() to get Enum.find().

> The only difference is to extract the value from the list on “get”. 

And still it's nice to have them both, each for its use case.

**Comment by josevalim** [comment]
I see. :) Can you provide an example where the default argument would be useful in practice? Is it why you are using `Access.find` in the first place? :)

**Comment by josevalim** [comment]
> Or another way of arguing: The two are similar just like Enum.filter() and Enum.find() are similar. You could use Enum.filter() to get Enum.find().

Unfortunately this argument leads to the slippery slope that all Enum functions belong in Access, which is exactly what I want to avoid. Access provides more focused in functionality, therefore it is fine to provide fewer affordances than Enum.

**Comment by mruoss** [comment]
> I see. :) Can you provide an example where the default argument would be useful in practice? Is it why you are using `Access.find` in the first place? :)

I have been working a lot with kubernetes resources recently. I'm also helping out on the maintenance of k8s and bonny. In k8s resources you find these type of lists very often. You get a resource, you add or modify some environment variables and send it back. 

I had implemented a similar helper [over at the k8s library](https://github.com/coryodaniel/k8s/blob/develop/lib/k8s/resource/named_list.ex). Now I needed a more general version where the key is not "name" that's how I finally ended up here. 

Kubernetes is the only place I have used this. And yes, that's why I've implemented it in the first place, for the default value. Maybe it is fine over at the k8s lib or I can release a separate module with it if it is not of much use to the rest of the community. 

> Unfortunately this argument leads to the slippery slope that all Enum functions belong in Access, which is exactly what I want to avoid. Access provides more focused in functionality, therefore it is fine to provide fewer affordances than Enum.

Fair enough. ;)

**Comment by mruoss** [comment]
> Is it why you are using Access.find in the first place? :)

Thought about it some more. In most of the cases I have used it, I could have used Access.filter(). It's "just" adding an item to the list that's being simplified with Access.find(). But this case can be worked around with update_in(). Thanks for the sparring, I'm closing this.

**Pull request closed without merging**
