### PR TITLE
Use Module.has_attribute?/2

### PR DESCRIPTION
**Pull request by blatyo**
I did a review of where `Module.get_attribute/2` was used in the code base, where `Module.has_attribute?/2` makes more sense and yields more correct behavior.

### CODE REVIEW

**Comment by blatyo** [comment]
I appear to have misunderstood how deleting an accumulated attribute works. It's more like what I'd call `Module.reset_attribute/2`. I'll need to change some of this back because of that.

**Comment by blatyo** [comment]
This PR should be good for review. I'm going to do ExUnit.Case in a separate PR.

**Comment by blatyo** [comment]
The test failure seems to be unrelated to my changes.

**Comment by fertapric** [comment]
Thanks @blatyo! 💜

**Pull request merged**
