### PR TITLE
Add `Enum.split_evenly/1`

### PR DESCRIPTION
**Pull request by Masynchin**
I am currently learning Elixir and using it to write algorithms.
I am amazed with amount of expressive functions that can be use with pipe to make nice-looking algorithm implementation.

This function inspired by this part of the task:
`The first, third and fifth digits, as well as the second and fourth digits are added separately.`

My first attempt to split digits on even and odd positions was:
```elixir
digits
|> with_index()
|> split_with(fn {_n, i} -> rem(i, 2) == 0 end)
|> Tuple.to_list()
|> map(&map(&1, fn {n, _i} -> n end))
```

And second:
```elixir
digits
|> then(fn digits ->
  [take_every(digits, 2), drop_every(digits, 2)]
end)
```

And my think was: "Can it be shorter and more expressive?", and than `Enum.split_evenly/1` was created.
I hope this function is ok to style of elixir and can be useful.

### CODE REVIEW

**Comment by Masynchin** [comment]
It also can be done with recursion:
```elixir
def split_evenly(seq) do
    split_evenly(seq, [[], []], Enum.count(seq))
    |> Enum.map(&Enum.reverse/1)
    |> Enum.reverse()
    |> List.to_tuple()
  end

  defp split_evenly(_, res, 0) do
    res
  end

  defp split_evenly([head | tail], [left, right], n) when rem(n, 2) == 0 do
    split_evenly(tail, [[head | left], right], n - 1)
  end

  defp split_evenly([head | tail], [left, right], n) when rem(n, 2) == 1 do
    split_evenly(tail, [left, [head | right]], n - 1)
  end
```

**Comment by ericmj** [comment]
Thanks for the PR! Please create a thread on https://groups.google.com/g/elixir-lang-core with your proposal so that it can be discussed there.

**Comment by Masynchin** [comment]
> Thanks for the PR! Please create a thread on https://groups.google.com/g/elixir-lang-core with your proposal so that it can be discussed there.

Yep, [done](https://groups.google.com/g/elixir-lang-core/c/ifmKm7HX3Yc)

**Comment by ericmj** [comment]
I will close this PR in the mean time. We can reopen depending on the outcome of the elixir-lang-core discussion. Thanks for creating the thread!

**Pull request closed without merging**
