### PR TITLE
Hint function may be private if not available

### PR DESCRIPTION
**Pull request by lpil**
Closes https://github.com/elixir-lang/elixir/issues/4405

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! I would like to collect some feedback before taking a decision on this one. /cc @fishcakez @lexmag @whatyouhide

**Comment by fishcakez** [comment]
In Erlang one would normally say the "function is not exported" as shown by the error atom. This means either the function is defined using `defp` or does not exist. I think in this situation we could leave a comment at the end (similar to the other comments) such as

```elixir
"function #{function}/#{arity} is not exported"
```

**Comment by lpil** [comment]
I feel that is more likely to confuse than either "undefined" or "undefined (or private)".

**Comment by whatyouhide** [comment]
Not sure about @fishcakez's error message. Mentioning exporting functions and the such makes sense for Erlang where you specifically have to `-export` functions, but in Elixir-land, we extensively refer to functions as "public" or "private" (that's what `defp` stands for in fact).

That said, I'm personally not sure about this yet. This PR in particular is not intrusive and it doesn't give away any information (e.g., does this function exist as a private function or is it actually non existent?).
Such an error message could be a good compromise because it points to the fact that the function may be private, so users may look into that soon after reading the message.

**Comment by fishcakez** [comment]
@whatyouhide makes perfect sense, to me not exported has hangover connotations that don't translate well.

I definitely think we should improve the message by stating undefined or private but I think we should put the comment in the same place as the other UndefinedFunctionError hints (afterwards). Also the commit message using "not available" has a different meaning in this case so we should change that too.

```elixir
"function #{function}/#{arity} is private or undefined, perhaps .."
```

**Comment by josevalim** [comment]
@lpil let's go with: "undefined or private function #{...}. Did you mean one of:"

Notice I changed "perhaps" to "did you mean" to mirror Mix. We should probably rename the function from `perhaps` to `did_you_mean` as well. Could you please do these changes?

**Comment by lpil** [comment]
Sure thing, as soon as I'm at a computer. :)

**Comment by lexmag** [comment]
I like to have one word that describes "undefined or private" (like "non-exported"), but have no idea what that word is. Thus "undefined or private function" seem okay to me. :bowtie:

Though I like how sounds the wording @fishcakez has proposed:

```
"function #{...} is private or undefined"
```

**Comment by lpil** [comment]
I think I prefer that too.

**Comment by josevalim** [comment]
We can rename the wording BUT we would need to do so for all other messages in there. :)

**Comment by lpil** [comment]
How's that @josevalim ? :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by lpil** [comment]
Hooray! Thanks :D

**Pull request merged**
