### PR TITLE
Update UnicodeData.txt to v9.0.0

### PR DESCRIPTION
**Pull request by eksperimental**
Released on 2016 June 21
http://www.unicode.org/versions/Unicode9.0.0/

Downloaded from http://www.unicode.org/Public/9.0.0/ucd/USourceData.txt

### CODE REVIEW

**Comment by eksperimental** [comment]
the String module mentions:
> The functions in this module act according to the Unicode Standard, version 6.3.0.

Should we update that?
It will also be worth mentioning in the String module that the data is from Unicode 9.0.0

**Comment by josevalim** [comment]
Thank you @eksperimental!

There is an open issue for this and right now I want to do those changes myself and manually. There are more files to update and some manual steps. The plan is to actually document those steps next time I do them, so next time around it is not dependent on me.

**Comment by josevalim** [comment]
Yes, we should update that too. One more thing to add to my todo list of things to update when updating unicode. :)

**Comment by eksperimental** [comment]
good to know it's on your TODO list.
thank you

**Pull request closed without merging**
