### PR TITLE
allow ! for access on maps

### PR DESCRIPTION
**Pull request by vans163**

### CODE REVIEW

**Comment by ericmj** [comment]
Please send proposal to the elixir-lang-core mailing list.

**Comment by josevalim** [comment]
Yes, please send this particular proposal to core but it is very likely it will be refused given you can use both `map.foo` syntax and `Map.fetch!(map, :foo)`. I don't think we need a third way.

**Comment by vans163** [comment]
The problem with map.foo is it expects an atom.  You cannot sanely have uuids as atoms.  There is a similar problem in another part of access, I remember mentioning it on IRC but cant remember now.

**Comment by whatyouhide** [comment]
@vans163 this is the reason why this discussion doesn't belong in the issue tracker: it's a discussion :) Please let's continue on the [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core) mailing list. 👍

**Pull request closed without merging**
