### PR TITLE
Improve merge exception texts inside exunit callbacks

### PR DESCRIPTION
**Pull request by azhi**
Considering this case:

```elixir
defmodule CallbacksCase do
  use ExUnit.Case

  setup do
    {:ok, :something}
  end

  test "nothing", do: assert true
end
```

Before this commit exunit callbacks return value merger was failing with

`(RuntimeError) expected ExUnit callback in CallbacksCase to return :ok or
{:ok, keyword | map}, got :something instead`.

But callback didn't return `:something`, it returned `{:ok, something}`.

After this commit same case will fail with

`(RuntimeError) expected ExUnit callback in CallbacksCase to return :ok or
{:ok, keywords | map}, got {:ok, :something} instead`.

This behaviour is achieved by moving all the checks to `__merge__/3` function.
`context_merge/3` now only works with maps and raises 'reserved keys' errors.

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! Instead of having two messages, can we simply always show the full result in the first message? This way we don't need to keep both of them and it shouldn't be confusing for users.

**Comment by azhi** [comment]
Yeah, i was thinking about it, but couldn't come up with clean implementation.

I see two possible options here:

* change `context_merge/3` so it accepts `{:ok, data}` as a third argument instead of plain `data`, and then use this `return_value` for raising an exception.
* leave `context_merge/3` params as it is, but manually wrap `data` with `{:ok, data}` when calling `raise_merge_failed!/2`

Both seems not clean enough for me, so i decided to create a separate message :).

Anyway, updated the PR with first option (change `context_merge/3` so it accepts `{:ok, data}`), let me know if we should use something different.

**Comment by josevalim** [comment]
I think the second option would be better as we wouldn't need to match on `{:ok, _}` on all places? Otherwise, we could keep things as is but merge `__merge__` and `context_merge` into a single function to avoid the multiple matching.

**Comment by josevalim** [comment]
Which one do you prefer?

**Comment by azhi** [comment]
> Otherwise, we could keep things as is but merge __merge__ and context_merge into a single function to avoid the multiple matching.

I think this one would be the best solution. Will implement it shortly.

**Comment by azhi** [comment]
Ok, updated the PR, how does it look?

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
