### PR TITLE
Give helpful error message if a string is used to name a GenServer / Supervisor

### PR DESCRIPTION
**Pull request by alecspopa**
Hi, this is my second PR related to #3932.
It should add helpful messages for GenServer and Supervisor.
Thanks!

### CODE REVIEW

**Comment by michalmuskala** [comment]
I started thinking. Given in how many places we map the elixir-style process name to the erlang-style name (in standard library, and even more in 3rd party libraries), should we provide one function in the standard library to do this?

**Comment by josevalim** [comment]
@michallepicki we already do as `GenServer.whereis/1`. This is slightly different because we need to pass the shape "unchanged" so it is invoked later on inside the process.

**Comment by whatyouhide** [comment]
Looks perfect to me! Thanks a lot @alecspopa 💟 :)

**Comment by alecspopa** [comment]
Thanks for merging @whatyouhide :)

**Pull request merged**
