### PR TITLE
Provide a more fitting example of Kernel.then

### PR DESCRIPTION
**Pull request by peaceful-james**

### CODE REVIEW

**Comment by josevalim** [comment]
Can you please explain why it is more fitting? Thank you.

**Comment by Eiji7** [comment]
@josevalim This PR was mentioned in his comment on forum:
https://elixirforum.com/t/elixir-v1-12-0-rc-0-released/38667/32?u=eiji

**Comment by josevalim** [comment]
I see.

it is the first argument but there is no straightforward way to pipe into operators besides using Kernel.*, which is not everyone’s cup of tea.

we can add more examples though, but we should keep the current one.

thanks.

**Comment by wojtekmach** [comment]
This is super anecdotal but I find then/1 especially useful for stuff like: `|> then(&File.write!("foo.txt", &1)`, `|> then(&IO.puts(:stderr, &1)`, etc.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
