### PR TITLE
Add is_tuple/2

### PR DESCRIPTION
**Pull request by ericmj**
Related to #10823.

### CODE REVIEW

**Comment by josevalim** [comment]
@ericmj should we wait until we also add the type stuff too? The reason I ask is because we are only adding this if it will benefit the typing information. If it wasn't for that, we probably wouldn't. So it would be nice to have the whole story on a PR. It is also fine to wait until we tackle this. :)

**Comment by ericmj** [comment]
Yeah, we can wait until #10820 is merged.

**Comment by josevalim** [comment]
@ericmj the other thing is that, if we want to have it as a macro, then we don't actually need `is_tuple(foo, 2)`, we just need to make the type checker smarter and point users to the right direction: which is either to pattern match or add a tuple_size, where the pattern matching is preferred. In fact, the original issue that lead to this issue would likely work better as a pattern. :) So now I am thinking we might not need this at all - especially because it should be discouraged compared to pattern matching, which is likely more efficient?

**Comment by ericmj** [comment]
@josevalim I still want this because it's more clear to point users to `is_tuple/2` when they already use `is_tuple/1` rather than tell them to add `tuple_size(tuple) == ...` or refactor to a pattern match.

**Comment by josevalim** [comment]
@ericmj sure, we can discuss later. My point though is that, for "v1", I think I would prefer to tell users to try pattern matching and collect feedback. Depending on the nuisance, then we can add is_tuple/2. I just don't think our starting point should be is_tuple/2.

**Comment by ericmj** [comment]
Okay, that makes sense. I will close this for now, we can always resurrect it later.

**Pull request closed without merging**
