### PR TITLE
Simplify specs in Range by introducing t:limit/0

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
There is a second PR doing a copy-edit of all specs and docs once this one is merged

**Comment by josevalim** [comment]
First and last were already public types, so I would prefer to not remove them. Thanks.

**Comment by eksperimental** [comment]
> First and last were already public types, so I would prefer to not remove them. Thanks.

Sorry, they were not
https://hexdocs.pm/elixir/Range.html#types

**Comment by josevalim** [comment]
Ah, so I added it recently? Makes sense.

**Comment by eksperimental** [comment]
> Ah, so I added it recently? Makes sense.

This makes me think if we should be adding the `@since` attribute to public and opaque types.

I know they are not part of the API but it can be useful to keep track of when they had been introduced

**Pull request merged**
