### PR TITLE
Include lib/*/lib files in Precompiled.zip

### PR DESCRIPTION
**Pull request by wojtekmach**
Ref https://github.com/elixir-lang/elixir/issues/6562#issuecomment-333213263

I tested it by both manually unpacking and via `asdf`. cc @ericmj

### CODE REVIEW

**Comment by josevalim** [comment]
Can you please run "make zips" and let us know how much bigger is the
precompiled one?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
numbers below for zip and unzipped directory:

```
# master
du -sh Precompiled-v1.6.0-dev.zip
3,8M	Precompiled-v1.6.0-dev.zip
du -sh release/
7,0M	release/
```

```
# wm-include-source
du -sh Precompiled-v1.6.0-dev.zip
4,5M	Precompiled-v1.6.0-dev.zip
du -sh release/
 10M	release/
```

**Comment by josevalim** [comment]
That sounds like a price worth paying, yeah. :) Thanks!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
