### PR TITLE
Update applications built by mix new

### PR DESCRIPTION
**Pull request by josevalim**
* Include a link to ExDoc and update links to hexdocs.pm
  * Generate @moduledoc and @doc with doctests
  * For --sup projects, move the application module to Mod.Application

/cc @elixir-lang/elixir

### CODE REVIEW

**Comment by josevalim** [comment]
I would love to have feedback from everyone, not only code wise, but also if this is the best way to move forward. :)

**Comment by fishcakez** [comment]
My only concern is I have seen quite a few empty MyApp modules for applications with supervision trees. I am unsure how I feel about that. I would put my application behaviour in `MyApp.Application` so like the change instinctively.

**Comment by lexmag** [comment]
👍 for showing doctests, but on `MyApp.Application` change I feel mildly 👎. Personally I will be moving its content back to `MyApp` every single time I believe.

**Comment by fishcakez** [comment]
`MyApp` is likely to be part of the public API and `MyApp.Application` the internals for setting up the supervisor tree. I think it is very rare to have code in `MyApp.Application` that would require use from the public API. These are quite different concerns and beneficial to separate in my opinion. Is there a reason to move it back, except for habit?

If the main goal is to prevent `MyApp.start/2` in autocomplete then it could have `@doc false`. Similarly would a `MyApp.Application` have `@moduledoc false`?

**Comment by josevalim** [comment]
@fishcakez `@doc false` does not solve `import`. You will still end-up with importing `start/2` into the user namespace. I am :+1: for adding `@moduledoc false` to the application one.

**Comment by lexmag** [comment]
> Is there a reason to move it back, except for habit?

I think about private "business" applications, mainly, which have no public API.
For comrades who write such application this change will mean empty `MyApp` most of the time.
Even in case I need to extract supervisor tree it usually goes to `MyApp.Supervisor` but `start/2` stays in main module.

I think `@doc false` will help a lot, but:

> You will still end-up with importing start/2 into the user namespace.

That's why I believe that wildcard `import MyApp` is quite intrusive and we should educate more about using `:only`. _(import only stuff you actually need)_ :bowtie:

**Comment by fishcakez** [comment]
> I think about private "business" applications, mainly, which have no public API.
> For comrades who write such application this change will mean empty MyApp most of the time.
> Even in case I need to extract supervisor tree it usually goes to MyApp.Supervisor but start/2 stays in main module.

Ah that's a good point. I am still locked in the Erlang mind set of `myapp_app` where putting it in `myapp` never happen. I am not sure it matters not having `MyApp`. I think it is of benefit for others if the application file is always namespaced the same because anyone immediately knows where to find the top of the supervision tree.

**Comment by josevalim** [comment]
> For comrades who write such application this change will mean empty MyApp most of the time.

Which is fine. Such applications are at the end of the dependency tree so having an empty module causes less impact than having a library, that will eventually be used as a dependency, expose things it should not.

I am aware of the trade-off, but I think it is one worth taking. Thoughts?

**Pull request merged**
