### PR TITLE
Silence compilation warnings about the deprecation of Dict

### PR DESCRIPTION
**Pull request by whatyouhide**
Trying to slowly remove the clutter, not sure if worth if for you folks.

### CODE REVIEW

**Comment by eksperimental** [comment]
yes, please. We are leaving a lot of warnings behind sometimes because of all this noise!
so +1

**Comment by josevalim** [comment]
@whatyouhide this looks good but please add a TODO around those changes because we may forget to remove them as they won't emit warnings.

**Comment by whatyouhide** [comment]
@josevalim both functions where I silenced this warning are already marked as to be removed on 2.0, so I think we don't need another TODO. Thoughts?

**Comment by josevalim** [comment]
Sounds good then!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
