### PR TITLE
Fix unquoted range

### LINKED ISSUE #4466: Compiler error when trying to use an unquoted range as a guard clause in a generated function
### Environment

* Elixir version (elixir -v): 1.2.3
* Operating system: Mac OS X El Capitan (10.11.3)

### Current behavior

Metaprogramming: compiler errors when trying to use an unquoted range as a guard clause in a generated function, even when using `Macro.escape` to get an AST representation of said range.

---
Code:
```elixir
defmodule SomeModule do
  range = 1..10
  def in_range(number) when number in unquote(range), do: true
  def in_range(_), do: false
end
```
Result:
`** (ArgumentError) invalid args for operator "in", it expects a compile time list or range on the right side when used in guard expressions, got: 1..10`

Same code as above, but using `unquote(Macro.escape(range))`:
`** (ArgumentError) invalid args for operator "in", it expects a compile time list or range on the right side when used in guard expressions, got: %{__struct__: Range, first: 1, last: 10}`

Same code as above, but using `unquote(Macro.escape(Macro.escape(range)))`:
`** (ArgumentError) invalid args for operator "in", it expects a compile time list or range on the right side when used in guard expressions, got: {:%{}, [], [__struct__: Range, first: 1, last: 10]}`

[This line](https://github.com/elixir-lang/elixir/blob/v1.2.4/lib/elixir/lib/kernel.ex#L2682) in `Elixir.Kernel.SpecialForms.left in right` suggests this last form form should have worked.

PS: the documentation for `Macro.escape` mentions escaping happens recursively until reaching the AST representation of the passed value - however, as seen above that didn't happen (the result of two nested `Macro.escape` calls was different from the one with a single call). Please let me know if you'd like me to open another issue for that.

### Expected behavior

Generated `in_range/1` function when compiling `SomeModule`.

### PR DESCRIPTION
**Pull request by whatyouhide**
This should fix #4466, attacking it from two fronts :) Me and @lexmag worked on this together, that's where the authorship of the commits comes from.

### CODE REVIEW

**Comment by josevalim** [comment]
Will `foo in @range` work? Can we have tests for the cases shown in #4466 if we don't have yet? Thank you! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by whatyouhide** [comment]
@josevalim `foo in @range` will not work, as you still need to escape the range with `Macro.escape/2` (exactly as you'd need to escape maps, for example). Both of these would work:

```elixir
def foo(x) when x in 1..10, do: ...

# and
@range 1..10
def foo(x) when x in unquote(Macro.escape(range))
```

which I think makes sense. We didn't implement tests because there are no tests for [the other case](https://github.com/whatyouhide/elixir/blob/fix-unquoted-range/lib/elixir/lib/kernel.ex#L2849-L2851) as well; I thought I could add tests for both cases in a separate PR, but I can add them to this one if you prefer.

**Comment by lexmag** [comment]
I agree with @whatyouhide, we should not make `in unquote(range)` work (read a special case) if we don't allow the following:
```elixir
defmodule Qwe do
  range = 1..10
  def qwe?(arg) do
    arg in unquote(range)
  end
end
#=> ** (CompileError) iex: invalid quoted expression: 1..10
```
Same applies to maps:
```elixir
  map = %{}
  def qwe?(arg) do
    arg == unquote(map)
  end
#=> ** (CompileError) iex: invalid quoted expression: %{}

  map = %{}
  def qwe?(arg) when arg == unquote(map) do
    :ok
  end
#=> ** (CompileError) iex: invalid quoted expression: %{}
```

**Comment by whatyouhide** [comment]
@josevalim ok, completely missed your question. Yes, `foo in @range` will work fine since the `left in right` macro will receive `{:@...` and expand it in the `__CALLER__`, which is a guard, so `..` will expand to the escaped `%Range{}` and everything will be easy peasy. 😺

**Comment by whatyouhide** [comment]
@josevalim & @lexmag, I added a couple of tests for errors with `in/2` when used in guards. I added these tests in `kernel/errors_test.exs` because that is where most of `in/2` is tested. Let me know what you think! 😺

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
