### PR TITLE
Fix documentation code block

### PR DESCRIPTION
**Pull request by max-vogler**
Before:
image

After:
image

### CODE REVIEW

**Comment by max-vogler** [comment]
Does it make sense to apply this to the 1.3 branch as well?

**Comment by josevalim** [comment]
The documentation built for master does not have this error: http://elixir-lang.org/docs/master/elixir/Module.html

We probably won't backport it, it is a minor detail and master has it fixed anyway. :)

**Comment by max-vogler** [comment]
image

I see! Thanks for the quick reply @josevalim

**Comment by josevalim** [comment]
@max-vogler :heart:

**Pull request closed without merging**
