### PR TITLE
Add file information to the dispatches on the source manifests

### PR DESCRIPTION
**Pull request by ggcampinho**
As discussed in #6629, this makes possible identify dispatches that occur in external sources

### CODE REVIEW

**Comment by ggcampinho** [comment]
It was necessary to add file information for all the dispatches because at the moment that we are adding this, it's impossible to distinguish external sources from the regular source via the environment variable. Another option is to add some information to the environment make it possible to distinguish this without accessing the attributes stored in the ETS during the expansion, I don't know if the messages to the lexical genserver with the filenames have a considerable impact on the performance.

Also, it's possible to keep the location consistent in the manifest, always having the file, but I kept compatibility to see what you prefer.

**Comment by josevalim** [comment]
@ggcampinho this is great. Thanks for exploring all of those different solutions.

Here are some ideas so we do not have to always store the file.

1. What if we pass the initial file when we [start the lexical tracker here](https://github.com/elixir-lang/elixir/blob/53a78833781c3102ae32bf2ddd4dd4fe0d6ae948/lib/elixir/src/elixir_lexical.erl#L16) and then the lexical tracker compares the file it has with the one it receives and then add it accordingly?

2. Another idea, which would be more efficient, would be to let the tracker know it is in "a special area". We would change [the code around here](https://github.com/elixir-lang/elixir/blob/53a78833781c3102ae32bf2ddd4dd4fe0d6ae948/lib/elixir/src/elixir_def.erl#L119-L130) to the following:

```erlang
  {File, MetaLocation} =
    case retrieve_location(Location, ?key(E, module)) of
      {F, L} ->
        {F, [{line, Line}, {location, {F, L}} | Generated]};
      nil ->
        {nil, [{line, Line} | Generated]}
    end,

  run_with_location_change(File, E, fun(EL) ->
    assert_no_aliases_name(MetaLocation, Name, Args, EL),
    assert_valid_name(MetaLocation, Kind, Name, Args, EL),
    store_definition(MetaLocation, Kind, DoCheckClauses, Name, Arity,
                     LinifyArgs, LinifyGuards, LinifyBody, ?key(E, file), EL)
  end.

run_with_location_change(nil, E, Callback) ->
  Callback(E);
run_with_location_change(File, #{file := File} = E, Callback) ->
  Callback(E);
run_with_location_change(File, E, Callback) ->
  EL = E#{file := File},
  Tracker = ?key(E, lexical_tracker),

  try
    elixir_lexical:set_file(Tracker, File),
    Callback(E)
  after
    elixir_lexical:reset_file(Tracker)
  end.
```

This is just a reference, for example those functions do not exist in the `elixir_lexical`, but I believe it shows the direction we could move to.

I think the second approach would be the most efficient by far and require the least changes, so I am more inclined towards it. What do you think?

**Comment by ggcampinho** [comment]
@josevalim I thought on something similar, but I was afraid that this was restricting the parsing of the whole file to be sequential, and because of this I suggested to add some kind of flag to the environment that is passed to expand functions. If this is not a problem, I'm happy to implement this approach!

Another possibility that solves this issue is to call something like `elixir_lexical:set_file(Tracker, Mfa, File)` and send the mfa in the environment in the `record_import`/`record_remote`, but it probably complicate things and it's not necessary.

**Comment by josevalim** [comment]
@ggcampinho it is already sequential so we can go ahead with this assumption.

> Another possibility that solves this issue is to call something like elixir_lexical:set_file(Tracker, Mfa, File) and send the mfa in the environment in the record_import/record_remote, but it probably complicate things and it's not necessary.

That would work but in truth this is all coupled together and there is no reason for decoupling because that's the tracker only use case. :) So I think we can go with the simplest that works.

**Comment by ggcampinho** [comment]
@josevalim Done! I agree that simplest is better 🙂

**Comment by ggcampinho** [comment]
Is it necessary to change the manifest version, when the data changes?

https://github.com/ggcampinho/elixir/blob/master/lib/mix/lib/mix/compilers/elixir.ex#L4

**Comment by ggcampinho** [comment]
I just realized that all the xref tool will break with this change, fixing it

**Comment by ggcampinho** [comment]
I did the minimum changes necessary on `Xref` to make it work as it is today, the other PR should handle the changes necessary to present the correct files

**Comment by josevalim** [comment]
@ggcampinho this looks perfect, thank you. I don't think we need to change the manifest file because the top level structure is the same and Elixir will recompile the code if you change versions.

Plus we already changed it once for v1.6. :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
