### PR TITLE
Added @impl to the Mix.Task example.

### PR DESCRIPTION
**Pull request by linjunpop**

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by linjunpop** [comment]
Should we also make all the `@impl` in the documentation explicitly? Currently, most of them are using  `@impl true`.

If so, I can submit another PR to change those.

**Comment by josevalim** [comment]
I actually prefer @impl true because 99% of the cases you have only one
behavior and @impl true has no ambiguity. So we should likely stick with
@impl true here too.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by linjunpop** [comment]
👌

**Pull request merged**
