### PR TITLE
Docs: change wording about WithClauseError

### PR DESCRIPTION
**Pull request by schnittchen**
This way I hope people will not fall into the trap that no else has different error semantics, as mentioned above in the docs.

### CODE REVIEW

**Comment by josevalim** [comment]
Maybe we should be clearer then: "If an `else` block is used and there is no matching clause, ...". Thoughts?

**Comment by schnittchen** [comment]
I'm all for clarity.

Unless somebody comes up with something better, I will change and push to that wording in a couple of hours.

**Comment by whatyouhide** [comment]
Agreed with @josevalim. Also please use the word "clause" over "condition" 💟

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
