### PR TITLE
Use explicit function names in DocTest tests

### PR DESCRIPTION
**Pull request by eksperimental**
Additionally be clearer on when the return value is wrong.

### CODE REVIEW

**Comment by josevalim** [comment]
test_fun is clearer to me. :)

**Comment by lexmag** [comment]
I personally don't really like `test_fun1` and `test_fun2` for the fact that they are too similarly looking names (differ only by 1 symbol). 
Not sure if like `one` and `two`, since they imply some sort or ordering. I usually prefer to use `foo`, `bar`, etc. :bowtie:

**Comment by eksperimental** [comment]
This comes from this proposal I'm working on for DocTests,
https://github.com/eksperimental/elixir/commit/8928d9e6fffa97ccce5dba84c159298db3f1bebf#diff-5bf76a905e4c4c5ef22f8dfcf379bdd1R148

and I had to create more functions as I'm testing thoroughly all import options and new options as well.
The `test_fun*` approach was not scalable.

Maybe we could use `return_1()` as in my example here https://github.com/eksperimental/elixir/commit/8928d9e6fffa97ccce5dba84c159298db3f1bebf#diff-5bf76a905e4c4c5ef22f8dfcf379bdd1R148

**Comment by josevalim** [comment]
Given that it is named `one` and it returns the integer `1`, then I would prefer that to `foo` or `bar`.

**Comment by lexmag** [comment]
I didn't check their return. 🙈
Yeah, `one` is better in that context.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
