### PR TITLE
Add guard to OptionParser.split/1

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by ericmj** [comment]
Looks like this is already handled by `do_split`.

**Comment by eksperimental** [comment]
Well, it is actually caught by `String.trim_leading/2`, which is caught by `Strim.replace_leading/3`

```
iex(1)> OptionParser.split(:atom)
** (FunctionClauseError) no function clause matching in String.replace_leading/3
    (elixir) lib/string.ex:637: String.replace_leading(:atom, " ", "")
    (elixir) lib/option_parser.ex:489: OptionParser.split/1
```

**Comment by ericmj** [comment]
Okay, then it makes sense to have the guard. Should we add the same to `String.trim_leading/2`?

**Comment by eksperimental** [comment]
yes, I already check but there is a lot of guards missing in the String module. So I will probably fix them all in one go

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
