### PR TITLE
Mix: add comma at the end of worker()

### PR DESCRIPTION
**Pull request by eksperimental**
make it easy to duplicate the worker line

### CODE REVIEW

**Comment by josevalim** [comment]
@pragdave I remember you once said (or I read from something you wrote) that you like the optional comma at the end of lists because it indicates something that may change in the future. Does this change fit your description? What do you think?

**Comment by whatyouhide** [comment]
IIRC @pragdave mentioned this in Programming Elixir!

**Comment by pragdave** [comment]
My thinking is that there are two kinds of list—those that are
predetermined, and those that may change over time.

An example of the first is the list of suits in a deck of cards. Here, I’d
write the list

suits = [ "clubs", "diamonds", "hearts", "spades" ]

An example of the second kind if a list of programming languages:

languages = [ "cobol", "ruby", "elixir", ]

Here, I intended to indicate that the list is not necessarily final—I may
want to extend it in future. So I leave the trailing comma to flag the fact.

I did something similar just today. I’m writing a DSL that handles
graphics, and it has a number of verbs. Right now, I’ve implemented just a
handful, to the list is terminated by a comma, just to flag the fact.

A secondary consideration: I tend to write open-ended lists vertically:

languages = [   "cobol",   "ruby",   "elixir",]

Having the trailing comma makes it easier to add a new entry anywhere in
the list—all lines look the same.

languages = [
  "cobol",
  "fortran",
  "ruby",
  "elixir",
  "snobol",
]

Is that what you were asking? :)

Dave
​

**Comment by josevalim** [comment]
Yes, that was it. Thanks!

**Pull request merged**
