### PR TITLE
Document Inspect.inspect/2

### PR DESCRIPTION
**Pull request by wojtekmach**

### CODE REVIEW

**Comment by josevalim** [comment]
Actually, we should add a note  that this function shouldn't be invoked directly. If you  want the result of inspect, one should prefer Inspect.Algebra.to_doc, since that one will handle Inspect.Opts properly.

**Comment by wojtekmach** [comment]
Good point. I guess `opts` should be `Inspect.Opts.t`, not `keyword`, too, right? I'll make both changes shortly.

**Comment by josevalim** [comment]
Yes, indeed.

>

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
