### PR TITLE
Update erlang.org links

### PR DESCRIPTION
**Pull request by eksperimental**
Consistently use https://erlang.org
See also ExDoc PR: https://github.com/elixir-lang/ex_doc/pull/1335

### CODE REVIEW

**Review by ericmj — APPROVED** [review]

**Comment by eksperimental** [comment]
There are some issues in the erlang.org site regarding redirection and usage of https, that I would like to report. Does anybody know what its the best place for this?

**Comment by josevalim** [comment]
I would say their issues tracker on GitHub.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by eksperimental** [comment]
> I would say their issues tracker on GitHub.

I will. Thank you

**Pull request merged**
