### PR TITLE
Take negative years into account in DateTime

### LINKED ISSUE #8032: DateTime.to_iso8601/1 fails on negative DateTime
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
  * Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
  * Elixir 1.7.1 (compiled with Erlang/OTP 21)

* Operating system: 
  * Debian Stretch, 9.5

### Current behavior

With Elixir v1.7 `Calendar.ISO` was extended to allow negative years, but strings representing negative years produced with  `DateTime.to_iso8601/1` are not a valid input to `DateTime.to_iso8601/1`.

```elixir
iex(1)> ts = -277705116800
-277705116800
iex(2)> datetime = DateTime.from_unix!(ts)
#DateTime<-6831-11-16 09:46:40Z>
iex(3)> iso = DateTime.to_iso8601(datetime)
"-6831-11-16T09:46:40Z"
iex(4)> iso = DateTime.from_iso8601(iso)
{:error, :invalid_format}
```

### Expected behavior

Expected behaviour would be that `DateTime.from_iso8601/1` accepts any output produced with `DateTime.to_iso8601/1`, as is the case for dates with a positive year.

### PR DESCRIPTION
**Pull request by josevalim**
Closes #8032.

### CODE REVIEW

**Comment by fertapric** [comment]
I was also working on this fix and I got stuck thinking about these cases:

```elixir
iex(3)> DateTime.from_iso8601("0000-01-01T00:00:07+10:00")
{:ok, #DateTime<-0001-12-31 14:00:07Z>, 36000}
iex(4)> DateTime.from_iso8601("-0001-01-01T00:00:07-10:00")
{:ok, #DateTime<-0001-01-01 10:00:07Z>, -36000}
iex(5)> DateTime.from_iso8601("-0001-01-01T00:00:07+10:00")
{:ok, #DateTime<0000-12-31 14:00:07Z>, 36000}
```

**Comment by josevalim** [comment]
@fertapric good catch! Those cases seem to work here and I would love to add them to the suite. Can you please prepare a PR so we merge it after this one?

**Comment by fertapric** [comment]
Sure!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by fertapric** [comment]
I just wanted to double check my test assertions, because some are failing with the current implementation:

```elixir
iex(1)> DateTime.from_iso8601("0000-01-01T01:22:07+10:30")
#DateTime<-0001-12-31 14:52:07Z>

iex(2)> DateTime.from_iso8601("-0001-01-01T01:22:07+10:30")
#DateTime<-0002-12-31 14:52:07Z>

iex(3)> DateTime.from_iso8601("-0001-01-01T01:22:07-10:30")
#DateTime<-0001-01-01 11:52:07Z>

iex(4)> DateTime.from_iso8601("-0001-12-31T23:22:07-10:30")
#DateTime<0000-01-01 9:52:07Z>
```

(2) is currently returning `#DateTime<0000-12-31 14:52:07Z>` and (4) `#DateTime<-0002-01-01 09:52:07Z>`. That's because the "extra days" should behave differently if the year is positive and negative.

If the tests are correct, I can work on fixing the current implementation.

**Comment by fertapric** [comment]
PR https://github.com/elixir-lang/elixir/pull/8038

**Pull request merged**
