### PR TITLE
Improve error message on invalid pattern on test

### PR DESCRIPTION
**Pull request by v0idpwn**
Also fixes typo on doc.

### CODE REVIEW

**Comment by ericmj** [comment]
What would the runtime error be if we did not have this check? Since we cannot catch all invalid patterns maybe it will be better to remove this check if the runtime error is good enough?

**Comment by v0idpwn** [comment]
See https://github.com/elixir-lang/elixir/pull/10647 for reference

I'm also not sure about the need for this check, @ericmj, but I think this error message is more precise than the current one.

**Comment by ericmj** [comment]
I guess I am too late for #10647, but I think the original error was better since the `FunctionClauseError` shows the argument that didn't match. It is also preferable since it's a test failure instead of a compilation error which is a better user experience because your other tests will run instead of preventing any tests from running. Maybe we should make it a warning so we get both error messages?

> [...] I think this error message is more precise than the current one.

Agreed.

**Comment by josevalim** [comment]
I like making it a warning with IO.warn. @v0idpwn, can you please update it?

This should work:

       IO.warn(message, Macro.Env.stacktrace(__CALLER__))

**Comment by josevalim** [comment]
In the test you will need to use capture_io!

**Comment by v0idpwn** [comment]
sure

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
