### PR TITLE
Reduce MapSet's space usage in Erlang term format

### PR DESCRIPTION
**Pull request by X4lldux**
MapSet is internally represented as a map with keys as set's elements and stub values of `true`, like: `%{ :key => true }`.  When MapSet, in it's current format, is written to a DETS file, or serialized using `:erlang.term_to_binary/2`, it's **two times** as big as the smallest possible case! If the stub value is replaced with an empty list, to a format `%{ :key => [] }`, there is a significant space reduction, see: 

```Elixir
iex(1)> ml = for i<- 1..1_000_000, do: {i,[]}, into: %{}; :ok
:ok
iex(2)> mt = for i<- 1..1_000_000, do: {i,true}, into: %{}; :ok
:ok
iex(3)> {:ok, table_ml} = :dets.open_file(:disk_storage_ml, [type: :duplicate_bag]) 
{:ok, :disk_storage_ml}
iex(4)> {:ok, table_mt} = :dets.open_file(:disk_storage_mt, [type: :duplicate_bag])
{:ok, :disk_storage_mt}
iex(5)> size_ml = File.lstat!("disk_storage_ml").size
5432
iex(6)> size_mt = File.lstat!("disk_storage_mt").size
5432
iex(7)> :dets.insert_new(:disk_storage_ml, {1, ml})
true
iex(8)> :dets.insert_new(:disk_storage_mt, {1, mt})
true
iex(9)> size_ml_dets = File.lstat!("disk_storage_ml").size        
6004693
iex(10)> size_mt_dets = File.lstat!("disk_storage_mt").size        
12004693
iex(11)> size_ml_etf = ml |> :erlang.term_to_binary |> byte_size
5999241
iex(12)> size_mt_etf = mt |> :erlang.term_to_binary |> byte_size
11999241
iex(13)> size_ml_dets/size_mt_dets
0.5001954652234755
iex(14)> size_ml_etf/size_mt_etf
0.49996837299959224
```

Since only keys from the map are of any importance, changing from `true` to `[]`,  doesn't change any of the functionality. MapSet is an opaque type, so nobody should be using it's internal format either.

This changes only how much space MapSet uses when it's serialized to ETF format, no RAM usage changes were observed.

### CODE REVIEW

**Comment by michalmuskala** [comment]
Should it be a concern if a map serialised with the old format, can be deserialized with the new version?

**Comment by lexmag** [comment]
@michalmuskala good question! I think it is fine as we don't use that value in any way.

**Comment by X4lldux** [comment]
Good catch! I think this might be a problem only when comparing old and new format with `MapSet.equal?/2`. But just in case, tomorrow I'll check all functions accepting two maps.

**Comment by X4lldux** [comment]
Only `MapSet.equal?/2` would give a wrong output when passing an old and a new format. It basically is a `===` operator. Everything else operates strictly on keys.
We can either:
* implement `equal?/2` so it compares only by keys (which unfortunately will be *significantly* slower for large sets),
* postpone this to v2.0 (or maybe v1.5 would be ok) but add a warning (in release note and docs) that an internal format has changed and a simple `MapSet.to_list(old_map) |> MapSet.new` is needed when deserializing MapSet in old format - and leave `equal?/2` as is: simple and fast,
* discard this entirely.

My, very biased, vote goes to option 2.

**Comment by josevalim** [comment]
I would go with 2 as well since the users likely to run into this issue are also the users that would benefit most from this change.

**Comment by josevalim** [comment]
@fishcakez what are your $0.02 here?

**Comment by fishcakez** [comment]
I agree with @josevalim. This doesn't mention serializing/deserializing speed. I think it will be a small serializing but a very significant deserializing improvement. We should measure.

Should we provide a downgrade capability from 2.0 -> 1.* from 1.5? I think using a different key would be more efficient (it is opaque) and cause a crash when incompatible - instead of an incorrect result.

**Comment by X4lldux** [comment]
```
Name                             ips        average  deviation         median
serialize empty list           22.53       44.38 ms     ±3.77%       44.15 ms
serialize true                 18.35       54.51 ms     ±3.05%       54.46 ms
deserialize empty list          6.07      164.77 ms     ±7.63%      158.50 ms
deserialize true                4.14      241.48 ms     ±4.71%      235.95 ms
```
full test at https://gist.github.com/X4lldux/173c59a1d838d65c1028d935bf71f75b

**Comment by josevalim** [comment]
Yes, let's call it `:data` instead of `:map` for the inner key. :)

**Comment by OvermindDL1** [comment]
Just want to note here since I was asked on discord, the reason this gives an improvement is that `[]` is the BEAM's `nil` type, unlike Elixir's `nil` which is just an atom and thus is larger as atoms are stored as strings in the external format.  The BEAM's `nil` (`[]`) type is documented at:  http://erlang.org/doc/apps/erts/erl_ext_dist.html#id100749

**Comment by josevalim** [comment]
@X4lldux please let us know when you change the key name from `:map` to `:data`. :)

**Comment by X4lldux** [comment]
@josevalim done :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
