### PR TITLE
docs: document unexpected ++ behavior

### PR DESCRIPTION
**Pull request by polvalente**

### CODE REVIEW

**Comment by v0idpwn** [comment]
I'd argue its documented above: https://github.com/elixir-lang/elixir/blob/2df03b7b7941b1c7bfdda9f663b29e99371d81db/lib/elixir/lib/kernel.ex#L1528

But the example is nice. I think it would also be good to have an example where the left-hand side is not a list.

**Comment by v0idpwn** [comment]
I'd argue its documented above: https://github.com/elixir-lang/elixir/blob/2df03b7b7941b1c7bfdda9f663b29e99371d81db/lib/elixir/lib/kernel.ex#L1528

But the example is nice. I think it would also be good to have an example where the left-hand side is not a list (ArgumentError scenario)

**Comment by v0idpwn** [comment]
Actually, the example from https://github.com/elixir-lang/elixir/blob/2df03b7b7941b1c7bfdda9f663b29e99371d81db/lib/elixir/lib/kernel.ex#L1541 shows the same situation as yours (but I think yours is clearer)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
