### PR TITLE
Treat warnings as errors

### PR DESCRIPTION
**Pull request by michalmuskala**

### CODE REVIEW

**Comment by josevalim** [comment]
@michalmuskala I think we should always enable them then.

**Comment by josevalim** [comment]
> Edit2: By doing so, the CI will not be allowed to test soft-deprecated code as they emit warnings ? 🤔 that is bad

This covers only compilation, we should be fine for the tests themselves!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by zkessin** [comment]
there should be a way to say only in my code and not in mix dependencies

**Comment by fertapric** [comment]
@zkessin I think this is only applied to the Elixir codebase. Personal Elixir projects are not affected by this PR.

**Comment by zkessin** [comment]
Thanks

**Pull request merged**
