### PR TITLE
Make Application a behaviour (instead of using :application)

### PR DESCRIPTION
**Pull request by whatyouhide**
Adds what described in #4546.

Since we already define `GenServer` as a behaviour (with a bunch of `@callbacks`) and document such callbacks, changing the behaviour when `use GenServer` is called from `:gen_server` to `GenServer` should be just a matter of actually changing that line :).

`Supervisor` (which is mentioned in the issue) needs no work for now as far as I understand, as we already defines the behaviour and uses `@behaviour Supervisor` when `use Supervisor` is called.

As for `Application`, I added two `@callback` definitions to it and documented them; also, I changed `use Application` so that it calls `@behaviour Application` instead of `@behaviour :application`. Erlang's `application` module only defines `start/2` and `stop/1` as callbacks ([here](https://github.com/erlang/otp/blob/maint/lib/kernel/src/application.erl#L64-L68)), but documents a few others (`prep_stop/1`, `config_change/3`, and `start_phase/3`); what should we do with them? Add them as `@optionalcallback` as soon as we have that available?

### CODE REVIEW

**Comment by josevalim** [comment]
@fishcakez please sanity check and merge it you agree. :)

@whatyouhide  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by fishcakez** [comment]
The Application part is good but unfortunately with the GenServer change we lose the optional callback information for `format_status/2`. I don't think we should make that change until we have #4037.

**Comment by whatyouhide** [comment]
@fishcakez ah, good point. I updated the PR title and removed the `GenServer`-related commit. I will take care of submitting it again (and adding the `format_status/1` optional callback to `GenServer`) once #4037 is in.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
