### PR TITLE
Add IEX helper to recompile all files without exiting IEX session

### PR DESCRIPTION
**Pull request by mgwidmann**
I find myself (and I suspect others) exiting IEx and starting back up `iex -S mix`. IEx already has a `c "path/to/file.ex"` to recompile a single file, but nothing to just compile everything that has changed. This PR attempts to add that capability. If theres a more preferred way of doing this than please let me know, but I feel this feature is a big productivity enhancement.

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you, we had this discussion in the mailing list. The issue here is that this won't work if the application was already started and you change a running server. You would need to at least stop the current application and start it again.

**Comment by mgwidmann** [comment]
Hmm, I see. Web servers may still need to reload their processes but at least for general module code this does work. I'd rather have this with the caveat that existing processes will still run the old code unless something intentionally reloads the code (like the Phoenix code reloaded or a gen server code change). 

For new learning users this is a big plus, especially while history is still not yet retained between IEx sessions. 

If you prefer I can make it a simpler interface like c(:all) or something. I just hate typing file paths in IEx and I hate exiting and reloading IEx.

**Comment by josevalim** [comment]
The old code lasts one cycle. The next cycle will cause old code to crash
and warnings to be spewed everywhere, causing a lot of confusion (I
assume). :)



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by mgwidmann** [comment]
Actually, I tried this in https://github.com/chrismccord/phoenix_chat_example and it was missing one thing (see last commit), but no errors spewing... Existing connections continued to run the old code as expected and new connections ran the updated code. More importantly the code in the console was always up to date. 

I'd like to at least try it and if it actually does cause too many problems it can be removed later. Its worth the try in my opinion.

**Comment by josevalim** [comment]
In that case it will be fine because the application that defines the processes is Phoenix, so you will see crashes only if you redefine Phoenix internal code. Your application code is called by those processes and therefore will be reloaded transparently.

But in Elixir we should not look only at Phoenix and we need to think how this feature applies and affects all projects. Maybe we should have both recompile and restart helpers. recompile just recompiles the code, restart does the whole dance. We need to think a good way to expose those too to avoid further polluting IEx helpers.

**Comment by josevalim** [comment]
Here is one possible idea:

    m :recompile
    m :restart

where:

```elixir
def m(task, args) do
    task = "iex.#{task}"
    Mix.Task.reenable task
    Mix.Task.run task, args
end
```

This way developers can extend those tasks by providing them under the IEX namespace. Either IEx or Mix would ship with those two tasks by default.

**Comment by mgwidmann** [comment]
Perhaps I'm not understanding...

I'm guessing `m :something` is supposed to rerun a mix task while inside the `iex` shell? You are suggesting that if a user runs `m :recompile`, `m :restart` it should reboot the mix application with the updated code and prevent having to exit the shell and start up again right? Maybe I just don't know the codebase well enough, but if you have `task = "iex.#{task}" then how would developers be able to extend it?

**Comment by josevalim** [comment]
Developers would be able to extend it by implementing "iex.whatever" which would then be called as `m :whatever`

**Pull request closed without merging**
