### PR TITLE
Fix infinite recursion in do_get_file_line

### PR DESCRIPTION
**Pull request by viniciusmuller**
While implementing fancy error reporting for diagnostics, I've noticed when the line was zero, `do_get_file_line` would get stuck into infinite recursion. This PR just tweaks the base case to avoid this issue.

I also think we should not even try to read the file if the line number is zero, even if it is readable.

### CODE REVIEW

**Comment by josevalim** [comment]
Maybe we should handle it in `get_file_line`, before we enter the recursion?

**Comment by sabiwara** [comment]
> I also think we should not even try to read the file if the line number is zero, even if it is readable.

+1, opening the file seems unnecessary in this case 👍

**Review by sabiwara — APPROVED** [review]
LGTM

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
