### PR TITLE
Remove mentions to unless/2 in the case/cond/if guide

### PR DESCRIPTION
**Pull request by sabiwara**
I think it is actually a nice simplification since it's one less thing in the getting started.

I'm also trying to rewrite [the macro guide](https://hexdocs.pm/elixir/macros.html) which is using `unless` as an example, I'm not sure what's the best candidate:
- `if`: less trivial and a tad verbose because will need to write it in terms of `case`
- `&&`: should be straightforward to change the existing guide, and can easily be implemented in terms of `if` (but maybe less "interesting/impressive" than implementing `if`?)
- keep unless?
- something else?

### CODE REVIEW

**Comment by josevalim** [comment]
I think the guide can still use `unless` and we mention it is an exercise? Although implementing the operator `&&` would also work.

**Comment by sabiwara** [comment]
> I think the guide can still use unless and we mention it is an exercise?

Yeah that would work, the only part we'd lose is

> In fact, [unless/2](https://hexdocs.pm/elixir/Kernel.html#unless/2) in Elixir is implemented as a macro:

or perhaps we can say "used to have one but has been deprecated".
But the "impact" might be lesser than showing we're able to implement a first class construct from the language.

**Comment by josevalim** [comment]
So let’s go with &&?

**Comment by sabiwara** [comment]
I went with a different approach and just changed the conclusion using `if`: [224b861](https://github.com/elixir-lang/elixir/pull/13852/commits/224b861335bd31a13d26316708af185ef16c44c6)

The problem with `&&` is to find a good name: if we call this `macro_and` it would be confusing, and `and` is not a simple one-liner that can be implemented with an `if`.

**Review by josevalim — APPROVED** [review]

**Pull request merged**
