### PR TITLE
System.otp_release now includes the full release number

### PR DESCRIPTION
**Pull request by eksperimental**
Now it returns for example "21.0.6" instead of "21" as before.

### CODE REVIEW

**Comment by eksperimental** [comment]
I think we are "inheriting" this limitation from OTP, since for whatever reason they have to only show the MAJOR number in their version.
We can do better than that, as @fishcakez already implemented in his Dialyze project, and @ericmj took it and Hex is using this piece of code.

**Comment by eksperimental** [comment]
This is a series of commits, but they build one on top of another,
following PRs make use of this function to improve the messages when running "elixir --version", therefore improving the bug hunting

**Comment by josevalim** [comment]
We had this discussion in the past and we decided that Elixir should follow Erlang/OTP versioning schema. They did have a rationale for not including the patch version and we wanted to respect that. If they changed it, then we will follow that too.

**Comment by eksperimental** [comment]
I see.
So will there be a mechanism to find out what is the MINOR AND PATCH OTP version?
I find it a bit vague to only  have the MAJOR version.

**Comment by ericmj** [comment]
> So will there be a mechanism to find out what is the MINOR AND PATCH OTP version?

Probably not for the reason @josevalim already stated.

The code from the dialyze project is the recommended way to get the minor and patch information.

**Comment by fishcakez** [comment]
> The code from the dialyze project is the recommended way to get the minor and patch information.

That project does this so for path uniqueness, i.e. so that we have separate PLTs when erlang version changes as a different version will have different path. Of course this breaks when versions match but path doesn't. Majority of the time the minor/patch handles this.

**Comment by adrianomitre** [comment]
For the record, after the backward-compatible sibling PR https://github.com/elixir-lang/elixir/pull/10299 was rejected, I decided to encapsulated its functionality into a little lightweight library called [otp_version](https://hex.pm/packages/otp_version).

**Pull request closed without merging**
