### PR TITLE
Dogfood new defoverridable syntax

### PR DESCRIPTION
**Pull request by samphilipd**

### CODE REVIEW

**Comment by samphilipd** [comment]
@josevalim the tests seem to be failing on OTP 18.0 and I have no idea why... something to do with parallel compilation deadlock?

**Comment by josevalim** [comment]
I will investigate. It seems to be state from one test leaking to the other. I have restarted that job for now.

**Comment by josevalim** [comment]
It is unrelated to this PR though, so no worries.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
