### PR TITLE
Rename type value "var" in typespec guards

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by ericmj** [comment]
What's the reason for changing `var` to `term`, maybe I missed a discussion around it? If this is the recommendation we should change the typespecs to reflect this.

**Comment by eksperimental** [comment]
@ericmj it was not _sort of_ discussed here, by @lexmag
https://github.com/elixir-lang/elixir/pull/5391#discussion_r86257839

I think having `term`, `any` and `var`, is too much, while var IMO doesn't add any new semantic value to what we have in `term` and `any`.

**Comment by ericmj** [comment]
Okay, I think @lexmag didn't find the docs for `var` in `typespecs.md`.

Let's use this PR to discuss if we should avoid using `var` and deprecate it. I will wait for feedback from the rest of the core team.

**Comment by lexmag** [comment]
@eksperimental apparently, I interpreted `var` incorrectly. 😞
We have it documented (but not quite clearly) and it is not an equivalent of `term`. 
We should definitely prefer `var` over `term` where possible.

**Comment by eksperimental** [comment]
@lexmag do you have any authoritative docs to read?
It's very tricky the whole guard thing in typespecs from what I could see.

**Comment by lexmag** [comment]
@eksperimental sorry, I don't have any docs, and OTP documentation will differ on this topic, also we only briefly mentioning it in [Typespecs.md](https://github.com/elixir-lang/elixir/blob/9ad2cdc084ed9bcc6acecff49d91bea668a4040f/lib/elixir/pages/Typespecs.md#defining-a-specification).
I hope one real example should clarify the difference:
```elixir
@spec qwe(val) :: val when val: term
```
is the same as:
```elixir
@spec qwe(term) :: term
```
and will be successful if we pass string and function returns integer.
While:
```elixir
@spec qwe(val) :: val when arg: var
```
enforces function argument and function result to be of the same type, but this type is not specified, but must be the same.

**Comment by eksperimental** [comment]
@lexmag and what about returning the exact same value passed..
We had a dicussion about this, https://github.com/elixir-lang/elixir/pull/5391#pullrequestreview-6904408
but now `var` having a different meaning than `term` changes the game again.

**Comment by lexmag** [comment]
@eksperimental when it is not `term` or `var`, `when` enforces tuple's shape, sign of the integer, etc.:
```elixir
@spec qwe(tuple) :: tuple
```
will be successful if we pass {1, 2, 3} function returns {:ok, 1}.
While:
```elixir
@spec qwe(val) :: val when val: tuple
```
requires function argument and function result to be tuple of the same shape and contain same types inside.

**Comment by josevalim** [comment]
Take `id(x) :: x when x: term` and `id(x) :: x when x: var`. The former means that `is_subtype(left_x, term)` and `is_subtype(right_x, term)` while the latter means `type(left_x) == type(right_x)`. The former will pass for types integer and binary while the latter won't. So the specs today are correct as is.

**Comment by ericmj** [comment]
Thanks for the explanation. Is it possible with typespecs to say that `type(left_x) == type(right_x)` and `is_subtype(left_x, term)`, how would I write that spec?

**Comment by eksperimental** [comment]
@ericmj would this work?  `@spec id(x) :: x when x: y, x: var, y: term`

Is there a way I can see how dialyzer infer types and specs? thank you.

**Pull request closed without merging**
