### PR TITLE
This example confused me before I understood it was using another library

### PR DESCRIPTION
**Pull request by ciaran**
Perhaps that could be made clear?

### CODE REVIEW

**Comment by whatyouhide** [comment]
Maybe we shouldn't mention a specific library; what if we use `use PropertyTestingLibrary` or something like this?

**Comment by josevalim** [comment]
:+1: for @whatyouhide

**Comment by ciaran** [comment]
Switched it to reference `PropertyTestingLibrary` instead.

**Comment by whatyouhide** [comment]
Thanks @ciaran! 💟

**Pull request merged**
