### PR TITLE
Improve docs for Application

### PR DESCRIPTION
**Pull request by jur0**

### CODE REVIEW

**Comment by michalmuskala** [comment]
If we're going to add this, I think it's important to mention that even though library applications don't start processes they can be normally started and stopped and need to be included as runtime dependencies in application list if needed (although that happens mostly automatically in 1.4).

**Comment by jur0** [comment]
Please check it now. I mentioned it behaves like a normal OTP application (so there is no need explicitly saying it must be included in runtime dependencies).

**Comment by fishcakez** [comment]
I think the final paragraph is a great addition. It is something we should be explicit about.

However I think we should avoid to defining `library` and `normal` applications because both are normal applications. We should not be thinking application X is a `library` application because in a future release (even patch release) it could become a `normal` application. There is not a concern outside of the application itself whether there it is a supervision tree or not. Other applications should not make any assumptions. Perhaps we could just explain the situation when there is no supervision tree without giving it a name?

**Comment by josevalim** [comment]
I agree with @fishcakez and that was the reason for not making the distinction in the first place. If we want to make a distinction, we should say "supervised applications" and "non-supervised applications" but this notation may be confused still to some.

**Comment by jur0** [comment]
Changed according to the comments

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
