### PR TITLE
Correct tense in verbs

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by eksperimental** [comment]
Please accept my last 10 PRs as part of improvements for the `v1.4` branch

**Comment by josevalim** [comment]
> Please accept my last 10 PRs as part of improvements for the v1.4 branch

Thank you so much for breaking those PRs apart. Discussion will definitely be straight-forward! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
Sure it will. some won't even need discussing at all. 
btw sorry about my previous MASSIVE commits :-P

**Pull request merged**
