### PR TITLE
add DateTime.to_unix/2 can accept non-UTC DateTime structs

### PR DESCRIPTION
**Pull request by lau**
This PR has two commits. One is general fixes of invalid types in the examples (e.g. invalid microsecond fields). The other commit makes it possible to use DateTime.to_unix with any DateTime struct, not just UTC.

### CODE REVIEW

**Comment by josevalim** [comment]
@lau those examples are not invalid. We allow you to pass an integer and, when doing so, we default to precision 6.

The other commit looks great. :D

**Comment by lau** [comment]
Oops. Some of the structs had invalid microsecond fields. But the calls to the `new` functions were valid I see. I'll revert the changes in the calls to `new`.

**Comment by lau** [comment]
The code has been updated.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
