### PR TITLE
Updating Version.compare/2 spec

### PR DESCRIPTION
**Pull request by ottolin**
Updating specs from low to high in a logical order (per comment in https://github.com/elixir-lang/elixir/pull/5349)

### CODE REVIEW

**Comment by whatyouhide** [comment]
I'm not strongly opposing to these changes but I don't see a real value in adding a commit and changing the history for this. It seems like a very minor thing, and somehow arbitrary 😕 Let's see what others think about this!

(thanks anyways for the contribution @ottolin 😃)

**Comment by lexmag** [comment]
I share @whatyouhide's feelings on it.

**Comment by eksperimental** [comment]
maybe we could wait to include these changes when we update version.ex for a different change, but I think keeping an order in the specs ease the task of understanding them.

**Comment by whatyouhide** [comment]
I don't feel like `:gt | :eq | :lt` is a hard spec to understand. Also, it's quite arbitrary to say that `:lt | :eq | :gt` is ordered while `:gt | :eq | :lt` isn't IMO, and I really don't feel changing this would make this clearer in any way 😕 But that's me, let's wait for more comments :)

**Comment by josevalim** [comment]
Closing for the reasons mentioned above.

**Pull request closed without merging**
