### PR TITLE
Document why 'mix xref' can give false positives

### PR DESCRIPTION
**Pull request by nathanl**
"False positives" might not be the best way to describe this case; if not, please advise.

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you. I have incorporated your changes into the existing description, so we provide an example. Let me know what you think.

**Comment by michallepicki** [comment]
I also have been using the term "unnecessary recompilations" at work when explaining this topic like @nathanl originally did here. "False positives" does not sound right, these are real dependencies caused by (understandable) limitations in compiler's dependency tracking model/algorithm

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by nathanl** [comment]
> `B` does not need to be recompiled, because it depends on `C` at runtime, but anything that depends on `B` at compile-time has to recompile, and that includes `A`.

I still find this confusing. I would picture the compiler saying:
- C changed, but B depends on it at runtime so B doesn't need to recompile
- A depends on B at compile time, so since B doesn't need to be recompiled, **A doesn't need to be recompiled**

... except it does. I was trying to have the docs explain *why* that's the case, but I don't really understand.

**Comment by josevalim** [comment]
Anything that is called at compile-time becomes compile-time behaviour. If you only call things at runtime, then it is all runtime. But as soon as you call something at compile-time, anything in that module and what that module calls becomes compile-time, because all of them can now change the behaviour of A.

**Comment by michallepicki** [comment]
@nathanl Here are some resources, I'm sure there are even more online:
-  [ElixirConf 2018 - Understanding Elixir's Re compilation - Renan Ranelli (conference talk)](https://www.youtube.com/watch?v=hqaxMZAwbBA)
- [Wojtek Mach - Speeding up re-compilation of Elixir projects (blog post)](https://dashbit.co/blog/speeding-up-re-compilation-of-elixir-projects)
- [Thinking Elixir - Compile Faster with Marc-André Lafortune (podcast)](https://podcast.thinkingelixir.com/60)
- [Tim Gent - How to speed up your Elixir compile times (blog post series)](https://medium.com/multiverse-tech/how-to-speed-up-your-elixir-compile-times-part-1-understanding-elixir-compilation-64d44a32ec6e)
- [Exploring Elixir Project Re compilation | Anton Satin | ElixirConf EU 2022 (conference talk)](https://www.youtube.com/watch?v=09LMYIclZdo)
- [Understanding Elixir Compilation by Tim Gent | ElixirConf EU 2023 (conference talk)](https://www.youtube.com/watch?v=kUrwGppYPVU)

**Pull request merged**
