### PR TITLE
Mix: allow installing a dependency not wrapped in a list

### PR DESCRIPTION
**Pull request by azizk**
I would find it very convenient to be able type `Mix.install :jason` in the console. The list brackets bother me a lot. :sweat_smile:

### CODE REVIEW

**Comment by josevalim** [comment]
I would rather not relax the API so much because it can easily expand to a request to support `Mix.install {:jason, ">= 1.0"}` and so on. Thanks!

**Comment by azizk** [comment]
Yes, sure! The code I wrote allows it. Why shouldn't it? I don't see any possible downsides. Please reconsider. :pray:

**Comment by josevalim** [comment]
It is not really a common pattern in Elixir and I am not sure we should start allowing it. There are likely many other places we could apply the same rule. For example, should we allow it here?

```
defmodule Foo do
  defstruct :bar
end
```

If something expects a list of things, then it should be a list of things.

**Comment by wojtekmach** [comment]
> The list brackets bother me a lot.

Since forever you can add a ~/.iex.exs but since Elixir 1.15 or 1.16 you can immediately import modules defined there. If you're bothered by extra brackets you can define your custom install function like this:

```elixir
# ~/.iex.exs

defmodule Helpers do
  def install(deps, options \\ []) do
    Mix.install(List.wrap(deps), options)
  end
end

import Helpers
```

```
$ iex
iex> install :jason
Resolving Hex dependencies...
Resolution completed in 0.012s
New:
  jason 1.4.1
* Getting jason (Hex package)
==> jason
Compiling 10 files (.ex)
Generated jason app
:ok
```

**Comment by azizk** [comment]
Okay, but shouldn't we at least distinguish between language constructs and language tools? I agree, it doesn't look good with `defstruct`, also with `@enforce_keys` and probably many others. That's totally fine. But not everything in the standard lib and external Elixir libraries is perfectly consistent, is it?

Maybe it's not a strong example but I'm thinking of `Phoenix` and defining HTML views with `use MyAppWeb, :html`. Very often the `use` macro takes an options list, but in this case you can pass a single atom, which of course is the most elegant syntax.

I'm not sure but is it very uncommon to have functions that wrap an argument (e.g. `ids`) in a list to avoid code duplication and provide convenience? I guess many projects have functions like that.

`Mix.install/2` is often used in the console or in scripts. Does it really have to be that strict? It already allows for conveniences, like defining an atom `:jason` instead of having to write `{:jason, "..."}`. Maybe give it some more consideration? :pray: :grinning:

**Comment by azizk** [comment]
Thanks for the suggestion, @wojtekmach! That's pretty good, but the downside is that it depends on this home `.iex.exs` file, which solves it for your machine, but not necessarily for remote machines (or other local work machines). Sure you can add it to the project's `.iex.exs` file, but regardless I think it would be nice if the public `Mix.install/2` API were more convenient, for novices and pros alike... :grinning:

It's also worth noting that the function is called `install` and not `install_apps` or `install_libs`. I think it reads nicely when you write `Mix.install :jason` instead of `Mix.install [:jason]` .

**Pull request closed without merging**
