### PR TITLE
Remove code to show how modification check is not covered by test suite

### PR DESCRIPTION
**Pull request by marcandre**

### CODE REVIEW

**Comment by josevalim** [comment]
FWIW, I get 16 failures after this change locally:

```
==> mix (ex_unit)
Excluding tags: [windows: true]

......................................................................

  1) test recompiles after struct path dependency changes (Mix.UmbrellaTest)
     test/mix/umbrella_test.exs:453
     Assertion with == failed
     code:  assert Mix.Tasks.Compile.Elixir.run(["--verbose"]) == {:ok, []}
     left:  {:noop, []}
     right: {:ok, []}
     stacktrace:
       test/mix/umbrella_test.exs:463: anonymous fn/1 in Mix.UmbrellaTest."test recompiles after struct path dependency changes"/1
       (mix 1.13.0-dev) lib/mix/project.ex:353: Mix.Project.in_project/4
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/umbrella_test.exs:454: (test)



  2) test recompiles after compile time path dependency changes (Mix.UmbrellaTest)
     test/mix/umbrella_test.exs:391
     Assertion with == failed
     code:  assert Mix.Tasks.Compile.Elixir.run(["--verbose"]) == {:ok, []}
     left:  {:noop, []}
     right: {:ok, []}
     stacktrace:
       test/mix/umbrella_test.exs:399: anonymous fn/1 in Mix.UmbrellaTest."test recompiles after compile time path dependency changes"/1
       (mix 1.13.0-dev) lib/mix/project.ex:353: Mix.Project.in_project/4
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/mix/umbrella_test.exs:393: anonymous fn/0 in Mix.UmbrellaTest."test recompiles after compile time path dependency changes"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/umbrella_test.exs:392: (test)

..............

  3) test reloads app in app tracer if .app changes (Mix.UmbrellaTest)
     test/mix/umbrella_test.exs:477
     Assertion with == failed
     code:  assert Mix.Task.run("compile", ["--verbose"]) == {:ok, []}
     left:  {:noop, []}
     right: {:ok, []}
     stacktrace:
       test/mix/umbrella_test.exs:502: anonymous fn/1 in Mix.UmbrellaTest."test reloads app in app tracer if .app changes"/1
       (mix 1.13.0-dev) lib/mix/project.ex:353: Mix.Project.in_project/4
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/umbrella_test.exs:478: (test)

........................................................................................

  4) test --stale doesn't write manifest when there are failures (Mix.Tasks.TestTest)
     test/mix/tasks/test_test.exs:82
     Assertion with =~ failed
     code:  assert mix(["test" | opts]) =~ expected
     left:  "No stale tests\n"
     right: "1 test, 1 failure"
     stacktrace:
       test/mix/tasks/test_test.exs:94: anonymous fn/0 in Mix.Tasks.TestTest."test --stale doesn't write manifest when there are failures"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/test_test.exs:83: (test)

.....

  5) test --stale runs tests that depend on modified modules (Mix.Tasks.TestTest)
     test/mix/tasks/test_test.exs:66
     Assertion with =~ failed
     code:  assert mix(["test" | opts]) =~ expected
     left:  "No stale tests\n"
     right: "1 test, 0 failures"
     stacktrace:
       test/mix/tasks/test_test.exs:73: anonymous fn/0 in Mix.Tasks.TestTest."test --stale runs tests that depend on modified modules"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/test_test.exs:67: (test)

...............................................................................................................................................................................

  6) test prints warnings from non-stale files with --all-warnings (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:627
     Assertion with == failed
     code:  assert capture_io(:stderr, fn -> Mix.Tasks.Compile.Elixir.run(["--all-warnings"]) end) == ""
     left:  "\e[33mwarning: \e[0mvariable \"unused\" is unused (if the variable is not meant to be used, prefix it with an underscore)\n  lib/a.ex:2\n\n"
     right: ""
     stacktrace:
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:628: (test)



  7) test does not treat remote typespecs as compile time dependencies (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:603
     Assertion failed, no matching message after 0ms
     Showing 1 of 1 message in the mailbox
     code: assert_received {:mix_shell, :info, ["Compiled lib/a.ex"]}
     mailbox:
       pattern: {:mix_shell, :info, ["Compiled lib/a.ex"]}
       value:   {
                  :mix_shell,
                  :error,
                  ["warning: mtime (modified time) for \"lib/a.ex\" was set to the future, resetting to now"]
                }
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:622: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test does not treat remote typespecs as compile time dependencies"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:604: (test)

.

  8) test compiles dependent changed files (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:315
     Assertion with == failed
     code:  assert Mix.Tasks.Compile.Elixir.run(["--verbose"]) == {:ok, []}
     left:  {:noop, []}
     right: {:ok, []}
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:336: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test compiles dependent changed files"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:316: (test)

.

  9) test compiles mtime changed files (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:198
     Assertion failed, no matching message after 0ms
     The process mailbox is empty.
     code: assert_received {:mix_shell, :info, ["Compiled lib/a.ex"]}
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:220: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test compiles mtime changed files"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:199: (test)

..

 10) test recompiles modules with exports tracking (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:356
     Assertion with == failed
     code:  assert Mix.Tasks.Compile.Elixir.run(["--verbose"]) == {:ok, []}
     left:  {:noop, []}
     right: {:ok, []}
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:384: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test recompiles modules with exports tracking"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:357: (test)

.

 11) test compiles size changed files (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:228
     Assertion failed, no matching message after 0ms
     The process mailbox is empty.
     code: assert_received {:mix_shell, :info, ["Compiled lib/a.ex"]}
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:244: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test compiles size changed files"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:229: (test)

..

 12) test verify runtime dependent modules that haven't been compiled (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:787
     Assertion with =~ failed
     code:  assert output =~ "A.foo/0 is undefined or private"
     left:  ""
     right: "A.foo/0 is undefined or private"
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:835: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test verify runtime dependent modules that haven't been compiled"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:791: (test)

.

 13) test compiles dependent changed modules (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:249
     Assertion failed, no matching message after 0ms
     Showing 1 of 1 message in the mailbox
     code: assert_received {:mix_shell, :info, ["Compiled lib/a.ex"]}
     mailbox:
       pattern: {:mix_shell, :info, ["Compiled lib/a.ex"]}
       value:   {
                  :mix_shell,
                  :error,
                  ["warning: mtime (modified time) for \"lib/b.ex\" was set to the future, resetting to now"]
                }
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:264: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test compiles dependent changed modules"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:250: (test)

...........

 14) test compiles dependent changed modules without beam files (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:269
     Assertion failed, no matching message after 0ms
     Showing 2 of 2 messages in the mailbox
     code: assert_received {:mix_shell, :info, ["Compiled lib/a.ex"]}
     mailbox:
       pattern: {:mix_shell, :info, ["Compiled lib/a.ex"]}
       value:   {:mix_shell, :info, ["Compiling 2 files (.ex)"]}

       pattern: {:mix_shell, :info, ["Compiled lib/a.ex"]}
       value:   {
                  :mix_shell,
                  :error,
                  ["warning: mtime (modified time) for \"lib/a.ex\" was set to the future, resetting to now"]
                }
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:289: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test compiles dependent changed modules without beam files"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:270: (test)

.

 15) test recompiles modules with async tracking (Mix.Tasks.Compile.ElixirTest)
     test/mix/tasks/compile.elixir_test.exs:454
     Assertion with == failed
     code:  assert Mix.Tasks.Compile.Elixir.run(["--verbose"]) == {:ok, []}
     left:  {:noop, []}
     right: {:ok, []}
     stacktrace:
       test/mix/tasks/compile.elixir_test.exs:478: anonymous fn/0 in Mix.Tasks.Compile.ElixirTest."test recompiles modules with async tracking"/1
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/tasks/compile.elixir_test.exs:455: (test)

...........................................................................................................................................................

 16) test run/2 tries to load deps if task is missing (Mix.TaskTest)
     test/mix/task_test.exs:81
     Assertion with == failed
     code:  assert Mix.Task.run("task_hello") == "Hello World v2"
     left:  "Hello World v1"
     right: "Hello World v2"
     stacktrace:
       (elixir 1.13.0-dev) lib/file.ex:1560: File.cd!/2
       test/test_helper.exs:127: MixTest.Case.in_fixture/3
       test/mix/task_test.exs:84: (test)

...........................................................................................................................................

Finished in 187.6 seconds (3.2s on load, 0.04s async, 184.3s sync)
6 doctests, 676 tests, 16 failures
```

**Comment by marcandre** [comment]
Great, I must not be running the correct command then. Sorry for the noise.

**Comment by josevalim** [comment]
Run `make test_mix` but that’s our longest suite. the README has steps to run tests in isolation, which I would recommend for convenience here :)

**Comment by josevalim** [comment]
And there is a test about mtime on compile.elixir_test.exs that you can use as a reference :) I can provide more info if needed when I am back at the computer!

**Comment by josevalim** [comment]
`make test` should run all suites, the Mix one is the last one.

**Pull request closed without merging**
