### PR TITLE
Fixed codestyle for OptionParser tests

### PR DESCRIPTION
**Pull request by AndrewDryga**
In PR #5709 @whatyouhide mentioned that this tests are violating new style guide, this PR should fix it.

### CODE REVIEW

**Comment by whatyouhide** [comment]
I am personally ok with this change, but others may feel like this is too many changes and maybe not worth it. I will not formally approve the changes but count me as 👍 :)

**Comment by AndrewDryga** [comment]
I have the same feeling, but lets see 😄

**Comment by AndrewDryga** [comment]
There are some weird test fluctuations today..

**Comment by lexmag** [comment]
Thank you @AndrewDryga!

**Pull request merged**
