### PR TITLE
Only load applications and dependencies when build embedded

### LINKED ISSUE #3544: build_embedded should only load applications that were explicitly listed in applications
The idea is to bring build_embeddded closer and closer to releases.

### PR DESCRIPTION
**Pull request by fishcakez**
Resolves #3544.

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you! @fishcakez my concern with removing the paths is that we may already have loaded stuff from it. I know it is kinda the premise of the issue, but I am afraid it will cause more confusion that won't be worth it.

For example, I will be able to start running a task from a dependency and then, after it starts my app, it will fail when invoking something in the project itself.

Thoughts?

**Comment by fishcakez** [comment]
I agree, however if running a task from a dependency the task only needs to load the relevant applications before calling app.start and their code will still be available. Are we okay if we document the advise in the commit message?

**Comment by fishcakez** [comment]
If we merge this we should change https://github.com/elixir-lang/elixir/commit/11c296e7b6bc247b7e62e5adddc003142acbf861#diff-e8cd0c0ec7d02005a0c807be1a895fb9R112 to use loaded applications, rather than started.

**Comment by josevalim** [comment]
@fishcakez I am thinking more like this workflow: I add dependency X that has a task but forget to add X to my application list. I invoke the task in X that calls app.start and then everything in X starts to fail (because we removed the path).

Instead of actually doing the work of cleaning up the paths. Maybe we can just warn? Application X was loaded but not listed in application of dependencies? I am guessing even this is not good because I may have compile-time only tasks?

**Comment by fishcakez** [comment]
Are we using the same meaning of loaded? I don't think we are. I am referring to `:application` sense and I think you to `mix` loading a dependency? Lets refer to the former as application loading and the later as dependency loading so there is no confusion.

I don't think warning about a loaded application that is not listed in applications lists is valid because the application must have been explicitly loaded/started. It is unlikely to be a mistake.

I don't think warning about a loaded dependency that is not listed in application lists is valid because the dependency could be used in a mix tasks for the same `MIX_ENV` or to compile something.

**Comment by fishcakez** [comment]
> If we merge this we should change 11c296e#diff-e8cd0c0ec7d02005a0c807be1a895fb9R112 to use loaded applications, rather than started.

We will hit the same issue with config for tasks/compile time deps here.

**Comment by josevalim** [comment]
> Are we using the same meaning of loaded? I don't think we are. I am referring to :application sense and I think you to mix loading a dependency? Lets refer to the former as application loading and the later as dependency loading so there is no confusion.

Your whole comment is perfect. I don't think there is much we can do here then. Because if can emit false warnings, we will definitely unload code when we don't want it too (for example, when running a dependency task).

**Pull request closed without merging**
