### PR TITLE
Mix: use underscore in tests and fixtures

### PR DESCRIPTION
**Pull request by eksperimental**
Standardizes the names of apps, tests, fixtures, modules the Elixir way (separating words with underscores and naming modules accordingly with CamelCase)

It also fixes an app that was wrongly named "escriptest" (not the only one "t")

### CODE REVIEW

**Comment by whatyouhide** [comment]
I think I am 👎 on renaming "Mixfile" to "Mix file"; "Mix file" sounds like a very generic file of type "Mix". I think of it as of Makefiles, Rakefiles, Gemfiles, and so on.

**Comment by josevalim** [comment]
Yes, we shouldn't rename Mixfile and we shouldn't rename the dependency status inside Mix. Those are private but Hex may depend on them.

Since the remaining of the changes are affecting mostly test, I don't think this PR is really worth it, because it will mess the history as usual but does not provide any direct benefit for users of Elixir. Thank you @eksperimental !

**Comment by eksperimental** [comment]
Agreed on the Mixfile thing.

I have to say that following a standard in **all Elixir code** maintains a higher quality of code and helps people to contribute and spot errors more easily. IMO I don't think it is only a matter of API and publicly accessible information, but also what we have in the code for developers and reviewers to see. All the contributions I have done to Elixir that were related to standardizing code have been done with this purpose very clear in mind.
The direct benefit that these changes provide is that all code looks the same, there are no surprises, and headaches.

Breaking the standard also creates this sort of snowball effect where new tests are added and they will tend to follow the current practice which breaks the standard, and we will have more code not following the standard.

Just to give a concrete example, while doing these changes I spotted this error that had been introduced 2 months ago (app name "escriptest" with only one "t"). Had the previous tests used the standard, I'm sure the new tests would have used  underscores and this wouldn't have happened.

[lib/mix/test/mix/tasks/escript_test.exs](https://github.com/elixir-lang/elixir/blob/bc2480d53749ffbd102898f5ead7e0948aa860ae/lib/mix/test/mix/tasks/escript_test.exs)
```sh
$ ag "escriptest"
lib/mix/test/mix/tasks/escript_test.exs
12:         name: "escriptest",
74:      assert_received {:mix_shell, :info, ["Generated escript escriptest with MIX_ENV=dev"]}
75:      assert System.cmd("escript", ["escriptest"]) == {"TEST\n", 0}
78:      refute_received {:mix_shell, :info, ["Generated escript escriptest with MIX_ENV=dev"]}
91:      assert_received {:mix_shell, :info, ["Generated escript escriptest with MIX_ENV=dev"]}
92:      assert System.cmd("escript", ["escriptest"]) == {"FROM CONFIG\n", 0}
147:      assert_received {:mix_shell, :info, ["Generated escript escriptest with MIX_ENV=dev"]}
159:      assert_received {:mix_shell, :info, ["* escriptest"]}
160:      refute_received {:mix_shell, :info, ["* escriptest.bat"]}
164:      Mix.Tasks.Escript.Uninstall.run ["escriptest"]
165:      assert File.regular? tmp_path(".mix/escripts/escriptest")
169:      Mix.Tasks.Escript.Uninstall.run ["escriptest"]
170:      refute File.regular? tmp_path(".mix/escripts/escriptest")
171:      refute File.regular? tmp_path(".mix/escripts/escriptest.bat")
```

Regarding the status Mix.Deps, I can confirm Hex does not use any of those values from what I was able to grep in its source code. And while this is non-public, I think it could be used by other apps, as you just mentioned Hex, and I think using the standard is the way to go.

Looking forward to hearing what you guys think

**Comment by antipax** [comment]
"escriptest" could have just as easily been "foobar". I don't think it's explicitly an error.

My personal feeling is that there's a line you can cross where applying standards becomes more of a pain than they are worth. To use your example, is "escriptest" really headache-inducing compared to "escript_test"? I think they're both totally clear.

jm2c

**Comment by eksperimental** [comment]
@antipax well, it's is not an error _per se_ since all tests are passing, but it's just an live example of how not using underscores make things harder to read and more prone to errors, as you can clearly see that's not what it was meant because you have: 
`      [app: :escripttest,`

and three lines bellow you have
```
         main_module: Escripttest,
         name: "escriptest",
```

While I agree with your feeling, I don't think it applies to this case.

thank you for your opinion :+1:

**Comment by antipax** [comment]
@eksperimental I don't necessarily agree, the name being different may have been an attempt to test that setting the name to something different than what would be automatically generated would work.

**Pull request closed without merging**
