### PR TITLE
Clarify binary comparison

### PR DESCRIPTION
**Pull request by michalmuskala**

### CODE REVIEW

**Comment by josevalim** [comment]
What if it does not have full bytes?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
What should we do with this PR?

**Comment by michalmuskala** [comment]
Sorry, I forgot about it. I asked couple people what happens in case of left over bits, but nobody seems to know. I haven't got time to actually check the OTP source yet.

**Comment by josevalim** [comment]
The comparison is bit by bit with the larger bitstring being "more than".

```iex
iex(17)> <<1::1>> > <<1::2>> # 1 > 01
true
iex(18)> <<1::1>> > <<3::2>> # 1 < 11
false
iex(19)> <<1::1>> > <<2::2>> # 1 < 10
false
iex(20)> <<1::1>> > <<0::2>> # 1 > 00
true
```

**Comment by michalmuskala** [comment]
So it seems like for the sake of comparison it treats the remaining bits as most significant bits of an additional byte and compares as if it were a complete byte.

```
iex(5)> <<1::1>> > <<1>>
true
```

If the bits are the same, the bitstring with "more bits" is considered larger:
```
iex(13)> <<0::1>> < <<0::2>>
true
```

**Comment by josevalim** [comment]
@michalmuskala ping.

**Comment by michalmuskala** [comment]
I wasn't really sure about the final wording. I went with:
> Bitstrings are compared byte by byte, incomplete bytes are compared bit by bit.

but I'm open for better proposals

**Comment by josevalim** [comment]
I am happy with this wording, thank you!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Pull request merged**
