### PR TITLE
Simplify guards by using ranges in character matching

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
The reason why we didn't use ranges is because this is performance sensitive code and the range does an extra is_integer check. I expect the Erlang compiler to be able to optimize those at this point - someone needs confirm it - but given the PR does not really change the behaviour, we can keep things as is as well. Thank you. :)

**Comment by eksperimental** [comment]
True! I forgot about the is_integer check

**Comment by michalmuskala** [comment]
In cases where the value is extracted from binary, the compiler should easily optimise this check away, in case of traversing lists, it's rather unlikely.

**Comment by eksperimental** [comment]
> In cases where the value is extracted from a binary, the compiler should easily optimise this check away, in case of traversing lists, it's rather unlikely to be optimised away.

Thank you for the clarification. So only the changes in the String module would be optimized.

**Comment by eksperimental** [comment]
> > In cases where the value is extracted from a binary, the compiler should easily optimise this check away, in case of traversing lists, it's rather unlikely to be optimised away.
> 
> Thank you for the clarification. So only the changes in the String module would be optimized.
actually, in Calendar.ISO  as well.

**Pull request closed without merging**
