### PR TITLE
Add power operator

### PR DESCRIPTION
**Pull request by josevalim**
Same semantics as in Nx.

Question: should the formatter format it as `left ** right` or `left**right`?

/cc @seanmor5 @polvalente @jonatanklosko

### CODE REVIEW

**Review by polvalente — COMMENTED** [review]
@josevalim this is nice! I personally prefer `a ** b`, because it would be consistent with the other arithmetic infix binary operators.

Also, I think that `123**-45` is a little bit uglier than `123 ** -45`

**Comment by whitepaperclip** [comment]
My 2¢ - I don't understand what the argument could be for `left**right` instead of `left ** right`. The latter is much easier to read and is consistent with the formatting of every other operator (afaik).

**Comment by josevalim** [comment]
Alright, `left ** right` it is. Thanks everyone for the input!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
