### PR TITLE
Fixing bug in Enum.dedup/1

### PR DESCRIPTION
**Pull request by sabiwara**
Hi. I just noticed that `Enum.dedup/1` isn't working properly on non-list enumerables in the 1.12-rc.0.

```elixir
[1, 1, 0, 2] |> Stream.map(& &1) |> Enum.dedup()
[1, 1, 0, 2]
```

After investigating, I realized this was a bug I introduced myself in a previous PR :see_no_evil:.
Really sorry for that.

### CODE REVIEW

**Comment by josevalim** [comment]
Great find, can you please add a test? Thank you!

**Comment by sabiwara** [comment]
@josevalim sure! Should I introduce a `EnumTest.Stream`? Current tests are basically mostly lists, ranges and maps (and this won't work to reproduce this bug)

**Comment by josevalim** [comment]
There is no need, just add a "dedup with stream" and we should be good!

**Comment by sabiwara** [comment]
Since it is a separate implementation, I just replicated the whole `dedup/1` case with streams.
If we cherry pick assertions, I wasn't sure which one to pick or not.
What do you think?

**Review by ericmj — APPROVED** [review]

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
