### PR TITLE
Document environment variable defaults

### PR DESCRIPTION
**Pull request by ericmj**

### CODE REVIEW

**Comment by hauleth** [comment]
😿

**Comment by AeroNotix** [comment]
@ericmj You had an opportunity here to switch over to better behaviour in https://github.com/elixir-lang/elixir/pull/9937 but decided to forge ahead with this with the tautological comment of: "If it's not documented it is only because it's missing in the docs."

**Comment by ericmj** [comment]
We can't switch behavior because that would be a breaking change. The Elixir community relies on being able to cache the `~/.mix` directory in scripts and in their CI environments.

In this case it was missing in the docs, since `~/.mix` is not for internal use only, just because it's not properly and explicitly documented does not mean we can go ahead and break it. We already mention the `~/.mix` directory multiple times in different contexts in the docs, and #9937 would break those documented instances in the docs. This PR clarifies how the mix directory is used, so that you don't have to infer it from reading different parts of the docs.

I understand that you would like mix to use the XDG directories by default, I would like that as well, but unfortunately we cannot make such a major breaking change.

**Comment by AeroNotix** [comment]
The PR can be further improved to falling back to the old method and also prefer using the XDG directories. It's not an either/or proposition.

**Comment by ericmj** [comment]
Please elaborate in more detail on how you propose the defaults and fallbacks should work so that we can discuss that directly.

**Comment by AeroNotix** [comment]
If the expected behaviour of certain clients is that the `~/.mix` exists, then it can be created and read from for a period of time, but preferring the configuration in XDG directories. Deprecate that behaviour, scream about it in release notes, what-have-you.

**Comment by hauleth** [comment]
@ericmj actually the only thing it would break would be `mix escript` which could be worked around by checking if the `~/.mix/escripts` is in `PATH` and then using it with together with printing warning about migration to another directory. All other uses will either work as before (`~/.mix/config.exs` would still be used if exists) or were documented lousy enough to be changed.

More - approach could be similar to the one used by Git:

- Load both `~/.config/mix/config.exs` and `~/.mix/config.exs` with second overwriting options from the first one.
- Install escripts in `~/.local/share/mix/escripts` iff there is no `~/.mix/escripts` in `PATH`. If there is `~/.mix/escripts` then print warning or silently migrate form one directory to another (potentially leaving symlink).
- Install archives in `~/.local/share/mix/archives`. If there is `~/.mix/archives` then behave in similar vain to the escripts directory.

Additionally we could add more configuration locations (using `XDG_DATA_DIRS` and `XDG_CONFIG_DIRS` allowing system-wide installations or configurations).

**Comment by ericmj** [comment]
> Deprecate that behaviour, scream about it in release notes, what-have-you.

That's how we usually deprecate things, but the breaking change would come in the major release, Elixir 2.0.

**Comment by ericmj** [comment]
> actually the only thing it would break would be mix escript which could be worked around by checking if the ~/.mix/escripts is in PATH and then using it with together with printing warning about migration to another directory.

It would also break `/.mix/archives` and `~/.mix/config.exs`. But this ignores that the community already assumes that `~/.mix` will be used by default, and that it's intentional that `~/.mix` should be used by default since it's not an internal directory, it being documented or not.

> Install escripts in ~/.local/share/mix/escripts iff there is no ~/.mix/escripts in PATH

This does not help, since I doubt people are pre-creating the escripts directory in scripts or CI.

> Install archives in ~/.local/share/mix/archives. If there is ~/.mix/archives then behave in similar vain to the escripts directory.

We can't do this for the same reason as escripts.

**Comment by josevalim** [comment]
@AeroNotix the original comment who mentioned that `~/.mix` is not documented was plain inaccurate. See:

* https://hexdocs.pm/mix/Mix.Tasks.Archive.html
* https://hexdocs.pm/mix/Mix.Tasks.Escript.html
* https://hexdocs.pm/mix/Mix.Tasks.Escript.Install.html
* https://hexdocs.pm/mix/Mix.Tasks.Help.html
* https://hexdocs.pm/mix/Mix.Tasks.Local.Rebar.html

And also in the man files. So if someone had spent 5 minutes to find references for `~/.mix` in the docs, they would have found it. This commit is just about adding the documentation to one *extra* place.

We are not going to introduce a change that can break other people code's and scripts.

**Pull request merged**
