### PR TITLE
Add missing arguments to man pages

### PR DESCRIPTION
**Pull request by eugulixes**
I described in `elixir(1)` and `iex(1)` the options which [have recently appeared](https://github.com/elixir-lang/elixir/blob/master/CHANGELOG.md) in the utils.

* `--boot`
* `--boot-var`
* `--erl-config`
* `--pipe-to`
* `--rpc-eval`
* `--vm-args`

Also I added the following options which had been missing for a quite long period of time.
* `-h, --help`
* `-v, --version`
* `--logger-otp-reports`
* `--logger-sasl-reports`
* `--werl`
* `--eval` (the short variant of the option was in the man pages from the very beginning)

### CODE REVIEW

**Comment by eksperimental** [comment]
Hi Eugene, I would like to make a suggestion that I have noticed long time ago. I think the AUTHOR section of the man pages should list the Author of the Elixir project, who are the Elixir core team, and Jose Valim, Plataformat tech or whatever it decided to go into that section, but not the author of the man pages.
Every project that I have used when I check the man pages, lists the Author of the package.
Thank you.

**Comment by eugulixes** [comment]
Agreed. I should put either José Valim or Plataformatec or both first on the list.

**Comment by josevalim** [comment]
This looks great @eugulixes, thank you! About the authorship what do you think about:

    Elixir is maintained by the Elixir Core Team.

    This manual page was contributed by Evgeny Golyshev.

    Copyright (c) 2012 Plataformatec.

**Comment by eugulixes** [comment]
@josevalim, thank you.
Speaking about the authorship -- I guess this is what we need. I reflected the suggestion in the latest changes.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
