### PR TITLE
Use new ExDoc extras auto-links

### PR DESCRIPTION
**Pull request by wojtekmach**
Ref: https://github.com/elixir-lang/ex_doc/pull/1140

We rename "Library Guidelines.md" to "library-guidelines.md", etc. This way, a given filename works both as a link on GitHub and when rendered on ExDoc (it's automatically rewritten to .html/.xhtml.) This works even with fragments!

### CODE REVIEW

**Comment by wojtekmach** [comment]
Oops, this needs some more work, will re-open later.

**Comment by wojtekmach** [comment]
Not sure why GitHub won't render links :( e.g. in https://github.com/elixir-lang/elixir/blob/1bcd0ab2ab24eae852a4e4e80e97acd8de506299/lib/elixir/pages/Library%20Guidelines.md#getting-started 

image

**Comment by josevalim** [comment]
@wojtekmach maybe because of whitespaces? what if you remove them?

**Comment by josevalim** [comment]
@wojtekmach maybe try rewriting all filenames to the filenames ExDoc would actually generate?

**Comment by wojtekmach** [comment]
@josevalim yeah, whitespace was the issue:

image

image

**Comment by wojtekmach** [comment]
you're suggesting to `mv "Syntax Reference.md" syntax-reference.md` etc? I can definitely do that.

**Comment by josevalim** [comment]
Yes, exactly
-- 


*José Valimhttps://dashbit.co/ <https://dashbit.co/>*

**Comment by wojtekmach** [comment]
Updated!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
