### PR TITLE
Add documentation with examples how to assert return values and capture IO output a the same time

### PR DESCRIPTION
**Pull request by jeznet**

### CODE REVIEW

**Comment by josevalim** [comment]
Can you please amend the commit message to remove the tags and to be in the present tense? Also, please remove the extra new line before the `end` (which was not there before). Thank you!

**Comment by jeznet** [comment]
@josevalim Done

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by jeznet** [comment]
Thank you!

**Pull request merged**
