### PR TITLE
increase assert_receive's default timeout

### LINKED ISSUE #3346: Consider increasing assert_receive default timeout
Or at least make it configurable. Sometimes 100ms ends up being triggered in slow environments like CI. Maybe we should increase it to 500ms?

### PR DESCRIPTION
**Pull request by tony612**
resolve #3346

### CODE REVIEW

**Comment by josevalim** [comment]
Shouldn't we also change the "refute_receive" timeout? The issue is that increasing that one means slower test suites. Maybe we should make refute_receive timeout explicit as it means you will literally have to wait for that time?

**Comment by josevalim** [comment]
Also, it would be nice to make those configuration options.

**Comment by josevalim** [comment]
Also, I would like more feedback before moving on with any of these changes. :)

**Comment by edgurgel** [comment]
I will give my feedback cause I use them a lot. 

I agree with the configuration option (a @attribute or ex_unit application env?) and also the explicit on `refute_receive` as it's not just a timeout but really waiting for something to *not* happen.

**Comment by philss** [comment]
I don't know if it makes sense, but would be nice to configure `assert_receive` timeout like we do with `async` option.

E.g.:
```elixir
use ExUnit.Case, assyc: true, receive_timeout: 500
```

This would be useful in specific contexts where the message would take more time.

For a "global" test configuration, something that goes in the test helper file would be great! Something like passing an option to `ExUnit.start/1`.

**Comment by gjaldon** [comment]
:+1: on the explicit timeout on `refute_receive` and the config option for timeout as option to `ExUnit.Case` and/or passed to ex_unit application env. Option to `ExUnit.Case` for module-wide config of timeout and appication env for global config of timeout. I prefer the option for `ExUnit.Case` to `@attribute` since there's no problem of name clashes.

**Comment by josevalim** [comment]
I don't think we need a local one because it is easily solvable by storing on whatever attribute and passing it explicitly. We just need :assert_receive_timeout and :refute_receive_timeout configurations on ExUnit.

**Pull request closed without merging**
