### PR TITLE
Mention in fun doc that Keyword.delete/2 is inlined by the compiler

### PR DESCRIPTION
**Pull request by eksperimental**
[skip CI]

### CODE REVIEW

**Comment by josevalim** [comment]
This function is not inlined by the compiler. :)

**Comment by eksperimental** [comment]
> This function is not inlined by the compiler. :)

So what does this mean then?

https://github.com/elixir-lang/elixir/blob/5d5b842168a5e6ab807e9652036aebebb2037e9c/lib/elixir/lib/keyword.ex#L539-L540

**Comment by josevalim** [comment]
This is internal to the module, it does not really leak to users, while the other ones change their external representation.

**Comment by josevalim** [comment]
To be clear, this applies only to callers within the same module.

**Comment by eksperimental** [comment]
I can see the difference now. Thanks for clarifying it. I think it should be documented.

**Pull request closed without merging**
