### PR TITLE
Remove boolean and number as builtin types

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Review by ericmj — APPROVED** [review]

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by adkron** [comment]
I watch all of the PRs to help learn more. I spend time trying to understand the decisions. I'd love to understand this more.

Does replacing the boolean type with a union do anything other than reduce some of the code? Is this going to speed things up? Does it open up for some kind of new feature?

Please don't feel obligated to answer. If you'd like to share I would be grateful.

**Comment by josevalim** [comment]
It is mostly to simplify the code as we reduce the number of builtin-types. All builtin-types need to be carefully considered by different parts of the code.

**Comment by josevalim** [comment]
Also, to be clear, this has no impact on user land whatsoever. is_boolean/1, is_number/1 and so on are still around. :)

**Comment by adkron** [comment]
@josevalim, thank you for taking the time to reply. ❤️ 💛 💜 💙 💚

**Pull request merged**
