### PR TITLE
Debugging Code In Windows Batch Files

### PR DESCRIPTION
**Pull request by OnorioCatenacci**
Added a user option to make it a little easier to debug Windows batch files when something isn't working as expected.  The way it's added it should only change things if the user actively changes their environment.  That is, by default, the behavior should be the same.

### CODE REVIEW

**Comment by josevalim** [comment]
Just for curiosity, how would you set it?

**Comment by josevalim** [comment]
Should we rather call it `ELIXIR_CLI_ECHO` to mimic the other environment variables?

**Comment by OnorioCatenacci** [comment]
Hi José,

1.) If they define the ELIXIR_CLI_ECHO environment variable to anything
(True, On, Whatever They Want) it will have the effect of echoing all the
commands to stdout.  If it's not defined, nothing different will happen
from what we have right now. This way they should only see the output if
they intentionally modify their environment.

2.) I like your name better than mine. :)  I modified the batch files and
the pull request should pick up the new name.

--
Onorio



On Tue, Dec 1, 2015 at 11:30 AM, José Valim <notifications@github.com>
wrote:

> Should we rather call it ELIXIR_CLI_ECHO to mimic the other environment
> variables?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/pull/4028#issuecomment-161022726>.
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
By the way, since you're probably wondering; I've been working with Paul Schoenfelder to try to get exrm working better on Windows. One of the things that came up was a simple, standard way to see what the various batch files are doing when they're run.  I figured since I needed that for the exrm stuff, it might also be useful on the mainline stuff. 

--
Onorio

**Comment by josevalim** [comment]
@OnorioCatenacci can we keep the variable name all uppercase? it would fit better with the other env variables in Elixir. Then please squash all commits into one. :) Thank you!

**Comment by OnorioCatenacci** [comment]
Hi Jose,

Seems like squashing everything into one commit is a bit tougher than I thought it would be.  You can close this pull request and I'll make the changes to get it all to one commit and submit another pull request.  I want to get this right--just didn't realize that I was so weak at using git. :)

**Comment by lexmag** [comment]
Hey @OnorioCatenacci, you could `git reset HEAD~5` in your current branch, and then `git commit` as it was one single commit, then `push --force` to make you changes present in current PR.

**Comment by OnorioCatenacci** [comment]
Thanks Aleksei--I'm already taking steps to remedy this.

On Tue, Dec 1, 2015 at 12:19 PM, Aleksei Magusev <notifications@github.com>
wrote:

> Hey @OnorioCatenacci <https://github.com/OnorioCatenacci>, you could git
> reset HEAD~5 in your current branch, and then git commit as it was one
> single commit, then push --force to make you changes present in current
> PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/pull/4028#issuecomment-161038148>.
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Pull request closed without merging**
