### PR TITLE
Update license year in NOTICE, README, LICENSE

### PR DESCRIPTION
**Pull request by tejasmanohar**
Looks like the LICENSE had a 2012 copyright- shouldn't that be modified to 2015?

### CODE REVIEW

**Comment by eksperimental** [comment]
that's the beginning of the period, nor the current year, neither the end.

**Comment by tejasmanohar** [comment]
@eksperimental ah i see. shouldn't it be a year range then? (i may be mistaken)

**Comment by eksperimental** [comment]
i was removed purposedly to not to have to update it every year.
If you read the history of the commits you will find it.
It said something like "it's not required the currect year, only the year that development began"

**Comment by tejasmanohar** [comment]
@eksperimental fair enough. didn't know that was applicable/valid

**Comment by eksperimental** [comment]
I don't know either whether that's valid or not, but that was the reason behind the change ;-D

**Pull request closed without merging**
