### PR TITLE
feat: access lists and tuples by index

### PR DESCRIPTION
**Pull request by JVMartyns**
feat: access list and tuples by index

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @JVMartyns! The access behaviour, as per its documentation, should only be implemented for dictionary/key-value like data structures. Maybe this is something that could be lifted, but it would require a more elaborate proposal. And, in any case, we don't want to expose it for lists, given index-based lookups are linear in nature.

**Comment by josevalim** [comment]
Thank you!

**Comment by JVMartyns** [comment]
Grateful for the attention. The idea was just to suggest a more natural way to access elements in lists through indexes. 🙂

**Comment by josevalim** [comment]
Yeah, in Elixir that's almost always an anti-pattern. Instead you think of list traversals using the functions in `Enum`. :)

**Pull request closed without merging**
