### PR TITLE
Range: to_charlist/1 and to_string/1 + Protocols

### PR DESCRIPTION
**Pull request by eksperimental**
Currently we can get the binary representation of a range via `inspect`, but not through another way.

### CODE REVIEW

**Comment by whatyouhide** [comment]
I'm not sure, why would ranges get a string representation but maps/tuples/etc not?

**Comment by josevalim** [comment]
I don't think we should implement to_string for ranges. Using `1..3` is the format that makes sense for Elixir, it is not a general representation though.

**Comment by eksperimental** [comment]
I see now the reasoning behind it.
Are you interested in merging the optimization for the Range protocol impl.? https://github.com/elixir-lang/elixir/pull/4605/commits/5c75a4b38ed26c4ca20530c44dc84fa42110ba62

**Comment by josevalim** [comment]
It is a very tiny optimization, we could add it, but it is not a large again. Specially because they should always be integers.

**Comment by eksperimental** [comment]
Could be tiny..  but also look at how many extra sub-calls there will be:  `Inspect.Algebra.to_doc/2` -> `Inspect.inspect/2` -> `Integer.to_string/2` + `Integer.base_to_value/2` + `Inspect.prepend_prefix/2`.

but in terms of performance, that could be negligible

**Pull request closed without merging**
