### PR TITLE
Note that string literals are not supported in typespecs

### PR DESCRIPTION
**Pull request by nathanl**

### CODE REVIEW

**Comment by whatyouhide** [comment]
@josevalim maybe we want to warn on these kind of typespecs, like we do for `string()`? I can do that if it sounds like a good idea.

**Comment by josevalim** [comment]
We should definitely warn or even raise.

**Comment by whatyouhide** [comment]
I believe raising, while maybe not being a superduper breaking change, will break a lot of code 😬 

I can work on the warning thoug 🙃

**Comment by josevalim** [comment]
:+1: for warning then :)

**Comment by viniciusmuller** [comment]
Hey @josevalim and @whatyouhide, I gave this a try and it seems we already raise with `Kernel.TypespecError` in elixir main for all the cases of having string literals in types/specs

```elixir
defmodule A do
  # raises
  @type a :: "foo"

  # raises
  @type b :: %{
    "a" => integer()
  }

  # raises
  @spec greet(integer()) :: "bar"
  def greet(_i), do: "bar"

  # raises
  @spec greet("foo") :: integer()
  def greet("foo"), do: 10

  # raises
  @spec greet(%{"a" => integer()}) :: integer()
  def greet("foo"), do: 10

  # raises
  @spec greet(binary()) :: %{"b" => integer()}
  def greet("foo"), do: 10
end
```

Maybe I might be missing something here, but I think this case is already being handled

**Comment by nathanl** [comment]
Yes, the compiler raises an error like `(CompileError) path/to/file:1: unexpected expression in typespec: "foo"`. But I still think that explicitly saying in the docs "you can't put strings in typespecs" would be useful. Otherwise the user is left to wonder "am I supposed to specify the string a different way?"

**Comment by josevalim** [comment]
I usually don't like to document what you cannot do. There are many things you can't do in typespecs, you can't add numbers, you can't specify floats nor strings. You can have regexes nor lists with several elements, etc. So we could improve the error message if necessary but I'd prefer to not list it and focus on what you can do.

**Pull request closed without merging**
