### PR TITLE
Clarify codepoint/grapheme in String docs

### PR DESCRIPTION
**Pull request by henrik**
Looked into this and found the examples less clear than they could be about this distinction.

### CODE REVIEW

**Comment by josevalim** [comment]
You broke the build. :) That's because there are many ways of writing é in Unicode, you are using two different notations. You should fix the last example.

**Comment by henrik** [comment]
@josevalim Hehe, that was precisely the distinction I was trying to clarify with these docs :D Hoist by my own petard. Let's see if I can fix this…

**Comment by henrik** [comment]
@josevalim Tests pass :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
