### PR TITLE
Change the word "duplicated" to "duplicate"

### PR DESCRIPTION
**Pull request by azizk**
The word *duplicated* isn't wrong but *duplicate* sounds better in these cases. :+1:

### CODE REVIEW

**Comment by romul** [comment]
To me `duplicate` sounds unusual in these cases. It's much harder to understand the actual meaning for non-native speakers, b/c `duplicate` sounds like a verb or a noun.

**Comment by whatyouhide** [comment]
Agreed (as a non-native speaker). Any native speakers care to chime in? 😄

**Comment by greg-rychlewski** [comment]
I'm a native speaker and I wouldn't blink an eye if either was used. English can be weird and as far as I know both words can be used as an adjective.

**Comment by azizk** [comment]
I'm not a native speaker but I have a good feeling for the language. Both words are grammatically correct, but I can still see a small difference. The word `duplicated` has a more active sense, as in "something was copied or replicated", so it implies an act of duplication has taken place. Whereas `duplicate` is passive and only describes the actual fact that identical items appear multiple times.

Regardless of this distinction I think it's also good to be consistent. The word `duplicate` is used throughout the `Keyword` documentation, for example. I guess we could leave the `supervisor/spec.ex` and `src/elixir_clauses.erl` files unchanged, but the other cases I'd definitely recommend to update. :+1:

**Comment by simonmcconnell** [comment]
I'm a native English speaker and I believe this change (using duplicate or duplicates) is correct.  

It's a bit confusing because duplicate can be an adjective, noun or verb. Duplicated is past tense.

In some instances it might be better to use identical.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
