### PR TITLE
Add URI.parse/2 with :loose option

### PR DESCRIPTION
**Pull request by tverlaan**
In the current implementation only URI's that match the regex  as in RFC3986 are parsed. However as stated on Wikipedia[0] some schemes don't require `//` to be in the URI. This PR adds a `:loose` option to `parse` so it can parse those URI's which don't `:strict`ly confirm to the regex as in RFC3986. Apart from the double slash, parsing of the URI's is the same.

I'm not 100% sure if this should be part of `URI` but you would need to duplicate some code to implement this elsewhere. It also doesn't seem *Uniform* if there are two URI parsers.

[0] https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax
> Two slashes (//): This is required by some schemes and not required by some others. When the authority component (explained below) is absent, the path component cannot begin with two slashes.

### CODE REVIEW

**Comment by josevalim** [comment]
There are actually multiple ways to parse URLs driven by different RFCs and committees. Therefore I would prefer to adhere to a single RFC otherwise it will lead to a slippery slope of us having to support multiple formats.

Therefore, if this is supported by the RFC, we would be glad to support it. Otherwise I don't think it belongs in Elixir's URI.

Thank you!

**Comment by tverlaan** [comment]
Thanks for your feedback. It is **not** supported by RFC3986 (section 3 clearly states a literal `//`). I was hoping that we could use Wikipedia's understanding of URI's as that seems to be the common understanding anyway. That would also guard the slippery slope I think.

**Comment by josevalim** [comment]
Unfortunately common sense does not apply to URLs. For example, browsers allow URLs such as "htt\np://google.com/" and I don't think we should allow those. For a more complete description of the problem: https://tools.ietf.org/html/draft-ruby-url-problem-01

Not following a RFC or a spec is exactly the slippery slope we want to avoid because then we become part of the problem. :)

**Comment by tverlaan** [comment]
Ha, you're right. Thanks again!

**Pull request closed without merging**
