### PR TITLE
Fix recursive call in Keyword.replace_lazy helper

### PR DESCRIPTION
**Pull request by palexanderm**

### CODE REVIEW

**Comment by maco** [comment]
thanks for catching this :)

**Comment by palexanderm** [comment]
> thanks for catching this :)

No problem. I'm just excited to be making my first contribution to my favourite language, no matter minuscule. :D

**Comment by maco** [comment]
adding that function was my first contribution too :D

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
