### PR TITLE
Add @since attributes for behavior introduced in 1.5

### PR DESCRIPTION
**Pull request by devonestes**
I saw [here](https://github.com/elixir-lang/elixir/blob/b9591267dc87f79178a9eba435d4765ed745f55b/lib/elixir/lib/code.ex#L43) that `@since` attributes are being added for new behavior in 1.7, and I
thought it might be helpful to go through the recent changelogs and add
those attributes for some newly introduced functions and macros. My
initial thought was to go back and add them through 1.4, but if it's
helpful to go further back then I'd be happy to do that as well.

Or, if you only want to have these attributes starting with 1.7 that's
cool too!

### CODE REVIEW

**Comment by josevalim** [comment]
@devonestes this is very appreciated, thanks!

@wojtekmach is currently working on a script that automatically generates the diffs between modules across versions, this way we will have a full list and be able to tackle it at once. :)

**Comment by josevalim** [comment]
@wojtekmach has extracted the list and I am curating them. Here is what was added on v1.5:

```
+Calendar.compatible_calendars?/2
+Calendar.ISO.add_day_fraction_to_iso_days/3
+Calendar.ISO.date_from_iso_days_days/1
+Calendar.ISO.date_to_iso8601/4
+Calendar.ISO.date_to_iso_days_days/3
+Calendar.ISO.day_rollover_relative_to_midnight_utc/0
+Calendar.ISO.iso_days_to_unit/2
+Calendar.ISO.naive_datetime_from_iso_days/1
+Calendar.ISO.naive_datetime_to_iso_days/7 
+Calendar.ISO.time_from_day_fraction/1
+Calendar.ISO.time_to_day_fraction/4
+Calendar.ISO.valid_date?/3
+Calendar.ISO.valid_time?/4
 
+Date.add/2
+Date.convert/2
+Date.convert!/2
+Date.diff/2
+Date.range/2
+DateTime.convert/2
+DateTime.convert!/2
+DateTime.diff/3

+Enum.chunk_every/2
+Enum.chunk_every/4
+Enum.chunk_while/4
+Exception.blame/3
+Exception.blame_mfa/3

+File.ln/2
+File.ln!/2
+File.ln_s!/2
+File.read_link/1
+File.read_link!/1

+Integer.gcd/2

+Keyword.replace!/3

+List.starts_with?/2

+Macro.generate_arguments/2
+Map.replace!/3

+NaiveDateTime.convert/2
+NaiveDateTime.convert!/2
 
+Registry.unregister_match/4

+Stream.chunk_every/2
+Stream.chunk_every/4
+Stream.chunk_while/4
+Supervisor.init/2
+System.stop/1
 
+Time.convert/2
+Time.convert!/2
+Time.diff/3
```

**Comment by josevalim** [comment]
Added on v1.4:

```
+Date.compare/2
+Date.day_of_week/1
+Date.days_in_month/1
+Date.leap_year?/1
+Date.utc_today/0

+DateTime.compare/2
+DateTime.from_iso8601/1
+DateTime.from_naive/2
+DateTime.from_naive!/2

+Enum.map_every/3
+Enum.split_with/2
+Enum.zip/1
 
+Float.ratio/1

+Inspect.Algebra.color/3
+Integer.floor_div/2
+Integer.mod/2

+List.myers_difference/2
+List.pop_at/3

+NaiveDateTime.add/3
+NaiveDateTime.compare/2
+NaiveDateTime.diff/3
+NaiveDateTime.utc_now/0
 
+Regex.recompile/1
+Regex.recompile!/1
+Regex.version/0

+Registry.dispatch/3
+Registry.keys/2
+Registry.lookup/2
+Registry.match/3
+Registry.meta/2
+Registry.put_meta/3
+Registry.register/3
+Registry.register_name/2
+Registry.send/2
+Registry.start_link/3
+Registry.unregister/2
+Registry.unregister_name/1
+Registry.update_value/3
+Registry.whereis_name/1
 
+Stream.map_every/3
+Stream.zip/1

+Task.async_stream/3
+Task.async_stream/5
+Task.Supervisor.async_stream/4
+Task.Supervisor.async_stream/6
+Task.Supervisor.async_stream_nolink/4
+Task.Supervisor.async_stream_nolink/6

+Time.compare/2
+Time.utc_now/0

+Mix.Project.apps_paths/1
```

**Comment by josevalim** [comment]
Added on v1.6:

```
+Access.filter/1
+Calendar.truncate/2

+Code.format_file!/2
+Code.format_string!/2

+DateTime.truncate/2

+DynamicSupervisor.code_change/3
+DynamicSupervisor.count_children/1
+DynamicSupervisor.format_status/2
+DynamicSupervisor.handle_call/3
+DynamicSupervisor.handle_cast/2
+DynamicSupervisor.handle_info/2
+DynamicSupervisor.init/1
+DynamicSupervisor.start_child/2
+DynamicSupervisor.start_link/1
+DynamicSupervisor.start_link/3
+DynamicSupervisor.terminate/2
+DynamicSupervisor.terminate_child/2
+DynamicSupervisor.which_children/1

+Enumerable.slice/1

+Inspect.Algebra.collapse_lines/1
+Inspect.Algebra.container_doc/6
+Inspect.Algebra.flex_break/1
+Inspect.Algebra.flex_glue/3
+Inspect.Algebra.force_unfit/1
+Inspect.Algebra.line/0
+Inspect.Algebra.next_break_fits/2
+Inspect.Algebra.string/1

+Kernel.defguard/1
+Kernel.defguardp/1
 
+Kernel.ParallelCompiler.async/1
+Kernel.ParallelCompiler.compile/2
+Kernel.ParallelCompiler.compile_to_path/3
+Kernel.ParallelCompiler.require/2

+List.ascii_printable?/2

+NaiveDateTime.truncate/2

+Port.demonitor/2
+Port.monitor/1

+Stream.intersperse/2

+Time.add/3
+Time.truncate/2
```

**Comment by josevalim** [comment]
Please let me know what is the best way to split this work. Maybe one PR per version?

**Comment by devonestes** [comment]
I'm happy to do all of this. This kind of housekeeping is oddly satisfying for me, and it's way easier than I thought it would be with the lists of what was added!

I think one PR per version makes sense. I'll continue on with 1.5 in this PR, and then open 1.6 and 1.4 separately.

**Comment by josevalim** [comment]
Beautiful! :heart:

**Comment by devonestes** [comment]
Ok, this is everything for 1.5 according to the list above. 1.6 and 1.4 will come in separate PRs.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by wojtekmach** [comment]
I was curious about the changes between 1.7 and master, I couldn't find the old script so here's a new one:

https://gist.github.com/wojtekmach/215a81682ef9c9e4aaf5822ed21aa4d3

As you can see there's a few missing `since: ` declarations, this could be easy contributions for new folks. cc @josevalim @devonestes

**Comment by eksperimental** [comment]
Is there a reason why we are not convering functions prior v1.4?

**Pull request merged**
