### PR TITLE
Correct guard in Enum slice optimization

### PR DESCRIPTION
**Pull request by fertapric**
cc @josevalim

### CODE REVIEW

**Comment by whatyouhide** [comment]
Was this a bug or is it just for clarity?

**Comment by fertapric** [comment]
@whatyouhide it's a bug. The `slice` function receives the start position, the amount of elements to slice, and the size of the list. The optimization is never been used because the amount of elements to slice won't be the same as the size unless the start is `0` and I think that's already optimized somewhere else.

For example, `Enum.take([1, 2, 3], -1)` would call `slice([1, 2, 3], 1, 2, 3)`.

**Comment by josevalim** [comment]
It is a fix. The clause as it was would only be true if start was 0. Good catch @fertapric!

**Comment by whatyouhide** [comment]
Should we add a test then?

**Comment by fertapric** [comment]
@whatyouhide it cannot be done easily because it's an optimization. If the optimization is not used, it just falls back to the slower default implementation.

**Comment by whatyouhide** [comment]
Ah that's what I thought, that's why I wasn't feeling it was a bug per se :) Good catch!

**Pull request merged**
