### PR TITLE
Update Enum tests

### PR DESCRIPTION
**Pull request by klippx**
Note: This is a housekeeping request, not intended to introduce any functional changes.

I had an idea, which we can shoot down or I can fully commit to if you like it: Basically I think that it would be nice if functions are specified with signature, and sorted in order within the test file. Would make it easier to find tests and have a cleaner code base.

I know some functions are already following this pattern, so this kind of a manual housekeeping task.

Summary of changes:
* Reorder test in alphabetical order.
* Specify signature for function being tested.
* Add missing tests where applicable.
* Reorder the function definitions in the main Enum file as well.

### CODE REVIEW

**Comment by josevalim** [comment]
Please go ahead. We usually don't merge style only commits but we have no open pull requests that would be affected by this, so it is a welcome improvement, thank you!

**Comment by klippx** [comment]
@josevalim Thank you for entrusting this with me. Please see the updated pull request as per agreement I have updated enum.ex and enum_test.ex

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by klippx** [comment]
@josevalim For future reference, may I do the same for Stream or any other place?

**Comment by josevalim** [comment]
@klippx go ahead with Stream but it is better to ping about the other modules. :)

**Comment by josevalim** [comment]
@klippx after some feedback we have decided to not merge further PRs because, even though it can no longer cause conflicts, it still pollutes git history (so blame is messed up) and it may make back porting fixes harder. Thank you anyway! :heart:

**Pull request merged**
