### PR TITLE
Update File doc with expected errors

### PR DESCRIPTION
**Pull request by fertapric**

### CODE REVIEW

**Comment by whatyouhide** [comment]
Might be nitpicking, but wdyt about using the wording "raise a X exception" instead of "raise X"? I think it makes things a bit clearer.

**Comment by fertapric** [comment]
@whatyouhide I started replacing "raises an exception" with "raises a `File.Error` exception", but then I saw the documentation was using "raises `File.Error`" in other places.  Both sound good to me :)

**Comment by fertapric** [comment]
@whatyouhide done in https://github.com/elixir-lang/elixir/pull/8123/commits/5e596ccda77f90f7f392e490238e40855e2786a7

**Comment by ericmj** [comment]
Thank you 💜

**Pull request merged**
