### PR TITLE
Correct grammatical number in ExUnit.Case options

### PR DESCRIPTION
**Pull request by eksperimental**
Since it is only one option available, it should be "option".

### CODE REVIEW

**Comment by whatyouhide** [comment]
I am not sure this is a good approach. We're listing supported options, and it's just a "coincidence" the options are *currently* just one. I am 110% sure that if we ever add an option there, we'll forget to turn "option" back into "options" :P. Do you have resources saying that what we have right now is definitely incorrect?

**Comment by eksperimental** [comment]
I understand your concern, but that doesnt make it grammatically correct.

**Comment by whatyouhide** [comment]
@eksperimental this is not prose so I am not sure it matters as much. I would much rather go with "options" and have a consistency than go with "option" here, forget to update it, and so on. This is technical documentation, the priority is to be clear and formal. Again, 

> Do you have resources saying that what we have right now is definitely incorrect?

**Comment by eksperimental** [comment]
Alternatively we could explicitly mention that:
>  When used, it accepts only one option:

This way it will be more evident if we ever forget to change tree lines provided we add more options in the future

**Comment by whatyouhide** [comment]
Again, I do not understand what concrete improvement this brings to the readability of the documentation. We're listing all the options this takes, it just happens that the options in the list are only one.

**Comment by eksperimental** [comment]
It's weird to my eye to read "the following options" and see only one.
What you see is what it is. Nothing else.

**Pull request closed without merging**
