### PR TITLE
Rename Enum.sample to Enum.random. Fixes #3285.

### LINKED ISSUE #3285: Rename Enum.sample to Enum.random
I would like to reserve `Enum.sample/1/2` for time based sampling.

### PR DESCRIPTION
**Pull request by modiho**

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by lexmag** [comment]
Shouldn't `Enum.sample/1` be (soft-)deprecated first?

**Comment by josevalim** [comment]
Enum.sample was never released.

**Comment by lexmag** [comment]
My bad, I remember that `Enum.sample` PR was so old (before v1.0) that I thought it was released. :smile_cat:

**Pull request merged**
