### PR TITLE
Use etc. instead of etc

### PR DESCRIPTION
**Pull request by eksperimental**
[ci skip]

### CODE REVIEW

**Comment by whatyouhide** [comment]
From my experience writing, my personal suggestion is to drop contractions like this (and "i.e.", "e.g.", and so on) because they make text easier to read for non-native English speakers. I would prefer to go with "and so on" instead of "etc." and since we're changing these occurrences, it might be a good chance to do it now. Thoughts?

**Comment by eksperimental** [comment]
I totally agree. In fact, the first paragraph of what you read in the Elixir documentation mentions "etc.".
Should we extend this change to all of them?

**Comment by eksperimental** [comment]
and we don't necessarily need to always replace them with "and so on" as there are a handful of expressions to replace them and that some would suit better than others depending on the context.

**Comment by whatyouhide** [comment]
> Should we extend this change to all of them?

Yep, IMO.

> and we don't necessarily need to always replace them with "and so on" as there are a handful of expressions to replace them and that some would suit better than others depending on the context, making the reading more natural.

As long as it's not complex English, I'm all for it :)

**Pull request closed without merging**
