### PR TITLE
titlecase support for string module

### LINKED ISSUE #9999: Add String.titlecase/2
We already have the implementation internally. Similar to capitalize but it doesn't downcase the rest of the string.

### PR DESCRIPTION
**Pull request by sushant12**
closes #9999

I am unaware of other cases that might fail String.titlecase/2 . If there is then please do let me know.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @sushant12. Apologies, I was not very precise on the description. This should not behave per word, because the concept of words is actually tricky to define. The implementation of this function should be like `capitalize`, except that we don't call downcase after. Something like this:

```elixir
  @spec titlecase(t, :default | :ascii | :greek) :: t
  def titlecase(string, mode \\ :default)

  def titlecase(<<char, rest::binary>>, :ascii)
      when char >= ?a and char <= ?z,
    do: <<char - 32, rest::binary>>

  def titlecase(string, :ascii) when is_binary(string), do: string

  def titlecase(string, mode) when is_binary(string) do
    {char, rest} = String.Casing.titlecase_once(string, mode)
    char <> rest
  end
```

Can you please update the implementation and tests accordingly? You can also use the tests from capitalize, making sure nothing is downcased.

**Comment by sushant12** [comment]
@josevalim please correct me if I am wrong.

I need to implement `String.titlecase/2` function whose implementation should be similar to `capitalize`

> except that we don't call downcase after

When I run `String.capitalize("hello world")` it returns `"Hello world"` .
Should `String.titlecase("hello world")` return `"HELLO WORLD"` ??If yes, then isnt that same as `upcase` ?

**Comment by josevalim** [comment]
```
String.capitalize("hello world") => "Hello world"
String.capitalize("HELLO WORLD") => "Hello world"
String.titlecase("HELLO WORLD") => "HELLO WORLD"
String.titlecase("hello world => "Hello world"
```

Try the code that I posted and you will see the diff. :)

**Comment by josevalim** [comment]
Hi @sushant12! I have merged #10008 which has an implementation closed to the one I had in mind. Thanks again and sorry for the lack of clarify.

**Pull request closed without merging**
