### PR TITLE
Use zero-arity instead of 0-arity and so on

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by josevalim** [comment]
One benefit of having written numbers is that it is easy to map “2-arity” to `foo/2`, especially because the word arity may be new to many.

can you think of other pros and cons in favor of one or the other? :)

**Comment by eksperimental** [comment]
IIRC we just unified this, it was also used for tuples with two-element tuples. I think reads better in English, specially for numbers from 1 to 10.
I can see the benefit for the arity case, but in the other cases I would stick to using words instead of digits.

**Comment by eksperimental** [comment]
I'm reading about it, and you can find both, and even style guides like The Chicago Manual of Style does not have a rule about it.
As of now, the word is favored over the digit, and that is the current style.
But if there's a benefit for arities let's use it.

**Comment by josevalim** [comment]
Good call. Lets go with tuple consistency then!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
