### PR TITLE
Typo fix 1

### PR DESCRIPTION
**Pull request by gliderproarc**
I think the word “normalize” on line 1615 of the kernel special forms doc should be in the past tense, so “normalized”.

### CODE REVIEW

**Comment by josevalim** [comment]
Can you please rebase your branch? It has more than 100 changes files right now. :)

**Comment by gliderproarc** [comment]
Sure thing. Sorry for the mess. First time contributing and wasn't quite sure how to make a pull request.

I'll figure it out and rebase the commit

**Comment by josevalim** [comment]
No worries! You can either try rebasing or going back to the main branch, updating the branch, and starting again with a new pull request. :)

**Comment by gliderproarc** [comment]
Thank you for your help Jose! And thank you for making Elixir!!

**Pull request closed without merging**
