### PR TITLE
`make test` individual files

### PR DESCRIPTION
**Pull request by eksperimental**
This commit allows developers to run indivual test from the `make test` command.

```sh
$ make test FILE="lib/mix/test/mix/tasks/new_test.exs lib/elixir/test/elixir/integer_test.exs"
Test file: lib/mix/test/mix/tasks/new_test.exs
==> lib/mix/test/mix/tasks/new_test.exs (exunit)
.......

Finished in 0.8 seconds (0.5s on load, 0.2s on tests)
7 tests, 0 failures

Randomized with seed 443699
Test file: lib/elixir/test/elixir/integer_test.exs
==> lib/elixir/test/elixir/integer_test.exs (exunit)
.....

Finished in 0.4 seconds (0.4s on load, 0.03s on tests)
5 tests, 0 failures
```

### CODE REVIEW

**Comment by josevalim** [comment]
You can run tests directly by using elixir path/to/test

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
yes, the thing is you need to run elixir from withing the project folder, (i.e. lib/logger), otherwise some tests will not pass because they used a relative path from that folder.

currently all these test will not pass if you call them from the root folder:
- lib/elixir/test/elixir/kernel/cli_test.exs
- lib/elixir/test/elixir/kernel/errors_test.exs
- lib/ex_unit/test/ex_unit/formatter_test.exs
- lib/logger/test/logger/backends/console_test.exs
- lib/logger/test/logger/error_handler_test.exs
- lib/logger/test/logger/formatter_test.exs
- lib/logger/test/logger/translator_test.exs
- lib/logger/test/logger/utils_test.exs
- lib/logger/test/logger_test.exs

and more new tests can fail in the future as they get updated or added.

I have updated the PR with a new commit that creates a new task for each set of tests. So we can take advantage of paralellization. tests for each project can run in parallel, plus all the files within a project run in parallel.

Another benefit over the regular elixir command is that we can include patterns

Here's an example:
`$ make -j test FILE="lib/mix/test/mix/tasks/new_test.exs lib/elixir/test/elixir/integer_test.exs lib/elixir/test/elixir/gen*_test.exs lib/mix/test/mix/tasks/compile*_test.exs"`

```
==> elixir (compile)
==> elixir (exunit)
==> files: test/elixir/gen*_test.exs test/elixir/integer_test.exs
.............................

Finished in 1.5 seconds (1.5s on load, 0.08s on tests)
29 tests, 0 failures

Randomized with seed 736729
==> mix (exunit)
==> files: test/mix/tasks/compile*_test.exs test/mix/tasks/new_test.exs
..........................................

Finished in 7.5 seconds (1.7s on load, 5.8s on tests)
42 tests, 0 failures

Randomized with seed 749196
```

**Comment by josevalim** [comment]
You can also do that with "elixir -r". I will look at the tests that do not pass. :)

**Comment by eksperimental** [comment]
there is one test that didn't pass with this command either, and is 

I don't understand how it passes `make test_stdlib`
```
  1) test macro with undefined local (Kernel.ErrorsTest)
     lib/elixir/test/elixir/kernel/errors_test.exs:467
     Expected match
     lhs:  "UndefinedFunctionError[message: \"undefined function: Kernel.ErrorsTest.MacroWithUndefinedLocal.unknown/1 (module Kernel.ErrorsTest.MacroWithUndefinedLocal is not available)\"]"
     rhs:  "UndefinedFunctionError[message: \"undefined function: Kernel.ErrorsTest.MacroWithUndefinedLocal.unknown/1 (function unknown/1 is not available)\"]"
     stacktrace:
       lib/elixir/test/test_helper.exs:88: CompileAssertion.assert_compile_fail/3
       lib/elixir/test/elixir/kernel/errors_test.exs:468
```

**Comment by eksperimental** [comment]
@josevalim still don't understand what would be the best approach to test files that are in different projects, since the helper file is required.

**Comment by josevalim** [comment]
Run multiple commands then. I really don't want to make the Makefile more complex.

**Comment by lexmag** [comment]
:+1: for keeping Makefile thin.

**Comment by eksperimental** [comment]
@josevalim could you please have a look at the first: 4fb52ecdbaac719bb282ef310887d04e4619e5ab and the last commit: e73e97a56b2f93eb89900fb6c2efab29f519859a

1. First commit moves elixir's test_helper.exs from the subfolder (test/elixir/) to the test/ folder, which is the convention used by elixir project, and by the other projects inside Elixir.

3. Last commit, requires all tests to compile.
right now, if you run `make test_*`  other than `make test_stdlib` ... and the sources have not been compiled, you will get.

```
$ make clean
$ make test_iex
==> iex (compile)
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by josevalim** [comment]
I got the last one, thank you!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request closed without merging**
