### PR TITLE
Use underscore in functions and variables

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by michalmuskala** [comment]
I'd say "pdict" is an established noun in the community, and I've only seen it written like this - without space/underscore.

**Comment by eksperimental** [comment]
alright.
just to mention, there are two modules (strcuts) named PDict in the tests

**Comment by josevalim** [comment]
Yes, definitely no underscore on pdict. :)

**Comment by josevalim** [comment]
Ping. :)

**Comment by eksperimental** [comment]
Sorry jose. Im super busy with other stuff. I will try to get this done today or tomorrow

**Comment by josevalim** [comment]
Take your time. I was just wondering if you didn't see our replies. :)

**Comment by eksperimental** [comment]
I have removed the p_dict commit, and created a new one renaming PDict structs to Pdict

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
