### PR TITLE
Update CHANGELOG.md for Mix install from SCM

### PR DESCRIPTION
**Pull request by antipax**
I thought I'd add a concrete example so people can try it out if they want, so let me know if I should remove any references to `serve_this`.

### CODE REVIEW

**Comment by lexmag** [comment]
We should not mention any specific Hex package. I think if we really want to add some package it should live under elixir-lang organization.

**Comment by josevalim** [comment]
@lexmag we could use ex_doc as an example but first we would need to make ex_doc work as a escript. Unless someone does that, our best option is to reference a third party package I would say.

**Comment by lexmag** [comment]
It really doesn't feel right to me to use third-party package, in this small example I'd rather use "artificial" package (we could use same code as in `escript.build` docs).

**Comment by whatyouhide** [comment]
I agree with @lexmag, I think it would be beneficial to use an "artificial" package for simplicity.

**Comment by josevalim** [comment]
@lexmag is working on making ex_doc work separately so let's see how it will go. :)

**Comment by lexmag** [comment]
Now we can use ExDoc as an example. :bowtie:

**Comment by josevalim** [comment]
@antipax ExDoc 0.14.5 was released and it supports escripts thanks to @lexmag. Can you please update the example? Thank you! :heart:

**Comment by antipax** [comment]
Okey dokey, updated!

**Comment by josevalim** [comment]
I am merging this manually and fixing the wrong path. Thanks @wojtekmach and @antipax !

**Pull request closed without merging**
