### PR TITLE
Better documentation for the GenServer terminate callback

### PR DESCRIPTION
**Pull request by werbitzky**
I'm an Elixir newbie and wanted to set up a cleanup for my supervised GenServer. However, it took me 2 hours to figure out, how to do this under a Supervisor and then another half hour to find the `Process.flag/2` method.
I'm not sure if the description is too long at this point but it would have saved me some time and wondering.

### CODE REVIEW

**Comment by josevalim** [comment]
@werbitzky Sorry to hear it took 2 hours but I am really, really glad you made it a pull request. Thank you!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
The beauty of free software :-0 :sighs:

**Comment by werbitzky** [comment]
Thank you for this great work – having a lot of fun with Elixir!

**Pull request merged**
