### PR TITLE
add vsn to sample application in fixtures

### PR DESCRIPTION
**Pull request by liveforeverx**
relate to bitwalker/exrm#178

### CODE REVIEW

**Comment by bitwalker** [comment]
@josevalim I know the last time this came up you said it was something we should be ignoring on the exrm side, but the issue is that these apps are located in Elixir's lib directory, which is being pulled in much like Erlang's lib directory when doing app discovery. I'd like to avoid having to explicitly whitelist/blacklist directories if possible. Is there a reason why these apps shouldn't have versions?

**Comment by liveforeverx** [comment]
Mostly all tests are passing, and failure seems to be unrelated to the change. At least, I do not see, why this app should stay unversioned.

**Comment by josevalim** [comment]
The reason I don't want to change is because exrm shouldn't be looking into them at all. If exrm is looking at them, there is a chance a bug will happen because you are looking where you should not. For example, let's imagine someone mistakenly declare a dependency named "bar". Because Elixir has a bogus "bar.app", it can now be included into the user release. Maybe, when including Elixir, you should do "lib/*/lib"?

**Comment by bitwalker** [comment]
@josevalim @liveforeverx I've fixed this by explicitly referring to the lib paths of each individual Elixir application, rather than the root lib path for Elixir, this prevents relx's app discovery from delving into the test directories. This can be closed.

**Comment by josevalim** [comment]
:+1: for your solution @bitwalker. Thanks for handling it!

**Comment by liveforeverx** [comment]
:+1: Thanks, all!

**Pull request closed without merging**
