### PR TITLE
elixir.bat: Quote file paths

### PR DESCRIPTION
**Pull request by wojtekmach**
Before this patch, if any of the boot paths contained spaces we got a failure:

image

This was also the cause of https://github.com/livebook-dev/livebook/issues/2368.

Note we are also quoting non-path values as cookies for consistency so I double-checked and that is not problematic:

```
C:\Users\User\foo bar\foo>iex --sname foo --cookie bar
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.7) - press Ctrl+C to exit (type h() ENTER for help)
iex(foo@WinDev2206Eval)1> Node.get_cookie
:bar
```

### CODE REVIEW

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by wojtekmach** [comment]
@josevalim should we back port this to v1.15?

**Comment by josevalim** [comment]
There won't be a new Elixir release. If your concern is Livebook, perhaps we can temporarily patch it there?

**Comment by wojtekmach** [comment]
Oh, ok. There's no rush. I'm updating Livebook to 1.16 anyway.

**Pull request merged**
