### PR TITLE
EEx: fix interpolation inside quotations

### LINKED ISSUE #3159: <%% should still interpolate inner <%
Today, the following code in eex `<%%= <%= "hello" %> %>` does not interpolate the inner `<%= %>`

### PR DESCRIPTION
**Pull request by oneeman**
Closes #3159.

I'm opening this in its current state since it resolves the issue as described and is self-contained.  

However, in thinking about this, I realized that the way `expr/3` finds the `%>` can be problematic (as shown in one of my comments on #3159).  In the end that turned out not to matter for quotations, since they don't need to use `expr/3`.  But it is a problem for comments, which I believe are the only other tag type that allows nested tags:

```
iex(1)> EEx.Tokenizer.tokenize("<%# <%= foo %> <%= bar %> %>", 1)
{:ok, [{:text, ' '}, {:expr, 1, "=", ' bar '}, {:text, ' %>'}]}
```

I assume this is something that should be supported, and will be happy to take care of it.  I already have the modified `expr/3` which matches the delimiters properly (I wrote it before realizing it wasn't needed for quotations).  I can do it in this PR or another one, I wasn't sure since it's related to the current issue, but not strictly speaking part of it.

On a more tangential note, there is the matter of non-delimiter appearances of `%>`.  For example, stand-alone ones now are just treated as text.  And if one appears in some Elixir code, it causes mayhem, e.g. 
```
iex(2)> EEx.Tokenizer.tokenize('<% "%>" %>', 1)                  
{:ok, [{:expr, 1, "", ' "'}, {:text, '" %>'}]}
```

Granted these are somewhat pathological cases, and the in-code case could be tricky to handle, so maybe this is something to discuss on the mailing list and take time to think about.  Just thought I'd mention it, since it involves some of the same code.

### CODE REVIEW

**Comment by josevalim** [comment]
> On a more tangential note, there is the matter of non-delimiter appearances of %>.

This is really complicated because if we want to handle it properly, for example, the ones inside quotes, we need to consider quotes, but then we need to consider interpolation, and all other formats. It can quickly go out of control. I think we should consider the first `%>` inside `<%` to be closing tag no matter what. If you don't want it, insert a escape character in the middle `%\>`.

I think this pull request is great, thanks for it. Can I ask you a favor? Can we change the third element of `{:expr, 1, "=", ' bar '}` to a char list everywhere? It will be more consistent and it will allow even unicode modifiers if one wants to in the future. :)

If you are interested, you could also look into: #3154

About the pull request. It is up to you, if you want me to merge this and you'll send another one, your call!

**Comment by oneeman** [comment]
Great.  I added commits for supporting tags inside comments and changing the markers to char lists.  So it's ready for further review.  After that, I figure the way to go is to squash the first three commits together and keep the markers' commit separate.

**Comment by oneeman** [comment]
Removed the commits balancing delimiters since @josevalim found it would break some existing code which uses `"<%"`.  So this is ready now.

**Comment by ericmj** [comment]
> I think this pull request is great, thanks for it. Can I ask you a favor? Can we change the third element of {:expr, 1, "=", ' bar '} to a char list everywhere? It will be more consistent and it will allow even unicode modifiers if one wants to in the future. :)

I think we need to revert this. It's a breaking change because it changes the arguments to engines `handle_expr`.

**Comment by josevalim** [comment]
I think we will roll this is a bug fix. The current format is just too inconsistent and confusing and it is easy to fix it by checking for both "=" and '=' in a guard (that's what I have done with Phoenix).

**Pull request merged**
