### PR TITLE
Add a code of conduct

### PR DESCRIPTION
**Pull request by FlaviaFortes**
In order to promote a more inclusive community, this PR suggests a Code of Conduct to be followed by the project's contributors.

### CODE REVIEW

**Comment by FlaviaFortes** [comment]
If needed, I can update the README or CONTRIBUTING guide.

**Comment by josevalim** [comment]
Thank you! I will setup an e-mail for reporting before we merge this, so all maintainers can be reached at once, and also provide an option to address issues in private.

**Comment by guilleiguaran** [comment]
@FlaviaFortes thank you very much for this!!

**Comment by josevalim** [comment]
I am still settling some details but this will definitely be part of the 1.1 release!

**Comment by josevalim** [comment]
@FlaviaFortes can you please send an e-mail to "elixir-lang-conduct@googlegroups.com" so we can confirm delivery on our side? Thank you!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
