### PR TITLE
Run code formatter on lib/elixir/lib/uri.ex

### PR DESCRIPTION
**Pull request by udaysinghcode**

### CODE REVIEW

**Comment by josevalim** [comment]
@udaysinghcode please submit only one PR per day so we don't get overwhelmed with PRs to merge. :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by udaysinghcode** [comment]
@josevalim - oh man, super sorry! I was just trying to clean through the lib folder for you guys. My mistake. 

No worries. I finished most of the lib folder, should I continue pushing them or hold off until tomorrow?

I'm going from bottom up and just finished formatting regex.ex, should I push that or should I just wait?

**Comment by josevalim** [comment]
@udaysinghcode please wait because we have about 25 other PRs to merge and we need to do some improvements to the formatter as well.

**Comment by udaysinghcode** [comment]
@josevalim absolutely. Happy to help in any way I can. Was taking a break from work and wanted to see where I could help out. Will definitely hold back until later.

Really appreciate all the awesome work you all have done!

**Pull request merged**
