### PR TITLE
Pass --quiet on to `git clone` via `mix deps.get`.

### PR DESCRIPTION
**Pull request by rcoppolo**
Just a shot at resolving #3167  

Please let me know if this is not the best solution.

### CODE REVIEW

**Comment by MSch** [comment]
`--quiet` should also be passed to `git submodule update`.

https://github.com/rcoppolo/elixir/blob/git-clone-quiet/lib/mix/lib/mix/scm/git.ex#L113

**Comment by josevalim** [comment]
Thank you! However, I would rather make it somehow a configuration of the shell. Mix.State is private to Mix, we should not rely on those from the SCM side. Also, if we set the state to quiet for this task, we need to revert it to the original state afterwards because you can cascade multiple tasks calls.

**Comment by josevalim** [comment]
To be clear, what I am proposing is to make the default of Mix.shell.cmd/1 quiet to be `Mix.State.get(:quiet)` here:

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/shell.ex#L83

Then ensure we rollback to "no quiet" after running the task and add a test.

Another option, which would be simpler, is to have a environment variable instead of the flag. The environment variable could work for all Mix tasks transparently as long as we support it in the Mix.shell.

**Comment by MSch** [comment]
@josevalim If I read the code correctly this has the downside that in the case of an error no messages are printed either. Debugging CI builds is already highly annoying, I'd like to avoid "WIP: disable quiet to figure out what's going on" for the common cases (missing ssh keys, github down, etc)

**Comment by josevalim** [comment]
@MSch You are right. We would need to stop redirecting stderr to stdout then. We can remove the stderr_to_stdout flag and make quiet means (skip everything, except errors).

**Comment by rcoppolo** [comment]
Just so I understand, instead of passing --quiet to `mix deps.get`, it would be a shell configuration that gets accessed at the line you linked to? Where would this `:quiet` option for the shell be set?

**Comment by josevalim** [comment]
It can still be stored on Mix.State as long as it is accessed only by Mix
shells.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by alco** [comment]
What was the reasoning behind adding `--progress` in the first place? By default, git doesn't print progress unless stderr is connected to a terminal. The `--progress` option forces it to output the progress even when stderr is redirected to a file.

I've traced the addition of this option to this commit https://github.com/elixir-lang/elixir/commit/3e44e9829958d865e26be8978412584bf294494c but I can't figure out if that was a 100% well-informed decision. What am I missing?

**Comment by josevalim** [comment]
@alco if I run mix deps.get and my screen does not give me output for 2 minutes because I am cloning a git repo, I will very likely think something went wrong. The default behaviour for SCMs should be verbose in my opinion. I think --progress was added because otherwise Mix wouldn't show anything OR it would show only for some versions.

**Comment by alco** [comment]
The default behaviour is verbose for the terminal. The earliest version of Git I currently have is 1.8.2, from  2013. Its man page for `git clone` says:

> Progress status is reported on the standard error stream by default when it is attached to a terminal, unless -q is specified.

**Comment by josevalim** [comment]
> The default behaviour is verbose for the terminal.

We will have to agree to disagree. :) Showing the progress is important and it is also the git default. Even more if you have slow connections (like if you live in a village... close to the forest... with only radio internet... that gets really bad even with the smallest rain).

**Comment by alco** [comment]
Sorry, I didn't express myself clearly. I meant that git's default behaviour is already verbose by default == what we want. Passing `--progress` to it applies that verbose behaviour to non-terminal outputs which I'm arguing against here. Hence the question: why are we passing `--progress`? Why do we want to print progress into files by default?

**Comment by josevalim** [comment]
Ah, we need to pass because we are shelling out. Git will always consider our shelling out as having no terminal. :(

**Comment by josevalim** [comment]
Closing this as we need a solution that does not rely on Mix.State.

**Pull request closed without merging**
