### PR TITLE
Suppress warnings

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by lexmag** [comment]
@josevalim there one more warning is left: `get_and_update` in `Map`.
I believe we should make `get_and_update` overridable in `Dict`, right?

**Comment by josevalim** [comment]
Yes, please! We should make it overridable.

**Comment by lexmag** [comment]
Added.

**Comment by lexmag** [comment]
Can we have it merged :smile:?

**Comment by josevalim** [comment]
I thought I had merged that, sorry!

**Pull request merged**
