### PR TITLE
Add --logger-otp and --logger-sasl to the command-line args

### PR DESCRIPTION
**Pull request by whatyouhide**
This PR should address #4355.

I added the following command-line arguments to the `elixir` binary:

  * `--logger-otp true|false` - to configure the `:handle_otp_reports`
    of the `:logger` application
  * `--logger-sasl true|false` - to configure the `:handle_sasl_reports`
    of the `:logger` application

Not sure this is the best way, consider this as an attempt :). Let me know if I can do anything else!

### CODE REVIEW

**Comment by josevalim** [comment]
Perfect! We also need to do the same for Windows. :) Btw, which name is best `--otp-logger`, `--logger-otp`, `--log-otp`?

**Comment by whatyouhide** [comment]
@josevalim I like `logger` first and `otp|sasl` second, so that they both start the same. `--log-otp` doesn't sound like it uses our `:logger`, so to me the best options are the original ones `--logger-otp` and `--logger-sasl` :). Wdyt?

**Comment by lexmag** [comment]
I also like `--logger` prefix but with `-reports` suffix. :smile:

**Comment by whatyouhide** [comment]
@josevalim I added what I hope is working Windows support :). I have no way to test on Windows right now (and it would take a while to be able to set up a Windows VM because of slow internet), but the logic doesn't look too complicated. The only thing I'm not checking in `elixir.bat` is that the value of `--logger-sasl|otp` is `true` or `false` (I'm doing this check in `bin/elixir`), but I think it's ok anyways. Wdyt?

**Comment by whatyouhide** [comment]
Btw @lexmag, `--logger-otp-reports` is a viable alternative (definitely more clear), but maybe a little bit too long? I don't have a strong preference between `--logger-otp` and `--logger-otp-reports` anyways/

**Comment by josevalim** [comment]
@fishcakez any opinion on the names and/or API? :)

**Comment by fishcakez** [comment]
I like `--logger-{otp|sasl}-reports`, `--logger-otp` is not as clear.

**Comment by whatyouhide** [comment]
I'll go for `--logger-(otp|sasl)-reports` for majority of votes then :).

**Comment by whatyouhide** [comment]
@josevalim, @lexmag, and @fishcakez: updated with `--logger-otp-reports` and `--logger-sasl-reports`, it's indeed clearer this way and probably the extra length is worth it :).

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
