### PR TITLE
Fix Project docs Markdown - incorrect backticks

### PR DESCRIPTION
**Pull request by ruanpienaar**
image
Believe the backticks on `use`s, should just be uses.

### CODE REVIEW

**Comment by josevalim** [comment]
It is intentional but perhaps confusing. It is meant to point to the `use` command in Elixir :)

**Comment by ruanpienaar** [comment]
Oh! a link to `use` . ok.

**Comment by ruanpienaar** [comment]
that implements `use` `Mix.Project` maybe ... 
happy to close this :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
