### PR TITLE
Replace lhs/rhs with left/right in ExUnit.Formatter

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by whatyouhide** [comment]
Did we end up deciding to go for left/right 😕?

**Comment by josevalim** [comment]
:shipit:

**Comment by lexmag** [comment]
@whatyouhide yes, it more easily communicates the meaning, for example, the correct definition for `lhs` is almost impossible to google. Do you see any downsides?

**Comment by whatyouhide** [comment]
It's pretty easy to find out what LHS is [by Googling it](https://en.wikipedia.org/wiki/Latin_hypercube_sampling) IMO, but that may be just me.

😄 kidding ofc, that's a good point. The only downside I see was mentioned in the ML IIRC, and it's that "right" may be confused with right as in opposite of wrong, but I'm not sure that's a problem. I wasn't opposing, just checking if we ever got to an agreement for this. :)

**Comment by josevalim** [comment]
Given right always shows AFTER left, I think we are fine. :) Copying @pragdave as he was the one who proposed lhs and rhs.

**Comment by josevalim** [comment]
To give a reference, I am pretty sure I would have no idea what `lhs` and `rhs` would mean when I started programming, specially since I am not a native english speaker.

**Comment by whatyouhide** [comment]
Ah, I didn't know what they meant either, definitely. @josevalim but I brought this up exactly because we don't always show "right" after "left" according to the PR: https://github.com/elixir-lang/elixir/pull/4940/files#diff-dcedcba19e3df61c281c3e36e50e53d9L612. :)

**Comment by pragdave** [comment]
I think left and right would be OK. I think I originally went for lhs/rhs
because they were short and the same length.

**Pull request merged**
